### ISSUE TITLE
Beta Website Down! 

### ISSUE THREAD

**Issue by thatspasha** [script3/yieldblox-beta#1]
Hey there, 

I am one of your Beta Tester's. I apologize in advance, but isn't the beta website supposed to work by now? http://ybx-beta.script3.io/ 

Please have a look, I cant wait to test! Cheers. 
![Beta website down](https://user-images.githubusercontent.com/4202843/135897411-2238bad3-2f0f-4314-b0d4-ef11c4abc9aa.JPG)

**Comment by drew-boy** [comment]
There is a slight delay -- will announce when live.
