### ISSUE TITLE
Tried to lend all my USDC, got an error and the USDC is not available in my balance 

### ISSUE THREAD

**Issue by ymatienzo** [script3/yieldblox-beta#102]
This is the XDR that showed the error: AAAAAgAAAABiD6tLR3cIPJfDex4hzjXGUE48BTcKDWn66izARH97awABOIAAA6ILAAAABgAAAAEAAAAAAAAAAAAAAABhXosVAAAAAQAAAAd5YnhNaW50AAAAAAQAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAC/q4h8saqbpppj41cVZo3kOdHQh3xcVL8vqUP8YuEU7wAAAAAAAAAGAAAAAnkwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/H//////////AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAYg+rS0d3CDyXw3seIc41xlBOPAU3Cg1p+uoswER/e2sAAAACeTAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAdQ8nAzQAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAADvyddNDQ1o0j9OlfC/MH6bQyzjNh09UOtGhTUlJnGGiwAAAAJ1MDBVU0RDAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAAX90tQAAAAAAAAACHJcnMwAAAEAplGwT134UV16vexHf1VFfPA7ycs2yt6oNeqDpQ8MJOWKB0Xcl6WIaxqEuA8sOA46ScobXkb99kJcWaGPLm/gCogJh3wAAAECvsbtKcMaW2TYtTcpk2ITiy6qyXy/IQO/DlkDYiVvvw1Xi9juaqzjm/Af8860p4zC5xCSYEVJVpAJ/Q41O05EL

Stellar laboratory shows the following error when trying to submit this XDR:

![Screenshot 2021-10-07 at 08 03 01](https://user-images.githubusercontent.com/22425087/136328518-ef584c88-5603-4ddd-9d6d-81b9f0f8df84.png)

**Comment by mootz12** [comment]
This does not appear to be an issue, the `tx_bad_auth` indicates Firdausfarul is correct.
