### ISSUE TITLE
Claim YBX

### ISSUE THREAD

**Issue by husnulh4kim** [script3/yieldblox-beta#104]
![Screenshot_44](https://user-images.githubusercontent.com/58093903/136329895-74cfef47-9ae5-4e10-87e1-60102fbead66.png)
![Screenshot_45](https://user-images.githubusercontent.com/58093903/136329902-49e6a23b-ae32-4632-bffd-d8d35f9d33cc.png)
I tried to claim 0 Ybx, not fail, the transaction was successful, but Ybx balance remained 0

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/26
