### ISSUE TITLE
[Suggestions][UI] Front-end validations on lending

### ISSUE THREAD

**Issue by mixomai123** [script3/yieldblox-beta#108]
Suggestion to add validations in front-end.

For example when I try to lend more than available balance there is no validation even though available balance is present.
The error is just after the request is sent to stellar blockchain and it happens to be underfunded. 
Maybe for the UI its better not to sent requests to blockchain that are predictable to return an error?

![image](https://user-images.githubusercontent.com/43234954/136333627-a2a8e0a3-c101-4892-9bcb-95abe9f10ace.png)

![image](https://user-images.githubusercontent.com/43234954/136334076-49c1738e-0fac-448d-81bb-2533fcbbf005.png)

**Comment by mootz12** [comment]
Correct, we do not have input validation (yet).

This is coming soon, but we are tracking the work in https://github.com/script3/yieldblox-beta/issues/28
