### ISSUE TITLE
Invalid XDR on deposit

### ISSUE THREAD

**Issue by cshangjie** [script3/yieldblox-beta#11]
Depositing BTC 

Claimable Balance is created, can verify that I am the wallet owner, returns invalid xdr in RABET.

Modal gives a transaction xdr: AAAAAgAAAABF37v6yH9HH0wMrAk6zsQMvFbQhp+78DCApojWcVwb5wAABLAAA6DyAAAACwAAAAEAAAAAAAAAAAAAAABhXiAzAAAAAQAAAAd5YnhNaW50AAAAAAYAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAC65hqWh5QlgBd8q4sdWzSNwcXY4Uf6Sqx/omMkGDt5nQAAAAAAAAAGAAAAAnkwMEJUQwAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/H//////////AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAARd+7+sh/Rx9MDKwJOs7EDLxW0Iafu/AwgKaI1nFcG+cAAAACeTAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAACRbFMAAAAAAAAADgAAAAJ5MDBCVEMAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAJFsUwAAAAIAAAAAAAAAAEXfu/rIf0cfTAysCTrOxAy8VtCGn7vwMICmiNZxXBvnAAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAACKHGgLZFzdHO/nY6UP3eo6i3kFvM1xQgwiut5n36Y4ngAAAAJ1MDBCVEMAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAAeke6AAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAATAAAAAnUwMEJUQwAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAACKHGgLZFzdHO/nY6UP3eo6i3kFvM1xQgwiut5n36Y4ngAAAAAAAAABAAAAAAAAAAIclyczAAAAQIBCHth9V+U1YgYKGZwAxzVvPpXBWEvbSEaGuvvUK0ac/c5a+j8arDMsZh02dZ0K/M2lHS/sy5E5YAfkwW7NuQmiAmHfAAAAQAoda7O+YU9NHL5X3dVLhT2FWxwNcHLXqqi6f5pb02FL9rgylZPK+pR1x5c8DqE2KklSmv0cXOeW/XYSBVY0tgE=

**Comment by drew-boy** [comment]
Duplicate clearing
