### ISSUE TITLE
Repayment with collateral

### ISSUE THREAD

**Issue by LorDDark6660** [script3/yieldblox-beta#110]
Remaining borrow negative? 

![1](https://user-images.githubusercontent.com/92062140/136340706-557b97d3-f767-4a3a-bca2-fafc8e1d5186.png)

**Comment by LorDDark6660** [comment]
Something went wrong!
Unable to complete your request.

Majority of turrets failed to execute contract. No collateral balances for y00EURT:GDGHQTCJ3SGFBWBHJGVRUFBRLZGS5VS52HEDH4GVPX5GZRJQAOW7ZM37

**Comment by mootz12** [comment]
This has since been resolved. Thanks for the bug :)

**Comment by LorDDark6660** [comment]
E-mail : petr86novotny@gmail.com, discord: LorDDarK#6660
