### ISSUE TITLE
Repay Problem

### ISSUE THREAD

**Issue by ygusmada** [script3/yieldblox-beta#113]
Here are my Wallet balance, and I was lend and borrow all assets that I have. As you can see, there is 4 USDC on my balance that I want to repay my loans.
![image](https://user-images.githubusercontent.com/28614308/136362174-fd783bf0-1342-437b-b9bd-dadf0168cee0.png)

I try to repay my borrows based on my balance (example: 2 USDC)
![image](https://user-images.githubusercontent.com/28614308/136362149-582c9ec4-04fd-4aa5-9d32-60321f0da7fc.png)

But getting this error.
![image](https://user-images.githubusercontent.com/28614308/136362109-98b3d4ea-eaa7-45f2-8ecc-173ae2de4781.png)

**Comment by mootz12** [comment]
The service unavailable was an unrelated bug, as has been resolved.
