### ISSUE TITLE
Collateral Slider accuracy

### ISSUE THREAD

**Issue by richyflip** [script3/yieldblox-beta#115]
Using the slider to enter the exact amount of Collateral to submit is tricky. it will be great if we could just type in the exact amount of collateral we would like to submit in the highlighted area on the screenshot it will save a lot of time instead of accurately trying to pinpoint the desired amount using a slider. 

![Slider Input](https://user-images.githubusercontent.com/91880700/136381507-b2a6fdbe-8c80-4671-b59c-08b0808c9c17.png)

**Comment by mootz12** [comment]
The collateral slider has been replaced after numerous bugs. Thanks for the feedback!!
