### ISSUE TITLE
Double position bug 

### ISSUE THREAD

**Issue by miki14000** [script3/yieldblox-beta#116]
![kép_2021-10-07_152405](https://user-images.githubusercontent.com/31147606/136393034-86cedb11-8dbd-4237-98d9-0e6398db0d20.png)

Double EURT screen in "My positions" tab.

**Comment by mootz12** [comment]
Good catch! This has since been resolved, and is the first bug I have seen for this issue.

We were not properly consolidating loans.

**Comment by miki14000** [comment]
Hi, my YieldBlox Testnet Beta public address: GBBMJ7PHJRIHWTLZRPVT3QUOOSFFRPUJOLOTKMK6YPPBTYQHY7GICIG7
Thanks.

**Comment by markuspluna** [comment]
Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public
