### ISSUE TITLE
Error withdrawing USDC from lending

### ISSUE THREAD

**Issue by haroldmd** [script3/yieldblox-beta#12]
Was trying to withdraw USDC from my lent amount and got this error. Rabet.

Wallet: GCGVILQGOC7XHPLA2Z2MSSCFUCOH4IZ5PY7WPO3KL76XNGOGSYT4EN7R

XRD: AAAAAgAAAACNVC4GcL9zvWDWdMlIRaCcfiM9fj9nu2pf/XaZxpYnwgAAAlgAA6E+AAAADgAAAAEAAAAAAAAAAAAAAABhXiFUAAAAAQAAAA55YnhCdXJueTAwVVNEQwAAAAAAAwAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAnkwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAADoMgXofAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAjVQuBnC/c71g1nTJSEWgnH4jPX4/Z7tqX/12mcaWJ8IAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAHRqUogAAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwVVNEQwAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAAPTqmUAAAAAAAAAAhyXJzMAAABAQT6RlV1NMxlUVNRctZPyxCs/95asViQ3GyLfCJwoO+mW1dCxcmyi6/msUwOFK5GWG4qN4LDA+kKvQEa39gdVB6ICYd8AAABAB5m5GQ1NpESyTIww0LgMSDln1EgFCApxE6n+3xQxJtOTr2dt+n7tIVeSFAhrQZeAaQfrGqkXMmrAIvmQAAidDQ==

![withdraw_usdc_from_lending1](https://user-images.githubusercontent.com/12978509/136290900-5433b78d-660a-4d2c-9860-dd1cbb8f28c1.jpg)

![withdraw_usdc_from_lending2](https://user-images.githubusercontent.com/12978509/136290913-81fe71a0-a69d-438b-ba0a-1fcdb96b67c6.jpg)

**Comment by mootz12** [comment]
This is a bug with Rabet reading our XDRs, and was the cause for us to disable access.

We will be reaching out to the team, but it doesn't appear related to YBX web app or our protocol
