### ISSUE TITLE
Claim Ybx 365,85 incoming 15,84

### ISSUE THREAD

**Issue by husnulh4kim** [script3/yieldblox-beta#122]
![Screenshot_47](https://user-images.githubusercontent.com/58093903/136415104-1e64a73e-4352-4be5-a222-c0e9243cf4b0.png)
![Screenshot_49](https://user-images.githubusercontent.com/58093903/136415120-3b00bca0-bd37-4184-b6fc-ebe971744947.png)
the number of claims does not match the one received

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/120
