### ISSUE TITLE
Able to send a transaction of 0 YBX to stake

### ISSUE THREAD

**Issue by Camels95** [script3/yieldblox-beta#126]
I am able to submit a transaction to stake 0 YBX. 

I click to max stake (I have 0 YBX) / enter 0 in amount and submit the transaction. 

https://stellar.expert/explorer/testnet/tx/8bf6a725cac7db94fb301f46a5fc0d5fb347f84d69444bbbc7973d83ee63b401

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/26
