### ISSUE TITLE
I found an issues from YBX Available to claim

### ISSUE THREAD

**Issue by davidsa05** [script3/yieldblox-beta#128]
I haven't made a claim yet with my balance in YBX Available to claim, but after I refresh page it showing that balance in menu Available To Claim reduced from 611.52 to 204.26. And on My Staked YBX balance showing 216.53

this is my screen capture
Before :
![landing YBX day 1](https://user-images.githubusercontent.com/91865890/136424773-eba74ef5-5e50-4a9b-a0fe-a41ead91f13b.JPG)

After refresh page :
![landing YBX day 1 3](https://user-images.githubusercontent.com/91865890/136424829-6505af60-626b-40f1-8018-0202670d9fa7.JPG)

**Comment by mootz12** [comment]
Some actions can automatically claim YBX for you.

IE -> if you update a position, we will claim the YBX outstanding for that position if it hasn't been updated in a few days.
