### ISSUE TITLE
Error notification is overlay from the box-sizing

### ISSUE THREAD

**Issue by starlog20** [script3/yieldblox-beta#132]
I tried to Borrow $50,000 EURT, and got this error. After i checked the discord channel, it happen in same time with refresh the cloud. But in my report is not about the reason the error. My report is, the error notification is overlayering from their box-sizing. This is weird to read and the alphabet that out from the box-sizing look blend with the background, so if your consummer is color blind person, i guess they will hard to read the error sentance. here the error:

![image](https://user-images.githubusercontent.com/92114001/136432573-e8b1bb48-b40f-4e39-820d-88498254cc4c.png)

solution is, 
1. expand the error box-sizing
2. allow the word to fit the box-sizing. so the hash error can be slice to below for one row. because i believe, this error happen is because the font/paragraph format dont allow to slice a word

**Comment by mootz12** [comment]
This is a readability issue. Good catch!

**Comment by starlog20** [comment]
Discord : starlog#9090
YieldBlox Testnet Beta Public Address: GA4CSV2JXVW2JIHG6EUFV4ITJWJT5XTYMDCUJEJXC7GP67IWW3P7ZREA

**Comment by markuspluna** [comment]
Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public
