### ISSUE TITLE
Current Borrow 

### ISSUE THREAD

**Issue by LorDDark6660** [script3/yieldblox-beta#135]
USDC showing 0.00 Current Borrow and i can´t borrow anything (BTC,ETH,EURT)

![4](https://user-images.githubusercontent.com/92062140/136437274-35f5989f-d2e4-4884-94b6-23835f3a1db0.png)

And when i try borrow 1000 USDC I got error
![5](https://user-images.githubusercontent.com/92062140/136437869-43cb1c8a-dea1-4c9b-8d7c-655a0ad3d334.png)
![6](https://user-images.githubusercontent.com/92062140/136437878-23ca7bd8-7c80-48d4-a27a-4b8b51a1ea4a.png)

**Comment by LorDDark6660** [comment]
now i can borrow USDc, but current borrow USDc show still zero

![10](https://user-images.githubusercontent.com/92062140/136615614-8c759779-1740-4d31-b24e-3ffdf48d2b1b.png)

If i click repay and MAX

![11](https://user-images.githubusercontent.com/92062140/136615617-ad35a053-7521-47ee-a26c-6f22c9267f17.png)

proof of borrow

![12](https://user-images.githubusercontent.com/92062140/136615626-e8f81b12-5753-459b-b5ef-fb584b485a60.png)

**Comment by mootz12** [comment]
This is an unrelated issue due to UX with not refreshing the webpage, and getting caught on old contract versions. We have it in the backlog to fix.
