### ISSUE TITLE
'<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

### ISSUE THREAD

**Issue by maksiuu** [script3/yieldblox-beta#138]
Unexpected error shows up when trying to submit transaction.
I have already lent 60 ETH and borrowed 35 EHT.
Then I borrowed another 20 ETH and tried to lend it. UI allowed me to set max amount for lent to 30 ETH, but when submitting transaction I received following error:
![image](https://user-images.githubusercontent.com/12476721/136439602-80cc8434-b007-4b84-9ed1-b4704061002c.png)

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/18
