### ISSUE TITLE
Negative borrow balance after repayment

### ISSUE THREAD

**Issue by maksiuu** [script3/yieldblox-beta#139]
I have repayed USDC borrow and minor amount of $ left to repay (balance said that it's less than 0.01 USD, but 0.00 in USDC). Then I submited another for remaining amount. My borrow position has not disapeared, but instead showed remaining borrow balance.
![Bez tytułu - Paint-007539](https://user-images.githubusercontent.com/12476721/136440780-d6b36df1-c6fb-4de0-8a26-cdbbfd45de81.png)

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/98
