### ISSUE TITLE
Unable to complete Deposit

### ISSUE THREAD

**Issue by zigone2021** [script3/yieldblox-beta#14]
I tried to make  a deposit, with BTC. My balance is gone and not complete the deposit.
Seems need some quick check ...
![screenshot_619](https://user-images.githubusercontent.com/92061986/136290874-d6a05f84-9876-45bd-9155-144ea771eecb.png)
![screenshot_618](https://user-images.githubusercontent.com/92061986/136290880-0f0c4bc6-e678-4486-b806-d8d27807313e.png)
XDR code "AAAAAgAAAADI9HKMn4bOIz+PSAqL0hQOfW3DTHsL8lVMOfCKZIVS3gAACWAAA6YpAAAABgAAAAEAAAAAAAAAAAAAAABhXh8dAAAAAQAAAAd5YnhNaW50AAAAAAYAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAADbLsXv+PdFL4ydwE8dHPpmupfannRwFs8FaNFh5BlxWgAAAAAAAAAGAAAAAnkwMEJUQwAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/H//////////AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAyPRyjJ+GziM/j0gKi9IUDn1tw0x7C/JVTDnwimSFUt4AAAACeTAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAACRbFMAAAAAAAAADgAAAAJ5MDBCVEMAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAJFsUwAAAAIAAAAAAAAAAMj0coyfhs4jP49ICovSFA59bcNMewvyVUw58IpkhVLeAAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAACKHGgLZFzdHO/nY6UP3eo6i3kFvM1xQgwiut5n36Y4ngAAAAJ1MDBCVEMAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAAZZ/3wAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAATAAAAAnUwMEJUQwAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAACKHGgLZFzdHO/nY6UP3eo6i3kFvM1xQgwiut5n36Y4ngAAAAAAAAABAAAAAAAAAAIclyczAAAAQAtfWqC9zwjjfKLkJBl+BYA6k7VGa6m++puQMOEdeYiX0JskvMO8J4QcKzVVfEF2djJYvhOLo+MXdF5gqEsNTg6iAmHfAAAAQBHBuxyZcPx47WsQSe9Rzxwt9AMwxnvrNCB7pbSXUkVapPJrGM/qCvie/jZpqOH0/HRZWy1zejSptRs4twhlFg0="

**Comment by mootz12** [comment]
see https://github.com/script3/yieldblox-beta/issues/12
