### ISSUE TITLE
UI: Aggregator Statistics Update Differently on Different Browsers

### ISSUE THREAD

**Issue by mergemode** [script3/yieldblox-beta#141]
The Flow browser was showing stats update glitches.

![IMG_20211007_181134](https://user-images.githubusercontent.com/61977238/136443166-355a8810-190a-4027-b6f6-203aeab2902a.jpg)

Update anomaly was substantially reduced in Yandex, although still present

![IMG_20211007_193809](https://user-images.githubusercontent.com/61977238/136443423-5d28007f-6c5f-41f1-8a24-859000a603e9.jpg)

**Comment by mootz12** [comment]
We don't plan on having full support for Flow and Yandex, rather, we will fully support an app in the future.

Most users having been having an OK experience with them thus far. So, I am closing for the mean time. If there are pressing issues, please respond to this issue or open a new one.
