### ISSUE TITLE
[UI/UX] Additional info on Account Overview

### ISSUE THREAD

**Issue by starlog20** [script3/yieldblox-beta#142]
Maybe you can add more info for overall balance of my asset that i have in this channel. I mean, it is include asset that constumer dont deposit or lend or borrow to your plaform. So it can be 

1. Total Asset Value from the connected address (include deposited balance). 
2. Available asset to trade (which is mean it is not deposited to your platform).

you can slice YBX staked here for additional asset info here

![image](https://user-images.githubusercontent.com/92114001/136443777-17468b55-ff8e-47a2-97a1-9a6c8b6dd510.png)

or 

make a new row below asset info here
![image](https://user-images.githubusercontent.com/92114001/136443975-f8c72145-1611-4982-95ee-ed37631302c7.png)

**Comment by mootz12** [comment]
Thanks for the suggestion! We will keep it in mind as we move forward. To keep the issue tracker clean, we will be closing this for the mean time.
