### ISSUE TITLE
Staking YBX: The sYBX Quantity Increased Disproportionately

### ISSUE THREAD

**Issue by mergemode** [script3/yieldblox-beta#143]
Same thing with the APY
Before staking

![IMG_20211007_195851](https://user-images.githubusercontent.com/61977238/136446445-c2686061-7239-4cc2-829c-cb74c4d929bf.jpg)

After staking

![IMG_20211007_195955](https://user-images.githubusercontent.com/61977238/136446490-cc08a381-e0b5-4088-94f6-827b6a703653.jpg)

**Comment by reigister** [comment]
i think sYBX it refers to how long you stake your YBX. so it will be different with amount YBX you stake.

**Comment by starlog20** [comment]
bro. 

120 * 1.5 = 180. 
100% * 1.5 = 150%

so, nothing weird i guess ?

**Comment by mergemode** [comment]
A year multiplier = 1.5

**Comment by mergemode** [comment]
holardzy@gmail.com
