### ISSUE TITLE
Unable to Login from Desktop or Mobile

### ISSUE THREAD

**Issue by Nathanofzion** [script3/yieldblox-beta#144]
I've created a Albedo account with the provided testnet login. However I'm unable to login with any of the key store providers

-Albedo on click returns (This Wallet is currently not supported)
-Freighter on click returns (Unable to connect to wallet - (note wallet is installed on chrome))
-Rabet   on click returns (This Wallet is currently not supported)

As you can see Freighter is just unable to connect to wallet; so ensuring wallet account is set to testnet and is funded with testnet xlm. The issue is still the same I've tried with an iphone 8 same thing.
<br /> 
![Albedo](https://user-images.githubusercontent.com/38050940/136453224-1a368075-70e8-4fcd-aa56-d1525da5e5a3.PNG)
<br /> 
![freighter](https://user-images.githubusercontent.com/38050940/136453231-5035bc6a-25b8-4e06-8f72-01a519293dfc.PNG)
<br /> 
![Rabet](https://user-images.githubusercontent.com/38050940/136453233-420f7ca5-9b68-445f-ac8e-7bb300cb2c44.PNG)

**Comment by arnob016** [comment]
> I've created a Albedo account with the provided testnet login. However I'm unable to login with any of the key store providers
> 
> -Albedo on click returns (This Wallet is currently not supported) -Freighter on click returns (Unable to connect to wallet - (note wallet is installed on chrome)) -Rabet on click returns (This Wallet is currently not supported)
> 
> As you can see Freighter is just unable to connect to wallet; so ensuring wallet account is set to testnet and is funded with testnet xlm. The issue is still the same I've tried with an iphone 8 same thing. ![Albedo](https://user-images.githubusercontent.com/38050940/136453224-1a368075-70e8-4fcd-aa56-d1525da5e5a3.PNG) ![freighter](https://user-images.githubusercontent.com/38050940/136453231-5035bc6a-25b8-4e06-8f72-01a519293dfc.PNG) ![Rabet](https://user-images.githubusercontent.com/38050940/136453233-420f7ca5-9b68-445f-ac8e-7bb300cb2c44.PNG)

Solution: (what worked for me)
- First login to your wallet (from extension menu)
- Put it on testnet mode
- Close & reopen the browser.
- Check if you wallet (from extension) is okay or not. Login if needed.
- Try logging into the website now
(Note : this was required for me too but only the first time on each browser. Restarting the PC didn't effect it. After clearing cache & data of the browser will need to follow these steps again.  )

**Comment by Nathanofzion** [comment]
> Freighter is the only one that works right now -- do you allow popups on your chrome browser?

Yes reset session, tried again this time a different error message. See attached
![Freighter-issue-2](https://user-images.githubusercontent.com/38050940/136594508-dbc7a8a2-78f0-4dca-b4bc-3f8ab918f613.PNG)

**Comment by mootz12** [comment]
You need to make sure the Freighter wallet is currently using your given beta wallet key, and is on the testnet.

**Comment by Nathanofzion** [comment]
Yes did that, managed to login, the account in Freighter was the wrong one. Thank you
