### ISSUE TITLE
Unable to borrow

### ISSUE THREAD

**Issue by Mcsunky** [script3/yieldblox-beta#145]
Despite having a health factor of 2.05 and a maximum amount of 8.82ETH and 34.7k USDC available to be borrowed I got an error message saying "Something went wrong! Failed to generate your token!" whenever i tried to initiate transaction (borrow). I used Freight wallet for these transactions. 

TRIED TO BORROW 2ETH HERE

![Screenshot_20211007-211033_Video Player](https://user-images.githubusercontent.com/35813996/136456830-90e301ec-9d7b-474a-a0d7-5105de693f14.jpg)

![Screenshot_20211007-211052_Video Player](https://user-images.githubusercontent.com/35813996/136456828-d6438415-3817-43ac-a0b5-945207d56784.jpg)

TRIED TO BORROW 10k USDC HERE

![Screenshot_20211007-213019_Video Player](https://user-images.githubusercontent.com/35813996/136460230-0668c4d2-f396-4ea6-852e-2ca6ccdfb148.jpg)
![Screenshot_20211007-213028_Video Player](https://user-images.githubusercontent.com/35813996/136460248-4ec28d60-afa8-415a-8822-becd65358a6f.jpg)
![Screenshot_20211007-213033_Video Player](https://user-images.githubusercontent.com/35813996/136460272-9b1e4d7d-47b5-497a-8376-01d6c8c7e58a.jpg)

**Comment by Mcsunky** [comment]
> Cloudflare issue -- working on it

Great...

**Comment by mootz12** [comment]
The service unavailable was a timeout problem on one of the turrets. it has since been resolved.
