### ISSUE TITLE
Repaying USDC leaves 0.001918 USDC behind.

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#150]
![image](https://user-images.githubusercontent.com/74468064/136468854-9aac9f53-f010-4844-ab5b-10dcc46388ff.png)

This also happened when I was repaying my borrowed ETH. It's kind of annoying.

**Comment by mootz12** [comment]
Duplicate of https://github.com/script3/yieldblox-beta/issues/32
