### ISSUE TITLE
Minor/Suggestion: Confirm withdrawal wording could be better

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#152]
When confirming a withdrawal, the wording could be clearer:

![image](https://user-images.githubusercontent.com/11483548/136473475-43df41a1-db05-45c1-ba84-641eb64c075d.png)

The current screen still references 'Deposit Amount', this could be changed to Withdrawal amount in line with the previous screen:

![image](https://user-images.githubusercontent.com/11483548/136473720-0b8af630-a0eb-4f99-88c9-b356de18c5f7.png)

**Comment by mootz12** [comment]
Good catch! Thanks.
