### ISSUE TITLE
Documentation: Links on Lending page are incorrect

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#154]
1. The link for collateral on the [Lending](https://docs.ybx.script3.io/user-docs/lending-borrowing/lending) page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#what-is-collateral which takes you back to the Lending & Borrowing page

![image](https://user-images.githubusercontent.com/11483548/136475000-f9ad754e-7042-4846-957d-ad9fde47dd3a.png)

Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/borrowing#what-is-collateral

2. The link for health factor on the Lending page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#whats-a-health-factor which takes you back to the Lending & Borrowing page

Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/health-factors

3. The link for borrow on the Lending page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#how-does-borrowing-work-on-yieldblox which takes you back to the Lending & Borrowing page

Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/borrowing#how-does-borrowing-work-on-yieldblox

4. The link for liquidation on the Lending page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#what-is-liquidation which takes you back to the Lending & Borrowing page

Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/liquidations

5. proportion of the pools lending balance is linked to  https://docs.ybx.script3.io/technical-docs/math#pool-token-issuance
which takes you to Average Interest Rate on the correct page

6.  withdraw their lent assets is linked to https://docs.ybx.script3.io/technical-docs/math#asset-payout which takes you to Originating Interest Rate on the correct page

**Comment by drew-boy** [comment]
fixed - thanks!
