### ISSUE TITLE
Documentation: Borrow link on the Lending page is incorrect 

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#155]
The link for borrow on the [Lending ](https://docs.ybx.script3.io/user-docs/lending-borrowing/lending)page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#how-does-borrowing-work-on-yieldblox which takes you back to the Lending & Borrowing page

![image](https://user-images.githubusercontent.com/11483548/136475440-31a89287-95cb-4905-b365-bdc9f71fdf88.png)

Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/borrowing#how-does-borrowing-work-on-yieldblo

**Comment by drew-boy** [comment]
#154
