### ISSUE TITLE
Documentation: health factor link on the Lending page is incorrect

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#156]
The link for health factor on the [Lending ](https://docs.ybx.script3.io/user-docs/lending-borrowing/lending)page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#whats-a-health-factor which takes you back to the Lending & Borrowing page

Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/health-factors

**Comment by drew-boy** [comment]
#154
