### ISSUE TITLE
Documentation: liquation on the Lending page is incorrect

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#157]
The link for liquidation on the [Lending ](https://docs.ybx.script3.io/user-docs/lending-borrowing/lending)page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#what-is-liquidation which takes you back to the Lending & Borrowing page

Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/liquidations

**Comment by arnob016** [comment]
> The link for liquidation on the [Lending ](https://docs.ybx.script3.io/user-docs/lending-borrowing/lending)page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#what-is-liquidation which takes you back to the Lending & Borrowing page
> 
> Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/liquidations

Can you please put all these wrong link issues in a single  post?

**Comment by defj** [comment]
> 
> 
> > The link for liquidation on the [Lending ](https://docs.ybx.script3.io/user-docs/lending-borrowing/lending)page points to https://docs.ybx.script3.io/user-docs/lending-borrowing#what-is-liquidation which takes you back to the Lending & Borrowing page
> > Suspect the correct link is actually: https://docs.ybx.script3.io/user-docs/lending-borrowing/liquidations
> 
> Can you please put all these wrong link issues in a single post?

Reported all against the original https://github.com/script3/yieldblox-beta/issues/154

**Comment by drew-boy** [comment]
#154
