### ISSUE TITLE
Transaction Confirmation Problem

### ISSUE THREAD

**Issue by ygusmada** [script3/yieldblox-beta#158]
Sometimes i need to refresh and waiting seferal times to submit transaction because always getting error when lend, borrow or claim YBX.

I got the clue when the error will be going.
if the freighter show 1x to confirmed (except login confirmation), the transaction will be error.
If the freighter shows 2x to confirmed (except login confirmation), the transaction will be working.
If the freighter shows 3x to confirmed (except login confirmation), the transaction will be working

**Comment by ygusmada** [comment]
Will be good if the confirmation just once.

**Comment by ygusmada** [comment]
1 time confirmation error does not affect when staking YBX

**Comment by arnob016** [comment]
Correct me if I'm wrong, 1 time confirmation is for Staking YBX & Updating Coleteral % only. All other transactions are 2 step or 3 step.

**Comment by ygusmada** [comment]
yes, right dude.

**Comment by mootz12** [comment]
I am unsure if I follow. Are you able to reproduce this? Could you provide some screenshots?

**Comment by ygusmada** [comment]
i didn't found errors now.. All works fine

**Comment by arnob016** [comment]
> I am unsure if I follow. Are you able to reproduce this? Could you provide some screenshots?

this wasn't actually a bug. He mentioned what times he'd get XDR error for various confirmation times. Mainly he talked about errors he got from staking YBX
