### ISSUE TITLE
Explanation stake incomplete

### ISSUE THREAD

**Issue by husnulh4kim** [script3/yieldblox-beta#159]
![Screenshot_62](https://user-images.githubusercontent.com/58093903/136479532-096fb5e7-bc36-428a-a373-1034ebe26c66.png)
![Screenshot_63](https://user-images.githubusercontent.com/58093903/136479534-5ecfe7d7-27cf-4be1-8f2d-1b1538dccec7.png)
I staked on ybx, as many as 2 kinds, namely 300ybx for 1 year and 100ybx for half a year, but in the description of the stake there is no detailed explanation, there is only 1 explanation

**Comment by mootz12** [comment]
If you are referring to `next unlock`, that shows the next stake you are going to unlock. it does not show the following unlock periods.

I understand how this can be confusing, so thanks for your feedback. We have some redesign plans in mind for staking, so I will be closing this for the time being.

**Comment by husnulh4kim** [comment]
Discord: Husnulh4kim#2588
YieldBlox Testnet PUBLIC key: GBIQY6MSJNLCMBBK2PM57ZZJ5MDOREWKO46WCEM7LKYIOD4ZMFLIYVDN
