### ISSUE TITLE
Majority of turrets failed to execute contract. AuthTokenTx 

### ISSUE THREAD

**Issue by B25T** [script3/yieldblox-beta#16]
![image](https://user-images.githubusercontent.com/30299817/136292117-dfa46a0f-90d8-4ac4-91bc-efe2c99b9273.png)
I've tried to deposit and I can't see the Current Deposit I've made and how can I borrow and there's always a notice like this Something went wrong!
Unable to complete your request.

Majority of turrets failed to execute contract. AuthTokenTx has a non-zero sequence number: Failed during auth

**Comment by mootz12** [comment]
This is a consistent failure with Albedo, and requires an update on Albedo's end to support our use of XDRs as auth tokens.

We will be reaching out to the team to get this resolved, but it does not appear to be an issue with YBX.
