### ISSUE TITLE
Bug manage colateral

### ISSUE THREAD

**Issue by marisadmr** [script3/yieldblox-beta#163]
1. 
![image](https://user-images.githubusercontent.com/92132964/136487554-d544882a-11ba-4717-a090-80244b880c00.png)
2. 
![image](https://user-images.githubusercontent.com/92132964/136487887-1c6ce57e-2243-47cc-b83c-b6424d692681.png)
3.
![image](https://user-images.githubusercontent.com/92132964/136488001-be958ede-f77e-4a39-aa13-664450594167.png)

im doing to manage colateral, when the submit button is clicked and then confirmed, nothing happens and the collateral does not change

**Comment by mootz12** [comment]
This modal has been redesigned since then. please let me know if this is still an issue
