### ISSUE TITLE
Repayment USDC with collateral EURT but i think something wrong.

### ISSUE THREAD

**Issue by reigister** [script3/yieldblox-beta#167]
I am attach some SS

No. 1 its before i do repayment
No. 2 when i try to repayment USDC with collateral EURT max but failed 
No. 3 trx failed
No. 4 try again to repayment USDC with collateral EURT  600.000 USDC it show remaining 132,55K USDC and health factor will go to 2,37
No. 5 after trx my health factor it not show like picture No. 4
No. 6 my remaining borrow for USDC not same with picture no .4 it must 132,55. am i get discounted? :p 

![repay with collateral](https://user-images.githubusercontent.com/78670969/136494559-7774e586-3c3f-49d3-9e01-8976e1e793f8.png)
![repay with collateral2](https://user-images.githubusercontent.com/78670969/136494566-e59c9e55-6385-45a4-ad2b-3b9b7d6b5b5d.png)
![repay with collateral3](https://user-images.githubusercontent.com/78670969/136494568-4c6f61ef-0817-4bbc-8bfe-77dd16685aca.png)
![repay with collateral4](https://user-images.githubusercontent.com/78670969/136494569-69cb368f-aaa9-4841-8b3e-1bc155a2482b.png)
![repay with collateral5](https://user-images.githubusercontent.com/78670969/136494570-0d7c792c-a8f5-45e8-81e0-37e60cc72de5.png)
![repay with collateral6](https://user-images.githubusercontent.com/78670969/136495332-9708d957-db15-401d-9077-61690a157cb1.png)

**Comment by mootz12** [comment]
There was a large update pushed our regarding repayments. Please let me know if you are still having issues.

**Comment by reigister** [comment]
Discord username : register#1319
