### ISSUE TITLE
The amount of assets not updated, need refresh page to do it

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#169]
I expected theres some assets refresh button in the page, so doesnt need to refresh whole page to update the assets amount.
Its for makes server smoother when theres many participant live.
![image](https://user-images.githubusercontent.com/91896561/136498969-76515c52-8089-4964-a1bd-fe28aad897ce.png)

**Comment by f0xie7** [comment]
Its more annoying when we try to withdraw the collateral after update the collateral, the y00 already appeared on wallet but amounts that available to be withdrawed still 0.

**Comment by mootz12** [comment]
This is marked as a post beta enhancement internally.

**Comment by f0xie7** [comment]
f0xie#8785
