### ISSUE TITLE
Failed to Generate Token Issue

### ISSUE THREAD

**Issue by Billamana55** [script3/yieldblox-beta#17]
I tried to make a small deposit, since I read much people reporting balance gone when made a deposit. Yes , the balance is gone but the deposit is not arrive to my account but shows me different error. 
![aa](https://user-images.githubusercontent.com/79621658/136292365-99d36dc7-4699-4009-afd2-fa15d196948e.png)

any idea?

**Comment by mootz12** [comment]
https://github.com/script3/yieldblox-beta/issues/6
