### ISSUE TITLE
Freighter connect issue

### ISSUE THREAD

**Issue by coolrobiul** [script3/yieldblox-beta#170]
If u still can't connect freighter extension through mobile browser
I have a solution
Supported browser (Kiwi, Yandex, Flow) I have test all of these

Giving example for kiwi browser
You need to do a setting

Follow this steps
3 dot - setting - accessibility - desktop mode by default (mark it on) 

![Screenshot_2021-10-08-11-55-58-91_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/59414838/136506174-8a45c6cf-69b4-490a-a177-f9798c7a426f.jpg)

Now there will be no problem using or connecting freighter extension through a mobile browser.
Thank you.

![Screenshot_2021-10-08-11-54-48-27_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/59414838/136505567-06cd654f-82ec-48d9-af3b-bb920534fa6d.jpg)

![Screenshot_2021-10-08-11-55-07-65_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/59414838/136505579-d3284abc-8534-4adb-83fb-3b2fc0bdda1e.jpg)

![Screenshot_2021-10-08-11-55-28-01_b5a5c5cb02ca09c784c5d88160e2ec24](https://user-images.githubusercontent.com/59414838/136505596-2b2384a9-f610-460e-b3de-8cec7df1c637.jpg)

**Comment by arnob016** [comment]
This is already posted on discord announcements 😶 Also use a suggestion tag

**Comment by coolrobiul** [comment]
Yes, but without this setting, above browser dont work for freighter extension

**Comment by starlog20** [comment]
Exactly, YBX doesnt support for mobile phone yet. so if you want to testing in mobile phone, the you will work harder to get trick so u can testing ybx platfrom via mobile phone.  so imo this is not an issue bcuz exactly ybx doesnt support for mobile phone user yet

**Comment by coolrobiul** [comment]
U can use freighter extension through mobile browser with this tricks

**Comment by Mahin8080** [comment]
This tricks really works
Thanks a lot.

**Comment by mootz12** [comment]
Thanks for the documentation! Marking it as such, and closing.
