### ISSUE TITLE
Health Factor looks really strange, it goes beyond

### ISSUE THREAD

**Issue by backschool99** [script3/yieldblox-beta#172]
![Health-Factor-Bug_Ybx](https://user-images.githubusercontent.com/88925777/136507134-45ae32de-89b1-41a0-808a-e4995b9c0b29.png)

![Health-Factor-Bug_Ybx-1B](https://user-images.githubusercontent.com/88925777/136507152-3eaccc13-8bca-422b-94ab-ece4632c8339.png)

https://user-images.githubusercontent.com/88925777/136507035-5d6fe54c-057a-44e2-928b-70a577bdcec6.mp4

**Comment by drew-boy** [comment]
The "b" means billion
