### ISSUE TITLE
Unable to claim YBX

### ISSUE THREAD

**Issue by Camels95** [script3/yieldblox-beta#174]
Unable to claim YBX 

"Failed to generate your token! Please try again by performing another action.

Majority of turrets failed to execute contract. Not authorized to run contract with hash 122136876b9ec434cbc0ad3f0d4b162ba5b255674d7d5fd5c2e4837823ed0356"

![Capture](https://user-images.githubusercontent.com/91905825/136511072-7ed359e0-1871-4e98-99b3-0f2d3ac2b740.PNG)

**Comment by mootz12** [comment]
We have been swapping hashes quite frequently, so this is an expected intermittent failure.
