### ISSUE TITLE
Can unstake early while my YBX is locked

### ISSUE THREAD

**Issue by dth324** [script3/yieldblox-beta#176]
I tried to unstake my sYBX which was locked for 1 year.

![1](https://user-images.githubusercontent.com/92073561/136514045-88aade94-4e3c-4799-8dfe-6e17fa1deb25.PNG)

I can fill in any amount, which is bigger than my locked sYBX, to unstake all my sYBX ( in my case, it is bigger than 232.67 sYBX)
I tried 500

![2](https://user-images.githubusercontent.com/92073561/136514093-a11ffc9c-69e2-4a61-b7dd-badce997a229.PNG)

It worked

![3](https://user-images.githubusercontent.com/92073561/136514120-7ead8925-8be1-47df-838f-63bfe9dbde85.PNG)

![4](https://user-images.githubusercontent.com/92073561/136514139-7a046f8c-314c-428e-b7e8-cf417ebfcb00.PNG)

My 'Staked YBX' now:

![5](https://user-images.githubusercontent.com/92073561/136513578-1af4d824-6660-4d03-9ca7-327b080bf5fe.PNG)

**Comment by drew-boy** [comment]
Yes, this is intended -- you don't earn any staking fees for unstaking early though. We are going to add a caution message to this workflow
