### ISSUE TITLE
Mistype Withdrawal to Withdrawl

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#177]
In https://ybx-beta.script3.io/#/profile
When withdraw-ing collateral, the title should be "Withdrawal" rather than "Withdrawl"
![image](https://user-images.githubusercontent.com/91896561/136515277-c0ae292c-55fc-4c2e-b0b7-8d3b995e0447.png)

**Comment by starlog20** [comment]
F gank. why are you so observant xD

**Comment by mootz12** [comment]
IKR. Thanks for catching all these typos. It feels like the disappear when you look at the UI long enough... lol

**Comment by f0xie7** [comment]
f0xie#8785
