### ISSUE TITLE
Max Repay Value

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#178]
I expect max repay value based on the funds on the wallets available, not only max repay based on the loan value.
Or probably add more button for that function(?)

![image](https://user-images.githubusercontent.com/91896561/136524535-874ebb64-ec6b-45b5-afe3-bd521e6d1c86.png)

**Comment by starlog20** [comment]
You can apply this suggestion if Account info containing about 
1. Total Balance in wallet (include non deposited, deposited, borrowed)
2. Total available balance that we can trade. (not deposited, and not borrowed in your platform)

continuing case from this suggestion : https://github.com/script3/yieldblox-beta/issues/142#issue-1020350161

**Comment by mootz12** [comment]
This was a mistake on our part, and has since been updated. Good catch!

**Comment by f0xie7** [comment]
f0xie#8785

**Comment by markuspluna** [comment]
Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public
