### ISSUE TITLE
Error while repaying borrowed amount. (ETH)

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#181]
XDR: AAAAAgAAAADkzI7f6TOEPoHBB/g4v7Lt3Q40ItpYleDP7gDFNlS/ugABhqAAA6dBAAAAWQAAAAEAAAAAAAAAAAAAAABhYBAtAAAAAQAAAAh5YnhSZXBheQAAAAUAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAADWpHF0tKQHcwx37HTfagdyLb7uApAO5unJbs+01l3u6gAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAAAAAACgAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAABMS0KQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAI5/uSuZx8KTY7FVjRUGglnnXgt3eVoXYIOombTaqwfKAAAAAnUwMEVUSAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAASm0dAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAjn+5K5nHwpNjsVWNFQaCWedeC3d5Whdgg6iZtNqrB8oAAAACdTAwRVRIAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAJQ414AAAAAAAAAAzM/EbYAAABADF3ru/5NYi09VxczUJtJEzyhdx0lYP19nbdZ+J8tkGSuJiMYeEMSWhjdUGevrhHa1qPlOePeky675RAjRR71CDXtBcUAAABAHVlA14j+BgiXtzkWSi7ElTx47MesFulTauiM0q2KzC0uVszK1e6i+xxzXmefeqPwZzeelJXoz5cDaiclJerFBTZUv7oAAABAWg9SS1OlMEyzfNk5N4le1QvgEPyyRT77lMxDEfOPiWWRNhRanMoeVNzuXxeHbWFihNzNSUOxXdHiHveg4CamDw==

Screenshots:

![image](https://user-images.githubusercontent.com/74468064/136532883-268d16e6-1e1f-4bc7-a6e8-6baef80791c4.png)
![image](https://user-images.githubusercontent.com/74468064/136532904-2e3afc11-b6a7-4652-9054-ce5b044d737b.png)
![image](https://user-images.githubusercontent.com/74468064/136532951-c3e205fc-7679-452c-b847-7d8786b89203.png)

**Comment by mootz12** [comment]
Our repayment modal went through a bunch of changes recently. Please let me know if this is still an issue.
