### ISSUE TITLE
error where i try execute transaction with freighter

### ISSUE THREAD

**Issue by kinjaz00** [script3/yieldblox-beta#182]
hii, try to execute some lend option at ybx beta found this :
![bugornotybx](https://user-images.githubusercontent.com/92155424/136537543-86c28a21-b175-4204-81e1-ddc062df1e91.JPG)

but after refreshing site, that's normal, i can execute lend&borrow.
i think, your's health factor option need some time more than executing order at freight wallet.
will you fixed it? so we dont worries about double sign at freighter,
thanks
kinjaz00

**Comment by drew-boy** [comment]
#180
