### ISSUE TITLE
YBX Icon gets squished

### ISSUE THREAD

**Issue by MLateralus** [script3/yieldblox-beta#185]
When you have a lot to claim in "Available to claim" the icon on the right get squeezed.
It could possibly expand the line into newline, 

![image](https://user-images.githubusercontent.com/9516558/136550711-590e6318-7406-4c8a-8263-3eefd7b51004.png)

Also the "YBX" gets under the button
![image](https://user-images.githubusercontent.com/9516558/136551066-e8e13975-0302-4dc1-a767-108e5e51268a.png)

**Comment by drew-boy** [comment]
no one will ever get that high of a ybx claim lol
