### ISSUE TITLE
I can't execute any contract 

### ISSUE THREAD

**Issue by gbosah** [script3/yieldblox-beta#187]
I want to claim my YBX and repay my borrowed assets, but is bring out "something is wrong". Below is the screenshot.
![Screenshot_2021-10-08-13-58-47-421_org flow browser](https://user-images.githubusercontent.com/28156856/136561826-8a297204-4b33-49db-9cd1-0d1d582e5010.jpg)

**Comment by mootz12** [comment]
We do a lot of contract swapping, this is an expected intermittent failure.
