### ISSUE TITLE
Different Actual Healty Factor During Repayment

### ISSUE THREAD

**Issue by starlog20** [script3/yieldblox-beta#188]
I try to repay borrowed USDC with Colleteral USDC , In Repay tab it say if i repay 100K then my healty factor will change from 1.30 to 1.45. I set 1% to avoid huge different amount fund when i use colleteral as repayer. here what i input
![image](https://user-images.githubusercontent.com/92114001/136559526-f2714a4c-3a44-455f-880c-2d2d00d3ae70.png)

But after transaction finished, the Healty Factor is only increase to 1.35.

![image](https://user-images.githubusercontent.com/92114001/136561445-4888e037-9fa8-4ab0-ada3-f6b125162d55.png)

i checked my lent position and my USDC deposit is gone. which it is correct. 

![image](https://user-images.githubusercontent.com/92114001/136561913-2009afc7-2728-47ef-a302-aab9abaea162.png)

Then i also check my borrow position and it reduce around 100k USDC which it is correct.
![image](https://user-images.githubusercontent.com/92114001/136562165-ced36736-332f-47d2-8fd6-ed43e2f327e7.png)

So, I'm not sure what exactly happen, but i believe this is bugs. But if this is not bug, i think better to give estimate instead fix healty factor to avoid fake promise to costumer.

**Comment by mootz12** [comment]
The health factor was being calculated incorrectly before. See https://github.com/script3/yieldblox-beta/issues/167

This has been resolved
