### ISSUE TITLE
[UI/UX] Additional/Change search, filter, sort on the platform

### ISSUE THREAD

**Issue by yuminaai** [script3/yieldblox-beta#189]
I think you can give more features like search, filter, sort on your platform. well currently your platform only has 4 assets, but in future, i believe there will have more asset to be added, so it will be paintifull if we cant filter many assets by doing search and sort the kind of assets. Please add this features in all place that have info about asset, that is on Lending Market, Borrow Market, and My Position in the profile.

![image](https://user-images.githubusercontent.com/92166874/136568955-3d69dfa5-409a-4d0a-b788-dadba285633d.png)

**Comment by mootz12** [comment]
This has already been suggested. We have marked it as a possible improvement for the mainnet release. Thanks for your feedback.
