### ISSUE TITLE
Can't do anything

### ISSUE THREAD

**Issue by husnulh4kim** [script3/yieldblox-beta#190]
![Screenshot_65](https://user-images.githubusercontent.com/58093903/136576107-9b4c894a-5eab-4abf-a620-e11093380bc2.png)
Has been more than 12 hours can not do any activity, always showing the same error

**Comment by husnulh4kim** [comment]
![Screenshot_70](https://user-images.githubusercontent.com/58093903/136643411-0c8e0869-1a97-487e-8da5-dc8eb42e947c.png)
It's been 24 hours I still can't do any activity. Still showing the same problem.
@drew-boy @mootz12 @markuspluna  Is there any quick action? So that I can maximize getting YBX
Account address:
GBIQY6MSJNLCMBBK2PM57ZZJ5MDOREWKO46WCEM7LKYIOD4ZMFLIYVDN

**Comment by husnulh4kim** [comment]
@drew-boy Is there any quick action? So that I can maximize getting YBX

**Comment by husnulh4kim** [comment]
![Screenshot_76](https://user-images.githubusercontent.com/58093903/136729184-94093b30-622f-4fb1-94c2-62d92bfd5c28.png)
This is day 3, i still can't do any activity on testnet, I think this is a big problem if it happens to the mainnet, because I can't control the assets I own. @mootz12 @drew-boy  @markuspluna

**Comment by mootz12** [comment]
This was an issue with your account setup, and has been manually resolved. Applying a bug bounty as an apology.

**Comment by husnulh4kim** [comment]
This is a big loss for me sir, because in those early days the number of YBX claims was bigger than it is now and I couldn't maximize it. I hope the prize lives up to my expectations.
Thanks sir

**Comment by husnulh4kim** [comment]
Discord: Husnulh4kim#2588
YieldBlox Testnet PUBLIC key: GBIQY6MSJNLCMBBK2PM57ZZJ5MDOREWKO46WCEM7LKYIOD4ZMFLIYVDN

Sir, For this matter please consider, This is a big loss for me, because in the early days the number of YBX claims was bigger and I couldn't maximize my land and borrow. I hope the prize lives up to my expectations.
Thank you sir
