### ISSUE TITLE
Minus Healty Factor

### ISSUE THREAD

**Issue by yuminaai** [script3/yieldblox-beta#191]
So, when we doing repay higher amount than borrowed ammount, is it possible to get minus healty factor? also why it's is green?

![image](https://user-images.githubusercontent.com/92166874/136576349-9ea19859-5422-4ed1-a869-9a816f1f852c.png)

**Comment by yuminaai** [comment]
another formula

6 BTC + 200 ETH

![image](https://user-images.githubusercontent.com/92166874/136577535-f155efb5-5d40-49a1-8d67-1deba56b4c79.png)

7 BTC + 200 ETH

![image](https://user-images.githubusercontent.com/92166874/136577588-3349af68-5876-427f-80de-9c66a05db542.png)

8 BTC + 200 ETH

![image](https://user-images.githubusercontent.com/92166874/136577621-c2d45734-fafe-46fa-884b-8dd4e1b66c72.png)

higher repayment will make the minus decrease, but why since 7 BTC + 200ETH it starting become minus/negative?

**Comment by mootz12** [comment]
Health factor was being incorrectly calculated in this case. See https://github.com/script3/yieldblox-beta/issues/167
