### ISSUE TITLE
Possible to connect with a non-beta account

### ISSUE THREAD

**Issue by fpbrault** [script3/yieldblox-beta#193]
It is possible to bypass the beta account restriction and connect with any testnet account.

Repro Steps:
1. Create another account on the testnet, fund it, and then add it to freighter (if not created from freighter).
2. (Optional) Add a trustline for the assets used in the beta.
3. (Optional) Send some of the assets from the Beta account to the newly created account.
4. Access the app and open the developer tools.
5. In the sources tab, access this file: _https://ybx-beta.script3.io/static/js/utils/beta.ts_
6. Add a breakpoint on the third line.
7. Connect with freighter. Make sure the new account is the active one.
8. When the breakpoint is reached, change the value of _walletAddress_ to any of the values in the BETA_WALLETS constant.

At this point, you should be able to perform any operation as with a beta account:
![image](https://user-images.githubusercontent.com/1728218/136620168-0e2288d8-08a4-4087-8b64-2d4c27facb40.png)

**Comment by drew-boy** [comment]
Account won't be tied to beta list so the new account won't get and YBX rewards for the beta, but interesting find -- neat!

**Comment by coolrobiul** [comment]
U can connect
But where u get testnet token issued by script3 ?
So u can't play the game 🎯

**Comment by mootz12** [comment]
It's 100% possible! But as others mentioned, users aren't incentivized to use other wallets.

**Comment by fpbrault** [comment]
Email linked to my beta account (for bug bounty): fpbrault@gmail.com
