### ISSUE TITLE
Max button doesn't work when unstake sYBX. I have to type in specific number.

### ISSUE THREAD

**Issue by butterpiefomo** [script3/yieldblox-beta#196]
<img width="454" alt="Screen Shot 2021-10-09 at 10 20 21" src="https://user-images.githubusercontent.com/91866182/136638929-3806b0c0-1fad-4019-aeef-1c33169f1fcc.png">

**Comment by drew-boy** [comment]
The max goes off of unlocked YBX, and your lockup period has not ended, so it should be 0.
