### ISSUE TITLE
borrow value minus

### ISSUE THREAD

**Issue by akugakgak** [script3/yieldblox-beta#198]
my testnet public key is GDO262LKKJTKTRA5IZ6ZLCLAS7W2BVN3VVYOC7E2MB4NNQ5EAUV4PZ
![err4](https://user-images.githubusercontent.com/75468816/136639224-9dd63a98-106f-4cd7-bf28-a1fd69ea7e8c.png)

and my YBX earning seem like lower than before

**Comment by mootz12** [comment]
What is the issue here? YBX issuance is expected to go down each day. As more and more users dump more money into the protocol, your share will start to decrease.

If I am missing something, please let me know.
