### ISSUE TITLE
Show unstake parts

### ISSUE THREAD

**Issue by jakathei** [script3/yieldblox-beta#201]
I stake parts: 1/4 year, 1/2 year and 1 year.When i want unstake 1 year but but no 1 year part give me unstake, only show 1/4 year part.
![0 5 y](https://user-images.githubusercontent.com/92008056/136640387-78d0c649-739f-455a-905c-ec1e38289c23.png)
![1 4 y](https://user-images.githubusercontent.com/92008056/136640390-892d6199-c969-46ed-9374-9b1d8d1b5cfe.png)
![1y](https://user-images.githubusercontent.com/92008056/136640393-77830180-5285-4ddf-ace8-eb6f73e40544.png)
![unsta](https://user-images.githubusercontent.com/92008056/136640396-301a5dde-2a26-4fff-86fc-c955c4ed976d.png)

**Comment by drew-boy** [comment]
Unstaking goes off the original stake, so you staked for the 1/4 year lock
