### ISSUE TITLE
I can't repay ETH 

### ISSUE THREAD

**Issue by Zaghivatta** [script3/yieldblox-beta#203]
whay 1 can't repay my eth borrowed
![eth1](https://user-images.githubusercontent.com/55428229/136641110-083442c0-45c8-44e9-ae75-999af9726ab0.JPG)
![eth2](https://user-images.githubusercontent.com/55428229/136641120-7891ab8e-eca2-46b6-8287-3a309734e2d3.JPG)
![eth3](https://user-images.githubusercontent.com/55428229/136641125-739b2473-0f5c-4495-83fa-a9c27e538732.JPG)

**Comment by mootz12** [comment]
The error was a poor repayment request on the frontend side when with `repayment amount`, and didn't encompass a contract bug, hence the downgrade to minor.

Thanks for finding this!

**Comment by Zaghivatta** [comment]
My discord
@Dede Hermawan#0694
My pk 
GAA6ZVHMXFKVLWGCC2PPJTDKQPFXOYIUF67K374XDH2HELEICXCSZZLA

**Comment by Zaghivatta** [comment]
My discord
Dede Hermawan#'0694
my email
dedefxhermawan@gmail.com
my YieldBlox Testnet Beta public address
GABYFNYJMLGAOSS2EOKN3JBB2ZKUWXBQGWN6EAKKQUXXFE6SOM7NLVR4
personal public Stellar address
GAA6ZVHMXFKVLWGCC2PPJTDKQPFXOYIUF67K374XDH2HELEICXCSZZLA
