### ISSUE TITLE
Repayment USDC with collateral BTC Max its show error message, but it is successful.

### ISSUE THREAD

**Issue by reigister** [script3/yieldblox-beta#204]
It is show error message "Something went wrong, unable to complete your request"
this is XDR "AAAAAgAAAAAYGpnPRyK9RwQUAElCpFztNJfB+TOhQ+di+hi9NvLusAADW2AAA6GTAAABHAAAAAEAAAAAAAAAAAAAAABhYQNsAAAAAQAAAAh5YnhSZXBheQAAAAsAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAADljAUQR5yC1IQ3o7FKgA6dXqbV6+aq6zl9wGreI3pggQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAABgamc9HIr1HBBQASUKkXO00l8H5M6FD52L6GL028u6wAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAzAfOwAAAAAAAAAQAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAA+RT3YpFMsFQmVYcon24dKdYDAv4JjpHo3Rhpe3AkHwcAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADgAAAAJsMDBVU0RDAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAOetS1tHQAAAAMAAAAAAAAAABgamc9HIr1HBBQASUKkXO00l8H5M6FD52L6GL028u6wAAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAABAAAAAAAAAAAAAAAAAAAAAIAAAABQlRDAAAAAAA1Ek02bEhKY4k7M1uIniJN5hg0JdWoXuxpOkwCDDa1cQAAAAAAAAHSAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAAAWYF7AAAAAAAAAAAAAAAAgAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAMwHXsAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAovMvBkyAAAAAAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9+mOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAXz6VQAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAEwAAAAJ1MDBCVEMAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9+mOJ4AAAAAAAAAAQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAnUwMFVTREMAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAF92UjAAAAAAAAAAN8/BMdAAAAQKjqChPV3Ii9Zvz6Pvqv5Gv/H7XzeFd+eJhoCzWjdTyyvLw6JKtDF7I7/NdXxmoSUi3UVXnMyBRW4O2u9FWNAQdKLFbCAAAAQKceQk155ZIw2eVHYz8i3Qblvsuma6foDBY4aWIEZ1esL9KWGYNNkfJqXajyueER1VRP4xHHc1+9o6TqF8bS0A028u6wAAAAQK7F/muj7Ck9qFtzaJ58zlkAoZP9To9X8g/rtBltY9vtcrPP1f5UKSsc9PaOS1u2lGMCt7168IhJ9QUrqHsIxQ0=

![try to repayment USDC with collateral BTC](https://user-images.githubusercontent.com/78670969/136641573-6a960591-bbc1-43f6-b258-7a8f25d5f810.png)
![try to repayment USDC with collateral BTC 2](https://user-images.githubusercontent.com/78670969/136641576-eb57297d-b323-4520-9e8d-95a5a16cc740.png)

when i try refreshing it successfull. my loan is decreased. and my collateral BTC is 0. but why show error message in front of it.

**Comment by StellarStoic** [comment]
I experienced this as well

**Comment by mootz12** [comment]
There was a stellar-sdk bug fix we missed on the frontend, and this has been resolved. Thanks!

**Comment by reigister** [comment]
Discord username : register#1319

**Comment by markuspluna** [comment]
Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public
