### ISSUE TITLE
Unmatch display when want to edit the collateral value

### ISSUE THREAD

**Issue by ygusmada** [script3/yieldblox-beta#206]
is this caused by a slow page loader or UI?

https://user-images.githubusercontent.com/28614308/136645297-c3a61e91-957d-4426-90af-58c136724e0f.mp4

**Comment by StellarStoic** [comment]
Also, weird values sometimes appear
![Screenshot (302)](https://user-images.githubusercontent.com/34000272/136668836-3cf8ef79-4827-4d19-9f35-6b968c477431.png)

**Comment by drew-boy** [comment]
solved with new input

**Comment by ygusmada** [comment]
ok

Pada tanggal Sel, 12 Okt 2021 06.53, drew-boy ***@***.***>
menulis:
