### ISSUE TITLE
Unmatch Collateral on Lent and Repay-with-Collateral

### ISSUE THREAD

**Issue by ygusmada** [script3/yieldblox-beta#208]
My collateral is 92, 85,78 and 92.
![image](https://user-images.githubusercontent.com/28614308/136646152-428f4631-f68a-4d14-af9b-785fddfb9fe6.png)

When i want to repay my borrowed using collateral, it showing default number 85, 90, 90 85 (Loan-to-Value percentage) and the amount doesn't follow collateral that i use. 
![image](https://user-images.githubusercontent.com/28614308/136646153-3701b084-2bdd-4fd3-ae6b-76b764aab3c5.png)

**Comment by drew-boy** [comment]
This is how it is supposed to work
