### ISSUE TITLE
Display issues with Float and Fixed Interest Positions on Market Borrow screen

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#212]
1. Borrow EURT with Float Interest Rate (347.51k EURT)
2. Borrow EURT with Fixed Interest Rate (100 EURT)

Correctly separates the Fixed and Float positions on Profile Screen:
![image](https://user-images.githubusercontent.com/11483548/136647812-05c70ef7-a81c-462c-8b7f-b3b78876ea8d.png)

On Market Borrow Screen, with Float Selected, it shows current borrow of 347.51k EURT
![image](https://user-images.githubusercontent.com/11483548/136647844-8f4d0947-9ce3-4c91-b85f-76b98f8f0c82.png)

On Market Borrow Screen, with Fixed selected, it shows the same current borrow of 347.51k EURT, it should only show 100 here:
![image](https://user-images.githubusercontent.com/11483548/136647906-96ca9524-8fd0-4871-b9f1-07d307d520aa.png)

3. Borrowed another 2k EURT Fixed
![image](https://user-images.githubusercontent.com/11483548/136648024-48f9d9d9-6b8e-448e-8eb1-afb0dd081392.png)

On Market Borrow Screen, with Fixed selected, it seems to show the float position when fixed is selected:

![image](https://user-images.githubusercontent.com/11483548/136648069-36f0f8b5-34c5-4cc1-910a-1bdfa6461a0a.png)

Note, if you try and borrow more fixed rate it shows the position value for float:
![image](https://user-images.githubusercontent.com/11483548/136648123-c32956dd-f8b1-4a2b-b7d0-7808401f263a.png)

4. Borrow another 1k EURT Float, updates on profile
![image](https://user-images.githubusercontent.com/11483548/136648151-109da9fd-9669-45c7-b363-2feeab425a5b.png)

Now Fixed position is displayed when Float is selected! (2.1k) - Appears to show the last fixed or float position regardless.
![image](https://user-images.githubusercontent.com/11483548/136648251-66695a30-7ee3-424f-ad3d-cb316dd5dd03.png)

![image](https://user-images.githubusercontent.com/11483548/136648255-1f2d450d-0740-40f0-a493-f86600f58425.png)

Also Borrow screen now shows the current position as 2.1k
![image](https://user-images.githubusercontent.com/11483548/136648278-b3327d55-64a1-495a-9d5e-8b14bbdc696d.png)

**Comment by mootz12** [comment]
Good catch. The actions will still apply to the correct types (since they are done through the profile page), but the display is really confusing.

**Comment by defj** [comment]
Discord: Tineye#2905
YieldBlox Testnet Beta public address: GDMM2XCYLGRQNMEULK44VYSVLIXQUWXIQTKHQH7RFQ42SGKCIMMPMKNF
