### ISSUE TITLE
Lost BTC when borrow and Lend it again

### ISSUE THREAD

**Issue by ygusmada** [script3/yieldblox-beta#215]
i currently borrow 2.06 BTC and wanna try to lending it again. But when i try to lend it, BTC that i borrow is not credited to my account.
![image](https://user-images.githubusercontent.com/28614308/136654506-766bdc68-64a4-4f1a-a04e-7277ec5654ca.png)

![image](https://user-images.githubusercontent.com/28614308/136654533-36705d3a-5a25-4572-a2a6-2c92c98f2e2a.png)

![image](https://user-images.githubusercontent.com/28614308/136654538-fb85aaeb-fd26-4b80-898b-849646a90a95.png)

**Comment by mootz12** [comment]
Have you converted / spent that BTC elsewhere already? The BTC will be issued at the time of borrow
