### ISSUE TITLE
Repaying debt is a hassle

### ISSUE THREAD

**Issue by StellarStoic** [script3/yieldblox-beta#216]
Repay BTC 1,000433430705083 - _(POP-UP) Something went wrong! Unable to complete your request._ 

Repaid BTC 0.5 - **success**
Repaid BTC 0.5 - **success**

Change still needs to be repaid BTC 0,0004348000125178265 - _(POP-UP) Something went wrong! Unable to complete your request._ 

[XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAABLAAA6ivAAAAggAAAAEAAAAAAAAAAAAAAABhYWWnAAAAAQAAAAh5YnhSZXBheQAAAAYAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAPAAAAAHnpLrqoj9x3pbyQHnKc1c0nBosEFr4I69JRiZ2FvbDrAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAEAAAADAAAAAAAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAAAQ%2FAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9%2BmOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAPyJdYAAAAAAAAAA3z8Ex0AAABAzcf%2FHS8uqoHynIsHd2%2FPT3cZNjRoR99%2Bho92DeLi%2BXoCtgbIrK9ZUo2Ic%2FWE4TUgJBYYTWqd2fznN8ye%2FTsYAkosVsIAAABAygncf9VQcXphU70u%2BT1UulZV2Z4uNsTHIlygsWC4eSndJ0jktPSYU0%2BWfqCQXmoU8q7BYV%2B7rra1XxAqglQRDbppRAoAAABAezHML86SbLTMeIKOhNiX5PSLxLW1o0dItZu959Bsjh7xF0f4G4e9lM4ewehiun3d6AJSUGSZz6aKYxM29JCOBg%3D%3D&type=TransactionEnvelope&network=test)

Then I tried to repay with collateral USDC 24.62 - _(POP-UP) Something went wrong! Unable to complete your request._ 

[XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAACigAA6ivAAAAgwAAAAEAAAAAAAAAAAAAAABhYWZuAAAAAQAAAAh5YnhSZXBheQAAAA0AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAAx28bNMjK8lhZn9g6i03CSqEYbsxoaIu8lQRX%2Bgt9RPQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAABAAAAACKwqMSwo%2B5F%2B9lW64OiKtGqkS6sQvMtjbiGnLi6aUQKAAAAAVVTREMAAAAACB2eQLRqhZI%2Bn1rL9qB81ce92ggXv546I6iFd98ySkcAAAAADqy6jQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAABAAAAACKwqMSwo%2B5F%2B9lW64OiKtGqkS6sQvMtjbiGnLi6aUQKAAAAAnkwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAE336RjiAAAAAAAAAA4AAAACeTAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAATffpGOIAAAACAAAAAAAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAAAAAAAAAAABAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAB56S66qI%2Fcd6W8kB5ynNXNJwaLBBa%2BCOvSUYmdhb2w6wAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAOAAAAAmwwMEJUQwAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAAAAAAACAAAAAwAAAAAAAAAAIrCoxLCj7kX72Vbrg6Iq0aqRLqxC8y2NuIacuLppRAoAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay%2FagfNXHvdoIF7%2BeOiOohXffMkpHAAAAAA6sueYAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAABQlRDAAAAAAA1Ek02bEhKY4k7M1uIniJN5hg0JdWoXuxpOkwCDDa1cQAAAAAAABD6AAAAAAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAA78nXTQ0NaNI%2FTpXwvzB%2Bm0Ms4zYdPVDrRoU1JSZxhosAAAACdTAwVVNEQwAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAnJmwkAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAEwAAAAJ1MDBVU0RDAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAA78nXTQ0NaNI%2FTpXwvzB%2Bm0Ms4zYdPVDrRoU1JSZxhosAAAAAAAAAAQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAIocaAtkXN0c7%2BdjpQ%2Fd6jqLeQW8zXFCDCK63mffpjieAAAAAnUwMEJUQwAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAACT8S6AAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAIocaAtkXN0c7%2BdjpQ%2Fd6jqLeQW8zXFCDCK63mffpjieAAAAAAAAAAEAAAAAAAAAA3z8Ex0AAABAv5OR5qirjc5lGZSB2fI7isACVtodnV%2F6IKYHSE0ZVAPKrMADF%2FG6AywiWYJJdBKAT9b7PjEY6JTgFOl3%2ByLSDEosVsIAAABAc5lloR6k0TTrEJAbTCnoRF4LZAPReTpf0hmG8CNkxaqJzfLnaP6m4a6XwcyH8Najmo3BmHkTGpxfPKYWtd5JArppRAoAAABABeels6bzrKVbu0r%2FvVlE%2B4c%2FNYrhbDvKE0qoIAyJvGYb1p3xfTzgvJYC7fw6DkT9Lhdi1ezGhiaRn%2F0wy4w1DQ%3D%3D&type=TransactionEnvelope&network=test)

Then I borrowed BTC 0.99956519998 to round up the number to 1 BTC which I failed to calculate and now I need to repay  BTC 0,9995654259105051

I select MAX and hit repay - _(POP-UP) Something went wrong! Unable to complete your request._ 

[XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAB1MAAA6ivAAAAhQAAAAEAAAAAAAAAAAAAAABhYWftAAAAAQAAAAh5YnhSZXBheQAAAAYAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAPAAAAALZHvCGK6DsbeBA4KhMp6Ha%2Fq5x0Mq4XP7vvJ%2B5794yrAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAMAAAADAAAAAAAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAJiFhgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9%2BmOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAZFfE4AAAAAAAAAA3z8Ex0AAABAWRapBe%2FRqjoYeAoVxP1tmv5suroxw3JJ3TPtlbls0zqKJGXjpFIn0ZFraXYA4l7yjYRBurKlsGkhZbeiIxYqB0osVsIAAABAV5DKVsS0SO9%2F7u3jLbMHKcJRhKBzGlKruur5XgAk6uMJn0dOtHEnLwvFzeGtAqJ22NyLPBqFRQ0nSJ0N9KyfA7ppRAoAAABAUVauMDPKPoW%2Bta41O2oGrOpmx16E8etl7YRAalPHi%2BSA%2BAr0fR9ci9GQsFHTAQZ9%2F08qcVTgjH1DEfiX1QQMBg%3D%3D&type=TransactionEnvelope&network=test)

Then I borrow again BTC 0.00043480002 which was a **success** - [TX](https://stellar.expert/explorer/testnet/tx/0bd516ba733df7d60a1d71214b5fc2d35572665725810e1cbd350651aeb550c2)

And now I tried to repay BTC 1,0000144319559634 - _(POP-UP) Something went wrong! Unable to complete your request._

[XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgACcQAAA6ivAAAAiAAAAAEAAAAAAAAAAAAAAABhYW6fAAAAAQAAAAh5YnhSZXBheQAAAAgAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAPAAAAAAyjqSMvGk%2BBP1NtZSZkYOhnsu5sLorh7TjNlbzqkFXNAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAcAAAADAAAAAAAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAAAAHQAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAJiW8wAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9%2BmOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAFSQ3AAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAEwAAAAJ1MDBCVEMAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9%2BmOJ4AAAAAAAAAAQAAAAAAAAADfPwTHQAAAECdkoO49kVM86i9c77%2BiLfqbh8hUjgCmSV0AUyXjaU%2F4RbLfStIc6YFXM0jATMfDRSbpCJh2Mu4%2BvVaw3jod9EBSixWwgAAAECAcfCXE8nTs6AVcgedvjnUY4zHQdsCCdym4ERsTbjl8QyXllUKSDNqVterEGOv%2BNdUk8eQe2dwaGoCOvI8eScAumlECgAAAECEexoVxqxNPEr85gcmFV0ui1RDfAjvZuVHPB2RX%2FgTYTmx5kE3Lxl7bYqhbHrUHSBhvqMWEq7IHILZR1QIZQ8F&type=TransactionEnvelope&network=test)

I see the minimum amount to borrow is in 7 dig BTC 0.0000001 [TX](https://stellar.expert/explorer/testnet/tx/f4f00a348ae7850398f5e2490c18441989d41d63e77c8812788df5750a9c4d4f)

Now I try to repay my debt in 7 dig exactly BTC 0.0000001  which was a **success** [TX1](https://stellar.expert/explorer/testnet/tx/6385b3cb0e48f0a5656c30138417aefb0bd59f1761b66154a2d4c4c566a164ae)

then I tried to repay BTC 1,0000204 which was unfortunately denied - _(POP-UP) Something went wrong! Unable to complete your request._

[XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgACIuAAA6ivAAAAjwAAAAEAAAAAAAAAAAAAAABhYXQPAAAAAQAAAAh5YnhSZXBheQAAAAcAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAPAAAAAJghDgtSk6WaLW%2B0GugkvmN9j0PxULN%2FkXhPDB4YW%2F3VAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAA4AAAADAAAAAAAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAAAAKAAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAJiXJAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9%2BmOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAbyR2YAAAAAAAAAA3z8Ex0AAABADw5ponSLNDWrtlgaciwg9%2F0GUAT8vR5uyuxzAWSrdu%2FKO1HshfHGiM7ZVkko8jbCQM5KaKIQGJQfXEDQQdj%2FDUosVsIAAABAUQ8JihM4%2FvG5jeEmnEnH3zEMiwuf5YmXhDUZ%2FMBvDFcBdBzrCYp1TpovzHNSfcRwYrMc0Q4huOWL%2BE3LjwKUALppRAoAAABAj6F8MEDEerdLnberMq1OEvtfZYK%2BKQF3Px%2B9P%2FtASyHzjZPi%2FE0eXlx%2BPonPRUfiiSMftYeEzajhPOZZ6lRmDA%3D%3D&type=TransactionEnvelope&network=test)

Here I round up my repayment to 6 dig BTC 1,000020 and again - _(POP-UP) Something went wrong! Unable to complete your request._

[XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAAG1gAA6ivAAAAkAAAAAEAAAAAAAAAAAAAAABhYXUGAAAAAQAAAAh5YnhSZXBheQAAAAcAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAPAAAAAJghDgtSk6WaLW%2B0GugkvmN9j0PxULN%2FkXhPDB4YW%2F3VAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAABMAAAADAAAAAAAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAAAAKAAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAJiXIAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9%2BmOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAlDDKAAAAAAAAAAA3z8Ex0AAABAHEQ0195YMpwfCj4T%2Bn4aNOQnl6M8XvbSbVSEfyLMc64ZiTQtKXhYrLtcPuK9xCK0eJL6oDF6SKyNNM6VbcgTBEosVsIAAABAqJg71rgQ%2Bz9FqCVohnabShcaArPIdHmMWHtFVFsHoJNn3NSyLdTfDHeg8eaUpSwD8B2jwlGszECvJD%2Feu6MPDLppRAoAAABAV3Tl07yyyUjuR8fv2QUjsOWqFTCmHKHC8u1T3CruyY5jwBDQuMgOw4N4OlaXVTJuBaX0Qk8Jhs05Q3jgMZBlCQ%3D%3D&type=TransactionEnvelope&network=test)

and here I am again trying to repay 1 whole BTC without success - _(POP-UP) Something went wrong! Unable to complete your request._
 [XDR](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgACIuAAA6ivAAAAkwAAAAEAAAAAAAAAAAAAAABhYXYqAAAAAQAAAAh5YnhSZXBheQAAAAcAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAPAAAAAJghDgtSk6WaLW%2B0GugkvmN9j0PxULN%2FkXhPDB4YW%2F3VAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9%2BmzFMAOt%2FAAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAOkAAAADAAAAAAAAAAAisKjEsKPuRfvZVuuDoirRqpEurELzLY24hpy4umlECgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAAAAKwAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAJiWVQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM%2FDVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9%2BmOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAlDDKAAAAAAAAAAA3z8Ex0AAABAvzFjHynM78QEgaXiK%2B1g8IWpXdj5j12jWpDz35FTQU9Bdq1ypLqOXReRtPIgH3u%2FKq0iezcrq1fbG41RjIsiDEosVsIAAABANLD1HCMfjrsd5MSA0IWARQ8QOPEGgdobk0T35hJ2qrzkjIDNk32%2BMfx0JKpAYlwnZYiuCTP5oA%2Fo7LjSNy6pALppRAoAAABAfKKS765qPecy7oR3YGjN%2BfyhA%2BXPlSL4SIWM4ufeHNRu6c1SAwmmQ5v1%2FwRvqKWYN%2Fbpg46fYtk2VyAweb4BDA%3D%3D&type=TransactionEnvelope&network=test)

But repaying BTC 0.9 was a **success** - [TX](https://stellar.expert/explorer/testnet/tx/8f53dd0fd390ac43469bd6cd19ec8f00079b4521fc42e74ef51941c3c63c056f)

weirdly Interesting!

**Comment by SimplePotato** [comment]
Oh I see [StellarLabs XDR viewer](https://laboratory.stellar.org/#xdr-viewer?network=test) doesn't automatically fill in the link with XDR 
**Solution:** 
_Right-click on the link - Copy link address and past it in XDR viewer - Delete what doesn't belong there :)_

**Comment by StellarStoic** [comment]
I see [StellarLabs XDR viewer](https://laboratory.stellar.org/#xdr-viewer?network=test) doesn't fill in the XDR automatically.
**Solution** (Brave browser) : 

1. Right click and "copy link address"
2. Open [StellarLabs XDR viewer](https://laboratory.stellar.org/#xdr-viewer?network=test)
3. Past copied link in URL bar and **DON'T hit enter!**
4. Select the address browser suggested to you _(Blue Bolded Link address)_

**Comment by StellarStoic** [comment]
Now it went through after I did who knows what. [TX](https://stellar.expert/explorer/testnet/tx/1863135e72a200ec4d0160f804b2241c084088405669fb27b3b733d4378b9e6c)
I rebalance my positions playing a little with the collateral slider on various assets and then I repaid $0.01 in BTC. The borrowed BTC Box finally went away.
