### ISSUE TITLE
Failure to pay the debt

### ISSUE THREAD

**Issue by binhkieu** [script3/yieldblox-beta#217]
I have more than 55 thousand USDC that have not been lent, but when I pay the debt of 17 thousand USDC, the system gives an error.

- 
![dư usdc](https://user-images.githubusercontent.com/36544627/136659936-5079d923-5f35-4adf-a5ef-92ef45fa500d.JPG)
![Ảnh trả nợ ko được](https://user-images.githubusercontent.com/36544627/136659939-26f617ee-d5ae-4c50-bd39-78ec0f1586fe.JPG)

**Comment by nixfreak** [comment]
I have also seen this issue with trying to repay using collateral. 
![20211009_14-56-repay_with_eth](https://user-images.githubusercontent.com/3707258/136672411-4fbb170b-3658-408a-b669-ccb2756e81df.png)

![2021-10-09_14-58-repay_with_eth-1](https://user-images.githubusercontent.com/3707258/136672414-0feb08b0-c67d-4a2f-b433-c93e85837c6e.png)
![2021-10-09_14-59_repay_with_eth_confirm](https://user-images.githubusercontent.com/3707258/136672418-4450798c-2e68-4cbd-b919-70e32bd72216.png)

![2021-10-09_15-01_repay_with_eth-error](https://user-images.githubusercontent.com/3707258/136672422-78da2241-01a5-4f09-8ffb-45a27baee1da.png)

**Comment by nixfreak** [comment]
Ok very interesting with paying back a BTC with collateral of BTC 0.1 the transaction went through and submitted successfully.

**Comment by mootz12** [comment]
Repay with collateral was in bad shape, but was fixed recently. Please let me know if this is still an issue.
