### ISSUE TITLE
Repaying all BTC - Small amount still borrowed

### ISSUE THREAD

**Issue by StellarStoic** [script3/yieldblox-beta#219]
When repaying all BTC loans, $0.01 usually still stays borrowed

![000btc](https://user-images.githubusercontent.com/34000272/136667561-eeaac026-2097-44b8-86cc-0cf7db298cff.png)

Paying back with collateral in USDC $0.01 wasn't working even when having enough funds.

I resolved it with withdraw of 0.0005 BTC to my wallet and then repay 0.000003 BTC

To avoid this on any assets I suggest not to chose 100% on anything except when repaying debt.

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/32
