### ISSUE TITLE
Collateral management weird values

### ISSUE THREAD

**Issue by StellarStoic** [script3/yieldblox-beta#220]
Also, weird values sometimes appear
![Screenshot (302)](https://user-images.githubusercontent.com/34000272/136668836-3cf8ef79-4827-4d19-9f35-6b968c477431.png)

_Originally posted by @SimplePotato in https://github.com/script3/yieldblox-beta/issues/206#issuecomment-939334085_

**Comment by drew-boy** [comment]
Solved with new collateral input
