### ISSUE TITLE
Page did not automatically refresh

### ISSUE THREAD

**Issue by starlog20** [script3/yieldblox-beta#223]
If we open 2 tabs in similar site. the tabs that not doing action didn't automatically do update if we dont do refresh

![image](https://user-images.githubusercontent.com/92114001/136671096-6f39f224-2c5d-475b-9047-6fa170bbc74a.png)

above is tab without action (no refresh)
below is tab with action (refreshed)

maybe someone doing multitasking when doing lending and borrowing, so this is annoying imo

**Comment by f0xie7** [comment]
Probably same issue here https://github.com/script3/yieldblox-beta/issues/169

**Comment by mootz12** [comment]
Appears to be a duplicate. See issue 169 for updates
