### ISSUE TITLE
Values returning not returning to zero (--) on borrowing page

### ISSUE THREAD

**Issue by Mcsunky** [script3/yieldblox-beta#224]
Using freight, as seen in the short clip, after inputting the amount of Ethereum (5 ETH) in the "amount to borrow" query box, I changed my mind and decided to borrow USDC instead. Following that, on the USDC borrowing page the "amount to borrow" query box didn't return to zero (--) rather it remained at 5 (Amount of ETH i wanted to borrow initially).

https://user-images.githubusercontent.com/35813996/136671136-12da4ee9-5716-4d97-84bc-a80b2c26f83d.mp4

**Comment by mootz12** [comment]
This is by design, state will be maintained until you submit, or manually clear it.
