### ISSUE TITLE
Unable to remove collateral

### ISSUE THREAD

**Issue by Mcsunky** [script3/yieldblox-beta#225]
Using freight, I tried to remove EURT collateral but freight extension didn't pop up to approve and confirm transaction. Other market worked fine.

https://user-images.githubusercontent.com/35813996/136672393-f746c061-80ee-48b5-966b-8d2b2d035c0d.mp4

**Comment by drew-boy** [comment]
You didn't change your collateral of EURT?

**Comment by mootz12** [comment]
Ditto above comment.

Also, browser wallets and apple "full screen" have a long way to go. I've found many interaction bugs thus far.

Unfortunately, we don't have much control over this.
