### ISSUE TITLE
All USDC debt paid but the card is still there with zero balance + Empty transaction of repaying 0 went trough

### ISSUE THREAD

**Issue by StellarStoic** [script3/yieldblox-beta#226]
![Screenshot (306)](https://user-images.githubusercontent.com/34000272/136672459-52828bbf-f2bc-43fb-be51-56f88c5a2fe5.png)

![Screenshot (307)](https://user-images.githubusercontent.com/34000272/136672464-9e7b55e1-485d-4767-9779-b8768d850cef.png)

![Screenshot (308)](https://user-images.githubusercontent.com/34000272/136672476-87634da3-8861-4d4d-b7cd-02f4074c422a.png)

![Screenshot (309)](https://user-images.githubusercontent.com/34000272/136672484-69c1dcf4-fdf6-4c86-a2de-660640da8b66.png)

[TX id](https://stellar.expert/explorer/testnet/tx/729f5408c47c89c364cedf5bc8ebb5ce47b69a4fa26a67056c36b14f4133feca)

The card disappear after I select 100 USDC (I'm not sure if I was charged $100) [TX id](https://stellar.expert/explorer/testnet/tx/98e0bbc0e9e109dc212e92d00f65c4af4ff6ff2c98ff326c50fed1d1b64f5e7d)

**Comment by markuspluna** [comment]
You weren't charged 100. Likely an issue with how the UI displays liabilities of less than 0.01
