### ISSUE TITLE
Auto update balance when swap

### ISSUE THREAD

**Issue by jakathei** [script3/yieldblox-beta#227]
When i swap euro to ethereum in Albedo wallet
![albe](https://user-images.githubusercontent.com/92008056/136676918-72eae981-51a5-4b79-bbce-476342937986.png)

My balance in beta Yieldblox not auto update

![githu1](https://user-images.githubusercontent.com/92008056/136676939-f16888dc-0dd6-4716-80c2-d9536dc8f9ba.png)

When i refresh it update the balance
![githu2](https://user-images.githubusercontent.com/92008056/136676960-168f279a-ca36-4133-a3e9-32dceb4c8c9a.png)

**Comment by drew-boy** [comment]
How are you using Albedo?

**Comment by jakathei** [comment]
I am using Albedo for swap .

**Comment by jakathei** [comment]
For example I borrowed 100k usd , and using Albedo swap 100k usd to Eth for lent by Eth. But It in't auto update my balance in web Beta.Although Albedo swap done

**Comment by mootz12** [comment]
This is correct. Your balances will not automatically update unless the webapp does something that causes them to change, or a 5 min window has passed.

This is to keep your web app experience fast, and our load on Stellar Horizon low.
