### ISSUE TITLE
Collateral Goes 0% 

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#228]
I am doing edit collateral on https://ybx-beta.script3.io/#/market.
This what happen, the collateral goes 0% and number of collateral looks bugged. 
![collateral](https://user-images.githubusercontent.com/91896561/136677122-256fe953-67f4-4c28-9a5d-976d9663bd73.gif)
,

**Comment by f0xie7** [comment]
I realized its happen when u edit collateral between assets, example u edit eurt, edit btc, than back to edit eurt again.

**Comment by drew-boy** [comment]
fixed with new input

**Comment by f0xie7** [comment]
Somehow its still bugged, also is this issue mentioned before. I got duplicate tag, but didnt know is it mentioned yet before.
Its collateral mentioned the last collateral opened, first time its 0, next when i open BTC, the data show ETH collateral, and so on.
![still bug collateral](https://user-images.githubusercontent.com/91896561/137266079-743ed87f-d7b2-468d-8139-d1f7d044b726.gif)

**Comment by f0xie7** [comment]
f0xie#8785
