### ISSUE TITLE
About Staked YBX.

### ISSUE THREAD

**Issue by masnarto96** [script3/yieldblox-beta#229]
does ii include a bug, i tried staking 360 days, shouldn't it be locked for 360 days? i tried to unlock by clicking max, but only 0 can be unlocked , but when i enter the value of sYBX manually unlockable, you can see the picture i attached, first picture before - second after

before
![Screenshot (38)_LI](https://user-images.githubusercontent.com/49241470/136677153-e9f75d45-693b-4629-815c-a240ebbadd21.jpg)

after
![Screenshot (37)_LI](https://user-images.githubusercontent.com/49241470/136677157-44ec37b5-7787-4550-9cb9-f4f6f5b040f2.jpg)

**Comment by drew-boy** [comment]
You can unstake early -- we're adding a caution message for this workflow
