### ISSUE TITLE
Lost ETH

### ISSUE THREAD

**Issue by LorDDark6660** [script3/yieldblox-beta#23]
depositing ETH all and collateral 0.01 '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

and ETH 0 in wallet and yieldblox too

Transaction 16ac55ec6a6e7ace6e1afa715a7161e46f81952811a2659a0e72ec6877477a32

Operation 1030070596550664

**Comment by drew-boy** [comment]
duplicate clearing

**Comment by LorDDark6660** [comment]
ok, i wrote it first to /docs my mistake
