### ISSUE TITLE
Repaying borrow bug

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#230]
I try to repay my loan, its doesnt repay my loan but it goes to my balance.Z
I expect the loan to be decreased while my collateral decreased too. But my collateral decreased, its move to balance, and didnt payoff my loan.
![repay bug](https://user-images.githubusercontent.com/91896561/136677198-22035e2c-819f-4867-9608-e599b4759bc6.gif)

**Comment by mootz12** [comment]
There was an issue repaying with collateral, where out input repayment amount was not accurate. This appears to be the same root cause.
