### ISSUE TITLE
Inconsistent information at Docs

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#231]
From https://docs.ybx.script3.io/user-docs/lending-borrowing/liquidations
1. borrower's loan becomes undercollateralized (their health factor falls below 1.00
2. only allowing liquidators to liquidate the borrower's position to the point where their health factor reaches 1.02.

Liquidation happens when its reaches 1.02 or fall bellow 1.00 ?

![image](https://user-images.githubusercontent.com/91896561/136677306-1280bd53-cda3-448b-8952-498433914e33.png)

**Comment by drew-boy** [comment]
Being liquidated increases the borrowers health factor -- their loan is being repaid
