### ISSUE TITLE
Rewards off

### ISSUE THREAD

**Issue by BrightLigth** [script3/yieldblox-beta#234]
I don't think reward are being tabulated correctly. Had a drop of 100 and change yesterday and 100 and change to day but that is not what is showing up. How can I correct drop amounts
![image](https://user-images.githubusercontent.com/92237131/136678165-f4eeb6a2-53fa-45d4-868b-7759d818d205.png)

**Comment by drew-boy** [comment]
Can you go into more detail?

**Comment by yuminaai** [comment]
I dont think this is bug. the mark in pict only show the next unlock, which is mean, if we stake 100 ybx at date A, and 200 ybx one day after date A, if you use same staking period, then the next unlock only show to you 100 ybx, not 300, ybx bcuz the nearest time to unstake is amount staked balance at date 'A'.

So it's work as wish imo

**Comment by BrightLigth** [comment]
Ok seem you need to un-stake to see the correct amount and then re-stake but then you hurt your future earning by un-staking. It would be nice to see a running total. Very difficult to see what is earned and what is owed to repay borrows and reclaim loaned.
Once you are on the wheel had to get a correct tally and to exit if needed. I enjoy the learning process but dont know what's a bug and what's a feature.Thanks for responding but I figured it out by un stake and re stake but should be that way or wont once lockup happens.
Peace
    On Tuesday, October 12, 2021, 01:28:28 PM CDT, yuminaai ***@***.***> wrote:  
 
 


I dont think this is bug. the mark in pict only show the next unlock, which is mean, if we stake 100 ybx at date A, and 200 ybx one day after date A, if you use same staking period, then the next unlock only show to you 100 ybx, not 300, ybx bcuz the nearest time to unstake is amount staked balance at date 'A'.

So it's work as wish imo

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mootz12** [comment]
The next unlock amount only shows your NEXT unlocked stake. So, if you stake again, it will not effect the next unlock.

There has been some confusion here, so we are considering some alternatives. Thanks for the feedback
