### ISSUE TITLE
Possible bug for borrowing and repay 

### ISSUE THREAD

**Issue by theboycoder** [script3/yieldblox-beta#236]
There was a spike in my health factor and apy, as posted here  https://github.com/script3/yieldblox-beta/issues/233 and by other people possibly. This spike occurred  after the ybx claim and locking it up for the staking period and previously this has happened before but only the APY spiked. Before the spike I was on the max health factor borrow limit with around 2m lent and 1.5m borrow, but during the spike the health factor opened up quite a lot and since i was limited before i decided to borrow as much as I could before the spike end. I ended up borrow 5m and and lent it out but my health factor was still stable above 1, but after it dropped to what it is now and I tried to repay certain amount to get back to 1 but there was a failure to repay.

 
![99a4e9c049553d17d275d44d3524beb5](https://user-images.githubusercontent.com/45983304/136678561-9dcb8330-24ae-4bf6-b70b-45fefea225e4.png)

![d3ca5202d5028a941df4905dd806384a](https://user-images.githubusercontent.com/45983304/136678560-3023176e-d355-41f7-a9ef-08e98bac192c.png)

 
AAAAAgAAAAACWDVnqIZy5scjeSpY9MUyuzKm4vpFY0Hnh1nxB5CWtAACvyAAA6c8AAABLgAAAAEAAAAAAAAAAAAAAABhYknvAAAAAQAAAAh5YnhSZXBheQAAAAkAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAH5smV6sQSnFoBZxVYjTVzz9KLkR2epQrgFNLbPuZEhqAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAuPjQAAAAEAAAAAAAAAAACWDVnqIZy5scjeSpY9MUyuzKm4vpFY0Hnh1nxB5CWtAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAAAJhAac4LhyqssutDVy8zhdPJdgMiV3JOklwPgaHdphFgAAAAEAAAAAAAkBYgAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAADzCqhoEZiiktGbtpy6PbGZAQ0sV9WzMZKfWvKjPmR4dQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMEJUQwAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAE8MHfAAAAAwAAAAAAAAAAAlg1Z6iGcubHI3kqWPTFMrsypuL6RWNB54dZ8QeQlrQAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAAAAg4AAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAOThPIAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAEQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAIocaAtkXN0c7+djpQ/d6jqLeQW8zXFCDCK63mffpjieAAAAAnUwMEJUQwAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAHAZgAAAAAAAAAAAN8/BMdAAAAQMIlkDvQUlHfDnDGjD+uDhy07zoVAL99CNb7z8ETYurYsST6CxhEuMRyg4qZMzMNHLGEAEYQo69pZ2dUUDUBrwxKLFbCAAAAQIY0dtbI3iktrmTBBt201H+WdfggfZiuzurRDxh0MIklbzx2IPIT6aMb2e6S4vVFSCeqoR1T36Q9RwU8srrmAAQHkJa0AAAAQBwWeeJVRvYnlRc9EHEY6DaaPmh65IyjtNZNIk0V+x3vYW7hlXGFBUVg3piBKHYOqALIoqHj31serZ+NpDG3jwg=

**Comment by f0xie7** [comment]
With this amount of lend and borrow, u probably got 4x ybx tomorrow...

**Comment by starlog20** [comment]
this is what i'm afraid from this issue  https://github.com/script3/yieldblox-beta/issues/205 if the issue come from protocol, and it happened 😂😂😂😂

**Comment by theboycoder** [comment]
> 
> 
> this is what i'm afraid from this issue #205 if the issue come from protocol, and it happened 😂😂😂😂

It might be a protocol issue but it's better for these issues to happen right now during the test period rather than when the main net launches, so lets get to finding the bugs!

**Comment by mootz12** [comment]
This was an issue in our pricing system for the testnet, and has been resolved.
