### ISSUE TITLE
repaying borrowed error

### ISSUE THREAD

**Issue by BrightLigth** [script3/yieldblox-beta#238]
AAAAAgAAAABflfQLABO/s5Gql3Iy78F2DT8wvUmpjovQmy3Q25CafQAABwgAA6jmAAAAYgAAAAEAAAAAAAAAAAAAAABhYmi/AAAAAQAAAAh5YnhSZXBheQAAAAkAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAE+4qoUs6IISJqpg95/hf9dOzcyhMzz9W9FLuIsh+iGGAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAHx4ejEkAAAAEAAAAAAAAAABflfQLABO/s5Gql3Iy78F2DT8wvUmpjovQmy3Q25CafQAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAAAJhAac4LhyqssutDVy8zhdPJdgMiV3JOklwPgaHdphFgAAAAEAAAAAAAbtEQAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAAhPcjeBBT2aiMcJhavIQr9fcjjwOeJiwiYHMeM0A9gegAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAinwxy4gAAAAAwAAAAAAAAAAX5X0CwATv7ORqpdyMu/Bdg0/ML1JqY6L0Jst0NuQmn0AAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAABZHYMsAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAIMeDSTUAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAEQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAnUwMFVTREMAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAB3YqQAAAAAAAAAAN8/BMdAAAAQEC7YUCD0K7nqpmxKLK2LDDK2W3XYNl3IxuX/D7DJ+XSGXzOIJfLy28H+JLUpkKu/6v8sBGoPn0my1ltcIC8Aw1KLFbCAAAAQGqKSIwBeUupOZipWF19yOKeIbchnSX0tQtK6T48HB02mdl0snDAtwYB75K3NFcVnHjNazZhnhMlQRcOdD4d9ArbkJp9AAAAQMkhxwwd9wBzqsdNqpgtHGpl44MLoLcaqrFKWmPAEPYJ6AVPeU7kI6YvV8cQg1RAI+HDlFywCZXIyjB97LHFmwM=

**Comment by mootz12** [comment]
I am unable to triage a bug with only the xdr

Please provide some additional information / reproduction steps about your issue, and I can reopen it.
