### ISSUE TITLE
Issue paying with collateral

### ISSUE THREAD

**Issue by Juniooor93** [script3/yieldblox-beta#239]
I tried repaying a part of my Eth loan- with USDC- and received two different errors. The first error said that there was a problem with the turrents: Unable to complete your request. Majority of turrets failed to execute contract. Unable to transform balance in request.

I then tried again and received this second error: 

AAAAAgAAAAB1JZk/Uc19wlaY+4aeOHAgOm02+cv28VEVO1MWXEIDZgAD96AAA6VwAAAAcwAAAAEAAAAAAAAAAAAAAABhYm0JAAAAAQAAAAh5YnhSZXBheQAAAA0AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAABrgz5RBC4nnfomk94358x/fmX7wauQlTzGEIzQhGNDrgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAHUlmT9RzX3CVpj7hp44cCA6bTb5y/bxURU7UxZcQgNmAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAIf5HJKgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAHUlmT9RzX3CVpj7hp44cCA6bTb5y/bxURU7UxZcQgNmAAAAAnkwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAWZ5P/SaAAAAAAAAAA4AAAACeTAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAABZnk/9JoAAAACAAAAAAAAAAB1JZk/Uc19wlaY+4aeOHAgOm02+cv28VEVO1MWXEIDZgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAABAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAADxPcarO/bkJiNXfLENz054gHOH6tSv5JtfvCx/s8VEAgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMEVUSAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAGm7SCAAAAAwAAAAAAAAAAdSWZP1HNfcJWmPuGnjhwIDptNvnL9vFRFTtTFlxCA2YAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAAAAAvd8AAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABRVRIAAAAAAAm/Hr+did1Niqr/LIylIKKOluv+dfLo2q0RY7qILYT0gAAAAAAAAAMAAAAAAAAAAAAAAACAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAIf5ESmAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFFVEgAAAAAACb8ev52J3U2Kqv8sjKUgoo6W6/518ujarRFjuogthPSAAAAAACYGb8AAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAABEAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAADvyddNDQ1o0j9OlfC/MH6bQyzjNh09UOtGhTUlJnGGiwAAAAJ1MDBVU0RDAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAABKpHzgAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAI5/uSuZx8KTY7FVjRUGglnnXgt3eVoXYIOombTaqwfKAAAAAnUwMEVUSAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAACIjQXAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwRVRIAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAI5/uSuZx8KTY7FVjRUGglnnXgt3eVoXYIOombTaqwfKAAAAAAAAAAEAAAAAAAAAA3z8Ex0AAABA+5YSzcPgOJw+j/DoZWRvN3M5njaAFeFcLKYzwKwaHxCEbhV+TVLjDdU6c05KY2gagKFfgeGHnSevUKHZAbLCBUosVsIAAABAdyg/coS+Ho0UjQ5u05MzUnXsv9Vx8TREK2Cb9ug9aqP1DZxHJ3t4I92JPnWO5bBwOhOK/aOKwRBezXqfI1jfDVxCA2YAAABAi4WrkXV+QWCiwQWptFCC4MzFhOVn6/ZZSmczGx/zh6HmsdG/OTCJgio9bJVZRwq2P51uKnpfKV21HYTKI8CFAA==

**Comment by mootz12** [comment]
This is a known error, and show up in a few different iterations in the github issue tracker.

It has since been fixed.
