### ISSUE TITLE
Deposit is'nt working ( BTC)

### ISSUE THREAD

**Issue by AbramSeptha117** [script3/yieldblox-beta#24]
I have made a deposit in btc worth 0.5.. for the status of the transaction it has been successful.. but not yet entered into the current deposit ybx beta-tesnet..  (I use albedo)

![Screenshot_2021-10-07-05-17-29-153_com android chrome](https://user-images.githubusercontent.com/75639636/136293820-0c2ade2a-5252-4726-a92b-d60fa6f0d40a.jpg)
![Screenshot_2021-10-07-05-16-32-477_com android chrome](https://user-images.githubusercontent.com/75639636/136293826-f1b1d243-ec52-4e0c-87e4-4d3a8fd83fa8.jpg)
![Screenshot_2021-10-07-05-14-44-177_com android chrome](https://user-images.githubusercontent.com/75639636/136293829-6b90b800-b7f0-4e7b-b8cf-027ac66eb749.jpg)

**Comment by tourBermuda** [comment]
I not sure if I have the same error but I got following message when depositing BTC.  @drew-boy @mootz12 
```Something went wrong!
Unable to complete your request.

'<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.```

However the BTC left my account and a Claimable was created for BTC. I only signed one transaction.
