### ISSUE TITLE
Can't repay small amounts with collateral when health factor is low but still above 1.02

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#240]
My health factor is 1.04
![image](https://user-images.githubusercontent.com/11483548/136682188-80457407-916d-4f4a-8657-0a044a986b28.png)

Attempted to repay EURT fixed borrowing with USDC collateral:
![image](https://user-images.githubusercontent.com/11483548/136682082-94fecacd-b2dd-421f-b704-d3e874479616.png)

![image](https://user-images.githubusercontent.com/11483548/136682113-98f27ff6-0428-4a3b-ad1c-9b2ee574364d.png)

Health factor is too low to permit withdrawal error.
![image](https://user-images.githubusercontent.com/11483548/136682174-b2976b01-abc6-480a-94ab-e4a0054299e9.png)

Suspect I may need to repay a large amount to put me above 1.10 but this is not clear.

**Comment by starlog20** [comment]
I'm afraid if you can repay with collateral bcuz repay with collateral mean your deposit balance also lost, so in the end you Healty factor almost no change bcuz your deposited balance is reduced same amount with borrowed balance.

if you have deposited 50000 USDC, and borrowed 49000 USDC, so the different is only 4%, then if you wanna repay with collateral 10000 USDC, both is reduced so you now have deposited less than 40000 USDC (bcuz u must pay interest fee) and borrowed 39000 USDC. which is mean the different is only up by 1% from 4% to 5%. 

but if you all in to pay debt, then your balance is rest 1000 USDC and lost 49000 USDC, leverage is danger 👀

**Comment by mootz12** [comment]
Good catch, we now allow for an increasing health factor transactions to work, so you can start inching your health factor back into a healthy state.

**Comment by defj** [comment]
Discord: Tineye#2905
YieldBlox Testnet Beta public address: GDMM2XCYLGRQNMEULK44VYSVLIXQUWXIQTKHQH7RFQ42SGKCIMMPMKNF
