### ISSUE TITLE
Depositing collateral

### ISSUE THREAD

**Issue by CPT72** [script3/yieldblox-beta#242]
Hi,

Unable to deposit Collateral independently of 'lend' deposit on the markets screen for any asset. 

Usually when I add a 'lend' deposit with collateral it will successfully create a transaction however this morning this has not been successful.

Is this by design or should I be able to do this? Would be ideal to be able to do this to facilitate further borrowing or improve health factor.

Thanks,
Patrick

**Comment by drew-boy** [comment]
Are you suggesting adding more collateral in general but not to a specific asset?

**Comment by CPT72** [comment]
Hi, apologies. No, I hadn't fully understand the protocol if honest. I was trying to use all my assets as collateral so I could borrow large amounts without lending them out. I realize now I can lend them, earn yield and use them all as collateral at the same time.

Sorry for the confusion.

Thanks,
Patrick
