### ISSUE TITLE
the borrow balance is the same as empty but but displayed differently

### ISSUE THREAD

**Issue by Esta00** [script3/yieldblox-beta#243]
the borrow balance ( eurt usdc ) is the same as empty but but displayed differently
![barrow2](https://user-images.githubusercontent.com/91866636/136691663-0d79d5fd-2d5e-48c3-a054-9380d0377809.JPG)
![barrow](https://user-images.githubusercontent.com/91866636/136691666-d443ddaa-37b8-4deb-8983-a7c3344eeb02.JPG)

**Comment by davidsa05** [comment]
maybe there is still a number/digit behind the decimal that has not been paid

**Comment by drew-boy** [comment]
yes, rounding issues

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/32
