### ISSUE TITLE
Can't repay max USDC.

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#244]
I borrow 100k USDC but when I try to repay max amount it shows an error. 
Attached screenshot & video in next comments.
Here's the XDR :
AAAAAgAAAADkzI7f6TOEPoHBB/g4v7Lt3Q40ItpYleDP7gDFNlS/ugAABXgAA6dBAAAA0AAAAAEAAAAAAAAAAAAAAABhYt4RAAAAAQAAAAh5YnhSZXBheQAAAAcAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAJv8v7Cyhf8GqxEalDdH1PRDkj0Cx3W6Y2N+5MVw6v7DAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAABsjMAAAADAAAAAAAAAADkzI7f6TOEPoHBB/g4v7Lt3Q40ItpYleDP7gDFNlS/ugAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAAAADWBgAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAADo1T7uNAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAA78nXTQ0NaNI/TpXwvzB+m0Ms4zYdPVDrRoU1JSZxhosAAAACdTAwVVNEQwAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAANK81gAAAAAAAAAA3z8Ex0AAABAbURg27pUZVLWYV89OFEaOW/r0Z7C6xdH3hx5z5qrz7+BnbSZx9pvLfGXgjiL4M4jzOK7IC3m2nwH7+1sC+D1AUosVsIAAABAuKUAGvK672+3BDgGngcYIbhDvAaTx+8LXDEStokMgKcGseyIh+uapAjZCRR5C8UMuixVqO0JCEd/OgA/TqZ1CjZUv7oAAABAXPeLyOfSUhRZncpTuoxh0pyzbQv6i+rHGvM2WL96Gs6LGWrLwwupeKcWdgxqD7ljWB+2ph1156W+9iSeeDLMCg==

**Comment by arnob016** [comment]
Step 1: 
![image](https://user-images.githubusercontent.com/74468064/136695987-5521d81b-15d0-4210-b229-86cb9b2f16a5.png)

Step 2: 
![image](https://user-images.githubusercontent.com/74468064/136695995-1d7f5c13-5705-4d8c-830b-94da678cec00.png)

Error: 
![image](https://user-images.githubusercontent.com/74468064/136696003-fec52677-9918-4b77-8eae-5041fff3a09a.png)

**Comment by arnob016** [comment]
If I leave 2$ as borrowed amount I can repay.
Here's the screen recording uploaded in google drive: (Sorry github doesn't support .webm)

https://drive.google.com/file/d/1Uyfpo3J3unAgc2LbaZdGcPwVr3plqIz7/view?usp=sharing

Ping me if anything is needed ( Discord : ArnobDey#5538 )

**Comment by mootz12** [comment]
It appears you entered 

$100,001.01

when you borrowed $100,001 USDC. Was there a chance that you did not have that much USDC?

The repayment modal was updated to avoid an issue like that, so maybe try and reproduce again.
