### ISSUE TITLE
Repaying borrowed asset cause skyrocketing of Health factor

### ISSUE THREAD

**Issue by sagarvd01** [script3/yieldblox-beta#245]
When repaying an asset, health factor is skyrocketing. **It's some calculation issue** (something like leverage) as it come down if we borrow something again.

![image](https://user-images.githubusercontent.com/15938422/136696214-e95ffb4e-aa9c-47d4-a96c-083049b733b2.png)

**Comment by drew-boy** [comment]
Working as intended
