### ISSUE TITLE
Easy Button on repay of loan

### ISSUE THREAD

**Issue by BrightLigth** [script3/yieldblox-beta#246]
De risking is a bear. Need an easy button. I was trying to repay my borrows all my borrows but there is no easy way too. You have to choose repay with collateral even if it doesn't seem to be needed because it is showing you have the asset in question to repay. So when you repay with collateral now you are stuck in the wheel.
Need a way to close positions easy One click and it works the repayment option. 
Same with loan Cant get off the wheel once it is loaned out.

Error on repayment keeps popping 
AAAAAgAAAABflfQLABO/s5Gql3Iy78F2DT8wvUmpjovQmy3Q25CafQACvyAAA6jmAAAAdQAAAAEAAAAAAAAAAAAAAABhYwOpAAAAAQAAAAh5YnhSZXBheQAAAAkAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAP9mExbaZ438PMu4XuzypjoB9IEMrn+uhQdYDETUntpmAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAC/b9IAAAAEAAAAAAAAAABflfQLABO/s5Gql3Iy78F2DT8wvUmpjovQmy3Q25CafQAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAAAJhAac4LhyqssutDVy8zhdPJdgMiV3JOklwPgaHdphFgAAAAEAAAAAAAizaEAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAA6mjxVw018pAp3b91ogrqWlZKipJgv69s2EGb7uOnV9AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMEJUQwAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAApErEAAAAAwAAAAAAAAAAX5X0CwATv7ORqpdyMu/Bdg0/ML1JqY6L0Jst0NuQmn0AAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAAACfQAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAExIwwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAEQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAIocaAtkXN0c7+djpQ/d6jqLeQW8zXFCDCK63mffpjieAAAAAnUwMEJUQwAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAJ1rNeAAAAAAAAAAN8/BMdAAAAQJ02gmedXnETE8xgVKRWnkv9oDlBLLrc4Cna/XnylrJSwSUQ6wnqZ3PpTjSSbSczjM/uVROEae+wgq9mdtmirQlKLFbCAAAAQKisT6yc2Sh5WPB+9TgJAPawcw8Hj4JOd/ye7LZ8XHn2TvYfjl8t3RLIWhzX+CsayKOTWqKRYBy30yfhasWoOwnbkJp9AAAAQLomUNVCgfapUJnHUc7ulCfsVkSMPMzaDY2XS6TVGL9cj1MxxbNBoMYDw7NfmEwOaiU0kouMqEML1xJDlNXHkA0=

**Comment by mootz12** [comment]
Repayment modal went through a big overhaul recently. Please let me know if this is still a problem.
