### ISSUE TITLE
Health Factor dropped after repaying EURT loan & wiped out loan w/o paying total loan amount

### ISSUE THREAD

**Issue by trossw1818** [script3/yieldblox-beta#247]
health factor was intially 1.12. Upon repayment of EURT borrow balannce it was supposed to be increased to 1.35 After repayment the borrow balance is cleared out but my health factor dropped to 1.09.
![ybx 1](https://user-images.githubusercontent.com/92266225/136705547-c281d60f-e3c8-4226-a4d2-48bbfbf00336.JPG)

Furthermore, when trying to repay the loan in its entirety w/ collateral I was getting an error that health "new health factor was too low". The max repayment seemed to be over-paying the loan.

![YBX](https://user-images.githubusercontent.com/92266225/136705611-9c991d69-9291-49b9-bb3c-8487120e5500.JPG)
![ybx 5](https://user-images.githubusercontent.com/92266225/136705771-a940844c-fa29-4163-a337-6b9f3f423bef.JPG)

I tried reducing the repayment to 100k EURT and got an error that I needed to reduce slippage and/or increase collateral
![YBX 3](https://user-images.githubusercontent.com/92266225/136705667-e1098d95-fba0-4c6e-a475-7e5163c8c5c6.JPG)

I then modified the repayment to be slightly higher w/ a lower slippage (seems unintuitive to me that I would need to lower the slippage allowed) and it went through but it shouldnt have wiped out the EURT borrowed amount, even though it did
![ybx 2](https://user-images.githubusercontent.com/92266225/136705698-61762a83-0068-40b4-8308-020a0878b124.JPG)

Notice the final transaction was only for 110k EURT but the borrowed amount was 131k EURT. However, it removed the entire borrow balance and somehow reduced my health factor as seen above

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/167

We were previously calculating the HF wrong for repay with collateral. Should be fixed now.

Let me know if this is still an issue.
