### ISSUE TITLE
Error when trying to repay loan w/ collateral of different asset

### ISSUE THREAD

**Issue by trossw1818** [script3/yieldblox-beta#248]
Attempting to repay BTC loan with EURT collateral but when doing so getting an XDR error. Have tried doing this w/ a few assets on a number of occasions but receive the same error every time
![ybx 6](https://user-images.githubusercontent.com/92266225/136707556-a7baf306-b73f-4125-9e14-60c38caf9378.JPG)

AAAAAgAAAAAJPnB3bzWg4zNqjVWMvjggwLRf29ei+fAVQntNCTxzOQAAB9AAA6iRAAAAlAAAAAEAAAAAAAAAAAAAAABhYyjdAAAAAQAAAAh5YnhSZXBheQAAAAoAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAAKo/K3+eknp4RR9rKHrY/06hlGz7I0FxNuq1xFJHq6HQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAAk+cHdvNaDjM2qNVYy+OCDAtF/b16L58BVCe00JPHM5AAAAAUVVUlQAAAAAAnN4X8L1YGspk5rx+yGy3gsrA34YrwYRKvN3wJ9AZTYAAAD5hs0BMAAAAAAAAAAQAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAAzmWV23ojoen/FqfRWXXZZFhJDuCTRWiMrWtlxt+APWMAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADgAAAAJsMDBCVEMAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAADNDA2QAAAAMAAAAAAAAAAAk+cHdvNaDjM2qNVYy+OCDAtF/b16L58BVCe00JPHM5AAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAABAAAAAAAAAAAAAAAAAAAAAIAAAABRVVSVAAAAAACc3hfwvVgaymTmvH7IbLeCysDfhivBhEq83fAn0BlNgAAAABVSj3eAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAABs6QAAAAEAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAAAAAAACAAAAAUVVUlQAAAAAAnN4X8L1YGspk5rx+yGy3gsrA34YrwYRKvN3wJ9AZTYAAAD5NMqKngAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAFK9B8AAAABAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAEQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAPfJmuPGPporE082oz1CxET26xHTPD9sWg/++qG03LdPAAAAAnUwMEVVUlQAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAI1MlSAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9+mOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAqXnHcAAAAAAAAAA3z8Ex0AAABAPrS9vbIssCTlRRhGIiGvzwSJT+jzwLeQntoZ+Gm9AyEVK0mI9vZgQpXwoe+mLkHbNXawsJMb8fT380OpGgm5AEosVsIAAABAsagOD6OD+oXg00UzisAVSqj8Nz1Tli+WnOu+UXim8XgrfzvZGny0HSTsJnz4Gsh/G2dLqFA6bEiAR2AvTs/7AAk8czkAAABAAkMbFp5C/x0tvnUc48jba3zjXsgjhnmNrYX+BptykQAPdo8d2EYgOd1M/+T+bn3FZ4lj5M03+3sU1lWuoPhTDQ==

**Comment by mootz12** [comment]
This was an SDK bug, and was fixed in a recent patch. Please see https://github.com/script3/yieldblox-beta/issues/204
