### ISSUE TITLE
Repay I know you know but maybe this might help

### ISSUE THREAD

**Issue by BrightLigth** [script3/yieldblox-beta#250]
I should be able to repay what I owe with the borrowed currency at the amount I borrowed and not leave a tad bit left over. Need to be able to close out a position totally
![Eth repayment](https://user-images.githubusercontent.com/92237131/136708810-f170f414-f25d-447d-98d3-6f82b659edc1.PNG)
![eth repayment 2](https://user-images.githubusercontent.com/92237131/136708811-c4d77fa0-ea9e-456b-bae8-9274e62e7fe5.PNG)
y

**Comment by drew-boy** [comment]
Thanks -- we'll look into it
