### ISSUE TITLE
Health factor suddenly goes up drastically after ybx claim and net Apy causing anyone to borrow high and lend back

### ISSUE THREAD

**Issue by austinero77** [script3/yieldblox-beta#252]
After I claim my allocation, suddenly the health factor jumped from about 1.12 to 1.88 and net Apy from 3.02 to 1.12K(thousand). This gives anyone to borrow high which I did and borrow EURT and swapped for ETH and lend back to the pool
![Screenshot_20211011-012251](https://user-images.githubusercontent.com/91912591/136718623-5356acf0-d7f4-4f01-abcb-2b73bb819ed0.jpg)

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/119
