### ISSUE TITLE
Too many operations for ybx claim 

### ISSUE THREAD

**Issue by coolrobiul** [script3/yieldblox-beta#253]
I noticed that when we claim daily ybx there are 16 operations need to be confirmed for a single ybx claim ??

![IMG_20211011_064154](https://user-images.githubusercontent.com/59414838/136718917-da27dc20-fdeb-4efe-bb13-4ff55157ff86.jpg)

I think this could be a reason that health factor, net apy, token yield is increasing after daily ybx claim.

**Comment by arnob016** [comment]
Here's another screenshot from me :
![image](https://user-images.githubusercontent.com/74468064/136727947-a7c7c8f8-5512-42fd-a89d-77b206f35eda.png)

**Comment by drew-boy** [comment]
Working as intended -- claim does a lot
