### ISSUE TITLE
Repayment USDC with all Assets (BTC,ETH,EURT,USDC) get ERROR

### ISSUE THREAD

**Issue by reigister** [script3/yieldblox-beta#254]
I want to repayment USDC with all Asset (BTC,ETH,EURT,USDC) but get ERROR, 

This is the XDR
AAAAAgAAAAAYGpnPRyK9RwQUAElCpFztNJfB+TOhQ+di+hi9NvLusAAHUwAAA6GTAAABkgAAAAEAAAAAAAAAAAAAAABhY6GdAAAAAQAAAAh5YnhSZXBheQAAABgAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAACxOJcwJ5AnSA3luWPvDonr1zAs9Am6i25QYOSZgInBSwAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAABgamc9HIr1HBBQASUKkXO00l8H5M6FD52L6GL028u6wAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAACtrAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAANMni9JUUXx0rp44Rsx11o1KBDkUg5BWLQP2gwuFhCASAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAGBqZz0civUcEFABJQqRc7TSXwfkzoUPnYvoYvTby7rAAAAABRVVSVAAAAAACc3hfwvVgaymTmvH7IbLeCysDfhivBhEq83fAn0BlNgAAAC0ZQXqgAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAA4IBc7RKnWNrCFVtCenS6SYaMoaREIf/SJbrL20ZTadcAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAQAAAAAYGpnPRyK9RwQUAElCpFztNJfB+TOhQ+di+hi9NvLusAAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAABn7DU8AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAB9/K4w6F5rYgqhdtg4EAYSwR1CoOy0oul9NXZPEVVV9AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAABgamc9HIr1HBBQASUKkXO00l8H5M6FD52L6GL028u6wAAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAAHc1k/wAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAABgamc9HIr1HBBQASUKkXO00l8H5M6FD52L6GL028u6wAAAAAnkwMEVUSAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAB5FvI6AAAAAAAAAA4AAAACeTAwRVRIAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAHkW8joAAAACAAAAAAAAAAAYGpnPRyK9RwQUAElCpFztNJfB+TOhQ+di+hi9NvLusAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAA1o1NenXUjA6nttCTB+aq1rWBGBo8hzHBmGVccH/ZWp4AAAAAAAAAAgAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAAAAAoAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAAAAB/a9AAAAAAAAAAAAAAACAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAACtogAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAAI8f8r4AAAAAAAAAAAAAAAIAAAABRVRIAAAAAAAm/Hr+did1Niqr/LIylIKKOluv+dfLo2q0RY7qILYT0gAAAAAAAblnAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAAFdh5gAAAAAAAAAAAAAAAAgAAAAFFVEgAAAAAACb8ev52J3U2Kqv8sjKUgoo6W6/518ujarRFjuogthPSAAAAAB3LvJIAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAYibKcwBAAAAAAAAAAAAAAACAAAAAUVVUlQAAAAAAnN4X8L1YGspk5rx+yGy3gsrA34YrwYRKvN3wJ9AZTYAAAAAAcQOFAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAAAFOTWwAAAAAAAAAAAAAAAIAAAABRVVSVAAAAAACc3hfwvVgaymTmvH7IbLeCysDfhivBhEq83fAn0BlNgAAAC0Xjs+NAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAiriAxHwAAAAAAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAJ1MDBCVEMAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAAAAAAQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAATAAAAAnUwMEJUQwAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAACKHGgLZFzdHO/nY6UP3eo6i3kFvM1xQgwiut5n36Y4ngAAAAAHbNQoAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAA98ma48Y+misTTzajPULERPbrEdM8P2xaD/76obTct08AAAACdTAwRVVSVAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAACL6JMAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAAD3yZrjxj6aKxNPNqM9QsRE9usR0zw/bFoP/vqhtNy3TwAAAAJ1MDBFVVJUAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAARe4KgAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAnUwMFVTREMAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAFos9MAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwVVNEQwAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAAAAAAEAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAACOf7krmcfCk2OxVY0VBoJZ514Ld3laF2CDqJm02qsHygAAAAJ1MDBFVEgAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAAJwvPQAAAAAAAAADfPwTHQAAAEDbGb3VL7+X+Ggshq4mwoEr7UfjfaquqlpaUMI4w1Zx9BPq1hN633meSMNu1JJ39NmFfqM3GdLFmWYRyKGm908D+T1+uAAAAEBnpX8Znj25hFbNquwEIo2FGwXgmAJ5/IyHsau48zZexoDcxXGQAiwZc2UtB6M92amH1f/41peNXt9jmtyXoWMINvLusAAAAEAvFYR7U3ati5r28NqiR/KRAwbcbwT2207j5TQDFOrfGJZ/IcjwTsqwQiRcL9FjGzX0NdnToIil7oVcgMHViWAD

This is my SS
![Repay with All collateral](https://user-images.githubusercontent.com/78670969/136724965-31fc6d76-e3e3-4c96-be8d-dabdf65fa822.png)
![Repay with All collateral 2](https://user-images.githubusercontent.com/78670969/136724980-f59b90e3-6c4b-4e8b-a9ca-9033cebe4110.png)

**Comment by reigister** [comment]
i have try refresh the page and do it again but always get the same message.

**Comment by reigister** [comment]
and suddenly the transaction was successful 

Another question: 
i have repayment usdc with all balance collateral BTC,ETH,EURT but why i got some BTC, ETH,EURT in my wallet. is it my interest?

check this SS

![Repay with All collateral 3](https://user-images.githubusercontent.com/78670969/136728350-a866ea2c-bf2a-4d1d-bdf2-1caa22851e2f.png)

**Comment by starlog20** [comment]
just my though. i think it is work as expected. you repay some amount fund that higher than your debt that you should repay. so the excess amount that you have paid is returned to your wallet.

**Comment by reigister** [comment]
my USDC collateral come back, it mean they not use my USDC collateral. They only use BTC, ETH, and EURT collateral. Maybe youre right. so system do random pick for collateral i have use to pay? i mean why system not pick all BTC,EURT, and USD and take a remaining in ETH.

**Comment by mootz12** [comment]
Anything that is not needed for repayment, will be sent to your wallet. The modal was updated recently to make this clearer. Please let me know if there is still an issue.
