### ISSUE TITLE
Wrong amount showing up in current borrow

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#255]
There's already EURT borrowed in my account, but when I'm trying to borrow more, it shows 0 in current borrow.

![image](https://user-images.githubusercontent.com/74468064/136728904-48d24ce2-ae1f-4815-b779-f8e1ae666ac6.png)
![image](https://user-images.githubusercontent.com/74468064/136728898-e6b99796-5af9-4a7c-9655-ae6082842072.png)

**Comment by mootz12** [comment]
This relates to a frontend bug with Borrow. See -> https://github.com/script3/yieldblox-beta/issues/212
