### ISSUE TITLE
Wrong Remaining borrow balance [UI bug]

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#256]
I tried to repay my borrowed BTC, clicked repay & didn't input anything. But the amount was already in negative.
![image](https://user-images.githubusercontent.com/74468064/136730099-8a6e6e48-1218-44a8-9e59-9d59b417b865.png)

**Comment by arnob016** [comment]
Borrow balance amount is completely messed up

![image](https://user-images.githubusercontent.com/74468064/136730561-01c2168d-9573-4c32-9e01-66e9b9107c68.png)
![image](https://user-images.githubusercontent.com/74468064/136730565-fc3e3bf1-6bc1-47a3-bdca-b24141f82d4b.png)

(I changed my collateral amount, then went to repay in the borrow tab, the amounts were completely different)

**Comment by arnob016** [comment]
Market is showing 0.00 as current borrow balance too.
![image](https://user-images.githubusercontent.com/74468064/136734375-c306403b-947e-47c2-8324-a233dd3d10ce.png)
![image](https://user-images.githubusercontent.com/74468064/136734381-91e7bfdd-5cbb-48d0-ac88-bb9aaa9bdef6.png)

**Comment by mootz12** [comment]
Thanks for the bug!

This has been patched. See https://github.com/script3/yieldblox-beta/issues/98
