### ISSUE TITLE
Collateral repayment issues, first one failed now seeing "No collateral balances"

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#257]
1. Trying to repay EURT with BTC. Received XDR error:

AAAAAgAAAADYzVxYWaMGsJRaucriVVovClrohNR4H/EsOakZQkMY9gAD96AAA6kTAAAArAAAAAEAAAAAAAAAAAAAAABhY7G/AAAAAQAAAAh5YnhSZXBheQAAAA0AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAACs6ayQVG6kiDAwegvI7GQg4aLHb9PZd9OLmAqbLHOY9gAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAANjNXFhZowawlFq5yuJVWi8KWuiE1Hgf8Sw5qRlCQxj2AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAS5K8wAAAAAAAAAQAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAA/54YOybMy4lHFlb+OQ0j3gQ8DwMqTx3ecQDPR/p1+KcAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADgAAAAJsMDBFVVJUAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAADxqJPYQAAAAQAAAAAAAAAANjNXFhZowawlFq5yuJVWi8KWuiE1Hgf8Sw5qRlCQxj2AAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAABAAAAAAAAAAAAAAAAAAAAAAmEBpzguHKqyy60NXLzOF08l2AyJXck6SXA+Bod2mEWAAAAAQAAAAAADIL8wAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAFQceA3kklutc092I2X1pwFvszMtCwAOx7iF3a8o7d4zAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwRVVSVAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAACVo2NneUAAAADAAAAAAAAAADYzVxYWaMGsJRaucriVVovClrohNR4H/EsOakZQkMY9gAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAABloQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAFFVVJUAAAAAAJzeF/C9WBrKZOa8fshst4LKwN+GK8GESrzd8CfQGU2AAAAAEZKXVgAAAABAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAAAAAAAgAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAEt6TkAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABRVVSVAAAAAACc3hfwvVgaymTmvH7IbLeCysDfhivBhEq83fAn0BlNgAAANkomns7AAAAAQAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAABEAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAACKHGgLZFzdHO/nY6UP3eo6i3kFvM1xQgwiut5n36Y4ngAAAAJ1MDBCVEMAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAACDA2xAAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAPfJmuPGPporE082oz1CxET26xHTPD9sWg/++qG03LdPAAAAAnUwMEVVUlQAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAARAIJ0AAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwRVVSVAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAPfJmuPGPporE082oz1CxET26xHTPD9sWg/++qG03LdPAAAAAAAAAAEAAAAAAAAAA3z8Ex0AAABAG5K572HtKBTsTQmShfV+tEKD8HCLfiuVbGyU5mAdOHeZTj0spjWGmksmhkgG/c+db5QbjPlG7tJWzOC1U130B0osVsIAAABAbcZ1i1W3a2P7Ffl4GoKzLLV4KOpPBSeIrJ5Qi4C/GrGKjmZL3iZteebDdPBrpXiEzi9zSz1M42Nyu+DYv9yOBEJDGPYAAABAsvS0uLw7KXcUBBK6pMd7hHSK0B/NbpOk2ZoRcFp1MiRog4fsHU1J+Xp/wqeuGzodqBw63nMIuZP4mbKkGbGODg==

2. Subsequent repayment attempts have "No collateral balances" error
![image](https://user-images.githubusercontent.com/11483548/136729987-a7c952e7-a56c-437d-8ebb-32f845cbb5f8.png)

BTC collateral still showing on my profile page:
![image](https://user-images.githubusercontent.com/11483548/136730324-26645c7d-1594-4cd2-8275-93a902030bf8.png)

**Comment by defj** [comment]
Update: Looks the the BTC collateral repayment may still have gone through eventually hence the missing collateral. Profile is missing the BTC now and EURT loan is reduced:
![image](https://user-images.githubusercontent.com/11483548/136735541-3a62c3cd-b635-4b58-9bd5-6b7a6df899ad.png)

**Comment by defj** [comment]
Same issue with repayment with 88 ETH :(

![image](https://user-images.githubusercontent.com/11483548/136735846-2cbefbb5-d4bb-43f6-9be1-693965daafd1.png)

AAAAAgAAAADYzVxYWaMGsJRaucriVVovClrohNR4H/EsOakZQkMY9gAEk+AAA6kTAAAArQAAAAEAAAAAAAAAAAAAAABhY8Y/AAAAAQAAAAh5YnhSZXBheQAAAA8AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAAcFetLug7sXaTpRA6nOMJe4XbGkiuhOiBbmItde6iyUAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAANjNXFhZowawlFq5yuJVWi8KWuiE1Hgf8Sw5qRlCQxj2AAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAANHO8EwAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAANjNXFhZowawlFq5yuJVWi8KWuiE1Hgf8Sw5qRlCQxj2AAAAAnkwMEVUSAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAB/YB8jAAAAAAAAAA4AAAACeTAwRVRIAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAH9gHyMAAAACAAAAAAAAAADYzVxYWaMGsJRaucriVVovClrohNR4H/EsOakZQkMY9gAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAABAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAADuOa8TN2Xri+9i0zytuxdmAdRKjgyytgRXBdXLIKP6ewAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMEVVUlQAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAADKagvAAAABAAAAAAAAAAA2M1cWFmjBrCUWrnK4lVaLwpa6ITUeB/xLDmpGUJDGPYAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAACYQGnOC4cqrLLrQ1cvM4XTyXYDIldyTpJcD4Gh3aYRYAAAABAAAAAAAMgvzAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAAGScE52XqMcokEj8qWglAbG+n1ykSTVHGVyr8Ya0g5y4AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADgAAAAJsMDBFVVJUAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAB9VYItQAAAAMAAAAAAAAAANjNXFhZowawlFq5yuJVWi8KWuiE1Hgf8Sw5qRlCQxj2AAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAABAAAAAAAAAAAAAAAAAAAAAIAAAABRVRIAAAAAAAm/Hr+did1Niqr/LIylIKKOluv+dfLo2q0RY7qILYT0gAAAAAAABHFAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAUVVUlQAAAAAAnN4X8L1YGspk5rx+yGy3gsrA34YrwYRKvN3wJ9AZTYAAAAAAMOX1AAAAAEAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAAAAAAACAAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAANHOq/AAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFFVVJUAAAAAAJzeF/C9WBrKZOa8fshst4LKwN+GK8GESrzd8CfQGU2AAACWF7V9fYAAAABAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAEQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAI5/uSuZx8KTY7FVjRUGglnnXgt3eVoXYIOombTaqwfKAAAAAnUwMEVUSAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAMte5kAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwRVRIAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAI5/uSuZx8KTY7FVjRUGglnnXgt3eVoXYIOombTaqwfKAAAAAAAAAAEAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAAD3yZrjxj6aKxNPNqM9QsRE9usR0zw/bFoP/vqhtNy3TwAAAAJ1MDBFVVJUAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAHdQvFQAAAAAAAAADSixWwgAAAEDaANhFow97w8AWGL11Azvo0PV6gOOtl30pe1CnDCD+4FDdnia/mQTAK6Ay2h5a4qIAMEZOBP4m2v4lvRntKywH+T1+uAAAAEBcP9AnAtfFEKX6BuB0goX/Atw1jlAYxb5M87NaQNS2EwCETI7XS7K15nCCHkWRUcVXTiT7IusLgUvVDWIHmNwCQkMY9gAAAEAY3UiGoU/3yrCtF80iX1JRiCf+711XcUXzVrpd9xf0Qmkg4MbQ0zjfeLuNKyDzFY2Nnq0NZ8TKB/2s6W7RCokM

**Comment by defj** [comment]
Health factor calculations are inconsistent, on the repay with collateral screen for 88 ETH repayment, health factor was supposed to return to 1.2 +, after it eventually went through despite reporting the failure above it is at 1.09 and the debt is still not fully repaid although 88 eth has bee deducted.

**Comment by mootz12** [comment]
HF calculations were wrong, and were patched last night.

Per the collateral "failure" issue, https://github.com/script3/yieldblox-beta/issues/204
