### ISSUE TITLE
There is a error when repay value higher than 1 BTC

### ISSUE THREAD

**Issue by minhtung1595** [script3/yieldblox-beta#259]
It's a bug when repay value higher than 1 BTC
https://user-images.githubusercontent.com/33053228/136732365-30d99062-de8c-40e4-8af8-2c6cb543cf84.mp4

**Comment by mootz12** [comment]
Hm, unsure what the root cause of this is.

We made some updates the the repayment modal, are you still having trouble?

My guess is you didn't have 1 BTC to repay at the time of repayment. This was a UX mistake that has since been resolved.
