### ISSUE TITLE
Current Borrow amount not synchronized

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#261]
I try to combine both Fixed interest rate with Float interest rate, i expect the current borrow amount is sum of both loan (306.58k USDC), but its only show the float interest rate amount (168.32k USDC).

![image](https://user-images.githubusercontent.com/91896561/136743803-186f1d3f-fd51-4410-a377-5a32b817c1f3.png)
![image](https://user-images.githubusercontent.com/91896561/136743796-45853606-a40f-47d3-96e3-0ae204d21c43.png)

Even i switch it to fix interest tab, its didnt changed
![image](https://user-images.githubusercontent.com/91896561/136744077-64f39915-de6a-4e46-af46-400c13effaed.png)

**Comment by mootz12** [comment]
There is an outstanding bug to clean up how we display market borrows.

See https://github.com/script3/yieldblox-beta/issues/213
