### ISSUE TITLE
Deposit Additional Collateral

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#262]
I dont know what should come when i turn on deposit additional collateral, i iexpect its probably show same thing with repay with another collateral, but its show nothing here.
![image](https://user-images.githubusercontent.com/91896561/136780522-3ae8f41d-5168-40e1-8ffa-c736df6f201c.png)

**Comment by mootz12** [comment]
This is working as intended.

It shows you everything you have lent, but not collateralized.
