### ISSUE TITLE
repay borrow with collateral

### ISSUE THREAD

**Issue by LorDDark6660** [script3/yieldblox-beta#263]
I repay EURT with BTC, BTC are gone, HF stay same...

**Comment by LorDDark6660** [comment]
Now i repay EURT with BTC again, btc are gone again, HF dont change, but show before 1.11->1.12, after this XDR still same

AAAAAgAAAAA0Uu+v4runt9Yl4Wi7Ae813aOWNAYAJUdZ6LFfDtJNvgAACWAAA6jXAAAA8gAAAAEAAAAAAAAAAAAAAABhZSggAAAAAQAAAAh5YnhSZXBheQAAAAwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAAIKJ7DjwEvRVWCD7AHNlMpLcSK2aoA0jNhimjdYqCIugAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAADRS76/iu6e31iXhaLsB7zXdo5Y0BgAlR1nosV8O0k2+AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAAdE5QAAAAAAAAAQAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAAmwxO9XOUN11Fb8H29T5tPVPnTs4n98TBPZc/0Kz2dHkAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADgAAAAJsMDBVU0RDAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAa+WgvdjQAAAAMAAAAAAAAAADRS76/iu6e31iXhaLsB7zXdo5Y0BgAlR1nosV8O0k2+AAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAABAAAAAAAAAAAAAAAAAAAAAIAAAABQlRDAAAAAAA1Ek02bEhKY4k7M1uIniJN5hg0JdWoXuxpOkwCDDa1cQAAAAAAAHjKAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAAYjmqngAAAAAAAAAAAAAAAgAAAAFCVEMAAAAAADUSTTZsSEpjiTszW4ieIk3mGDQl1ahe7Gk6TAIMNrVxAAAAAAAG0L8AAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAAXDiTkYAAAAAAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9+mOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAN//bMAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAEwAAAAJ1MDBCVEMAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9+mOJ4AAAAAAAAAAQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAnUwMFVTREMAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAN/5WoAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwVVNEQwAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAAAAAAEAAAAAAAAAA6NXssAAAABAI5Q9PWSlTqcxUIXEcXGPRjMSDPzX865yzBnIz8TuyhElPiExYoVZ6QwV6ecDWr25yoO8T2JE7Jv5ChgWue72CZShDZ0AAABA/Qji+1KrbdACNJAZIVApGw//FGYEs+Hy3V4rmBU8ZVFltnAmwo6ktaeehzB7/JBcER6v4QknlxDXS/5jlpcCDg7STb4AAABAFHYWuEGw+VmzCYmWqK7Dice9KM9b7iuZWszg7rVE8i7EvcP9/QZrNd7jxEgEsF5hiGBqcEo+ONA9yTCJljvQAg==

**Comment by LorDDark6660** [comment]
AAAAAgAAAAA0Uu+v4runt9Yl4Wi7Ae813aOWNAYAJUdZ6LFfDtJNvgAACigAA6jXAAAA9AAAAAEAAAAAAAAAAAAAAABhZaZBAAAAAQAAAAh5YnhSZXBheQAAAA0AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAABpZa6JaAkgufHqago0n51eCQJ3StXETtCOf3zcdq8fSgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAADRS76/iu6e31iXhaLsB7zXdo5Y0BgAlR1nosV8O0k2+AAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAABCwdfgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAADRS76/iu6e31iXhaLsB7zXdo5Y0BgAlR1nosV8O0k2+AAAAAnkwMEVUSAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAABwVd2/AAAAAAAAAA4AAAACeTAwRVRIAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAHBV3b8AAAACAAAAAAAAAAA0Uu+v4runt9Yl4Wi7Ae813aOWNAYAJUdZ6LFfDtJNvgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAABAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAA9WYqMqQq2uzYoS8Ch7BK9RgsUgSuYoitgNhYjA9NHXwAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAABog7JJ1OAAAAAwAAAAAAAAAANFLvr+K7p7fWJeFouwHvNd2jljQGACVHWeixXw7STb4AAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAFFVEgAAAAAACb8ev52J3U2Kqv8sjKUgoo6W6/518ujarRFjuogthPSAAAAAAAB4fsAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAAAXsEnpAAAAAAAAAAAAAAACAAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAABCpODQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAANoDmeskAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAABEAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAACOf7krmcfCk2OxVY0VBoJZ514Ld3laF2CDqJm02qsHygAAAAJ1MDBFVEgAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAAE603gAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAI5/uSuZx8KTY7FVjRUGglnnXgt3eVoXYIOombTaqwfKAAAAAnUwMEVUSAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAAAMCYAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAA78nXTQ0NaNI/TpXwvzB+m0Ms4zYdPVDrRoU1JSZxhosAAAACdTAwVVNEQwAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAA/XAZUAAAAAAAAAA6NXssAAAABAw0TkfIOUNzS/Lye1KtPMHwPod7XxamFSQ+/R6jnkRgJQBYPjrwgaq0ZrZaQGGseagy7UpeWeDw9dH4vg3wtNDpShDZ0AAABAOBYnDMt28SI/siLsBKTfbb1hNBA7Puiqcbb9ovq5i2YSTPRmRtvL1axMRg31PqVeBPX0emIhrXztQOmVC5iOAw7STb4AAABANhSL8C6Jw3RThH+CTOR/vK+Ix9SJteaTXQ+YhFx3m3y0rirGulZDLs0KzkGAY0zrtAkGvkR0veV0oS3XS3jcCA==
![a](https://user-images.githubusercontent.com/92062140/136982456-acfe4b1b-07d1-44ba-9dd2-d1455a764133.png)
![b](https://user-images.githubusercontent.com/92062140/136982462-ae4c5fed-376f-41d0-b35e-cf07ca1eb53c.png)

**Comment by mootz12** [comment]
The repay modal went through some heavy lifting.

Repay with collateral will not have a large effect on your health factor. You are removing collateral (which decreases health factor) to pay off liabilities (which increases health factor). It's mainly used as a way to de-lever yourself.

Please let me know if you are still having issues with this after the repay overhaul
