### ISSUE TITLE
[UI/UX] Additional option to check total fund that we can unstake at x date (suggestion)

### ISSUE THREAD

**Issue by yuminaai** [script3/yieldblox-beta#265]
I do staking for 1 year and 6 months. Firstly i do staking for 1 year and then stake for 6 months after. and at current UI it will show me the next unstake timing is the shorter time staked, that is 6 months later. so it show me be like this

![image](https://user-images.githubusercontent.com/92166874/136847229-c160ceba-d26d-4d0e-b28f-1fbb5f6ce1cc.png)

But the problem is, where the other fund go? how to check time to unlock the other staked fund? how to see other rest unlock schedule?

So i would suggest to you to add option to check them. example 

1. add option to check total fund that i can unlock until or at date 'A'

Example we lock for 2 ybx for 3 months and 3 ybx for 6 months. then if we set unlock check to 6 months, it will show 5ybx (2+3). and if we check for 4 month, it will show 2 ybx.

2. add option to check total fund that i can unlock between date 'A' to date 'B'

3. separate or make list each user doing staking. 
    so this is more transparance to user because we know our unstake schedule more details

imo, this is will help to manage staking strategy to user.
It is not good for users information if users are forgot when they do staking or if users do staking daily manualy, or users cannot remember how much ybx that users has staked until day A or until day B. so if you have this features, users can make better schedule for their investement strategy purposes for future.

**Comment by mootz12** [comment]
Thanks for the suggestion!

We have some ideas to make this information more clear for the user. I am going to close this to keep the issue tracker focused on beta issues, but your feedback has been noted.
