### ISSUE TITLE
[User experience] Default order of boxes in 'My positions'

### ISSUE THREAD

**Issue by maksiuu** [script3/yieldblox-beta#267]
Order of 'My positions' changes too slowly and causes confusion. It should be configurable (e.g. what order to use or refresh interval)
When I lower collateral on ETH, and quickly try to withdraw funds from the same positions, I see ETH in the same place. When I click on it, I see different coin and no funds available to withdraw. I need to close the window and look for new 'ETH box' location.

**Comment by mootz12** [comment]
It should be in the order order of your most recently modified positions.

We have received some feedback to make this more configurable.

Going to close this issue for now to keep the issues focused on bugs, but your feedback has been noted! Thanks!
