### ISSUE TITLE
HF minus When claim YBX

### ISSUE THREAD

**Issue by ygusmada** [script3/yieldblox-beta#270]
Today when i claim YBX, my healty factor was minus 0.01. Any issues?

**Comment by nixfreak** [comment]
Depends on your profile , lending , borrowing .

**Comment by ygusmada** [comment]
when claiming YBX
![IMG_20211013_192629](https://user-images.githubusercontent.com/28614308/137132130-e9dec888-231f-40a8-a472-788e6478a594.jpg)

After claiming YBX
![Uploading IMG_20211013_192613.jpg…]()

**Comment by ygusmada** [comment]
Before claiming YBX
![IMG_20211013_192629](https://user-images.githubusercontent.com/28614308/137132285-f5c0400c-b220-4167-ac50-c7872daaa369.jpg)

After Claiming YBX
![IMG_20211013_192613](https://user-images.githubusercontent.com/28614308/137132318-3daa1081-662e-46a9-8e60-817ddf321f3c.jpg)

**Comment by ygusmada** [comment]
2 days ago my HF was 1.21. yesterday was 1.20 with yellow green.. and today the colors is 1.20 with red colors..

Frst day, this issues didn't happen and happened 2 days ago

**Comment by ygusmada** [comment]
i think everyday it will decrease 0.01.. i will report and screenshoot it here

**Comment by mootz12** [comment]
That is likely. You are borrowing a LOT of assets, and you accrue interest. Interest rates are extremely high since people are borrowing hard with fake money.

Claim refreshes all of your liabilities, and ensures the interest on them is the most up to date.
