### ISSUE TITLE
Repayment with negative collateral amount

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#272]
1. UI allows negative collateral amounts to be entered during repayment with collateral.

eg Repay EURT loan with negative collateral amount:

![image](https://user-images.githubusercontent.com/11483548/136879756-22dc136e-8062-4f35-b4ef-a68cbefce301.png)

2. Contract builds then the following error is encountered:

![image](https://user-images.githubusercontent.com/11483548/136879988-5fd9c380-de69-41be-8fe0-d86284deef2a.png)

Should probably be prevented at step 1.

**Comment by mootz12** [comment]
Thanks! We are tracking a lot of our work to add input validation in https://github.com/script3/yieldblox-beta/issues/28
