### ISSUE TITLE
Unstaking negative amounts of sYBX

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#273]
1. UI allows negative number to be entered into as unstake amount
![image](https://user-images.githubusercontent.com/11483548/136880224-0a0289f2-0196-49a2-90ac-2247591dc6e5.png)

![image](https://user-images.githubusercontent.com/11483548/136880264-cc705b54-5ff3-48ee-8024-bd50a969d484.png)

2. Error received when building contract.

![image](https://user-images.githubusercontent.com/11483548/136880342-496ecc63-a373-4660-a7d6-af395be4a333.png)

Expect negative number entry to be prevented in step 1.

**Comment by mootz12** [comment]
We are tracking out input validation work here: https://github.com/script3/yieldblox-beta/issues/28
