### ISSUE TITLE
Validation of stake amount

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#274]
1. UI allows entry of stake amounts greater than those held by the account

![image](https://user-images.githubusercontent.com/11483548/136881128-e6f12be5-2e7d-415c-9bbb-05e50485dc27.png)

2. Confirm transaction
![image](https://user-images.githubusercontent.com/11483548/136881175-0e63fcda-c918-4bd9-9797-45d05a9d9322.png)

3. Submit transaction - Non descriptive error message
![image](https://user-images.githubusercontent.com/11483548/136881366-bac5a2aa-6652-4824-be83-c6185caaffd7.png)

XDR in error:
AAAAAgAAAADYzVxYWaMGsJRaucriVVovClrohNR4H/EsOakZQkMY9gAABXgAA6kTAAAAtgAAAAEAAAAAAAAAAAAAAABhZPTuAAAAAQAAAAp5YnhTdGFraW5nAAAAAAAHAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAALyL+Kvr4MyE/IGVkQ0Gf4Jtsu/Xt/fW75WLOqBh0LLYAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAADwAAAAAIKfsQoweNAhBtzSFwHqQZ9HphoULHjkg7vP0FMPl0tgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAANjNXFhZowawlFq5yuJVWi8KWuiE1Hgf8Sw5qRlCQxj2AAAAAVlCWAAAAAAAkWZA75T+uH68WcBdUf7MhiLHGH/QzgQgLIOWVnHYQ8cAAAAAfMk34wAAAAAAAAAQAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAAAAA4AAAABWUJYAAAAAACRZkDvlP64frxZwF1R/syGIscYf9DOBCAsg5ZWcdhDxwAAAAC4ZAHjAAAAAwAAAAAAAAAA2M1cWFmjBrCUWrnK4lVaLwpa6ITUeB/xLDmpGUJDGPYAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAJhAac4LhyqssutDVy8zhdPJdgMiV3JOklwPgaHdphFgAAAADAAAAAQAAAAUAAAAAAeGFWAAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAOAAAAAXNZQlgAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABFJYC1AAAAAMAAAAAAAAAANjNXFhZowawlFq5yuJVWi8KWuiE1Hgf8Sw5qRlCQxj2AAAAAwAAAAEAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAAAAAAAAAAACYQGnOC4cqrLLrQ1cvM4XTyXYDIldyTpJcD4Gh3aYRYAAAAAwAAAAEAAAAFAAAAAAHhhVgAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAEQAAAAAAAAADo1eywAAAAEBd7x4DhFAfRz0yg89ouK4W7eCm4tj+myoU2tEOCsZfhHLhfWH5B59DfiFBjrxkvndmDdKwv7aqiNJrRqhBKbcMlKENnQAAAEAEzm8AbCFHd7dCY02KXE6W4lse6Dp3HhChU8Zs2865upvUDY0bOgql/J572/h4OhNa3pudt5yqyKIoxWJ9mNkFQkMY9gAAAEAiM97jxGwB0SNzHegFD4tQ6c0DS+AMjXh4XGFmOmk2Yz4JXFa64PG49EmQ1dkogVr3Sn2lCcSEdZ+zz6eM+AwH

Should be prevented at Step 1.

**Comment by nixfreak** [comment]
You don't have any ybx to stake , according to the screenshot

**Comment by defj** [comment]
> 
> 
> You don't have any ybx to stake , according to the screenshot

That's the point of the issue, you should be prevented at step 1.

**Comment by mootz12** [comment]
We are tracking our input validation work here: https://github.com/script3/yieldblox-beta/issues/28
