### ISSUE TITLE
Repay issue?

### ISSUE THREAD

**Issue by BrightLigth** [script3/yieldblox-beta#275]
So I have been trying to repay my borrows. Difficult to see the proper way. Long story short what got deposited in my wallet is not what was accepted to be repaid. Where did the rest go, repaid with like kind so I would think it would show up in my wallet.
![BorrowEURTrepay2](https://user-images.githubusercontent.com/92237131/136882021-5f51c4dd-a521-4c20-8c02-2d5abe459f50.PNG)
.
![wallet](https://user-images.githubusercontent.com/92237131/136882163-b9a6ed2c-b98e-42db-9cd3-b199dae62cee.PNG)

.
should be 7k as it stands seems like you get screwed repaying.

**Comment by mootz12** [comment]
Could you explain more what you were trying to do?

A repayment is repaying a liability. You were given the EURT in exchange for the liability at the start of your loan. I wouldn't expect any assets to be returned to you unless you are burning additional collateral to cover your liabilities.

**Comment by BrightLigth** [comment]
So maybe I dont understand. I borrowed say 10k EU  I want to repay what was borrowed I choose repay select borrowed amount and try to repay both with collateral and without just a straight repay and both times failed or I lost (burned) my collateral. I used EU for repay and with collateral as well I had the extra in my account to repay. Just testing things out trying to grasp the concept. 
It could just be me but the repay feature if not intuitive and seems to be very buggy. I cant put my finger on it I should've made a video so you could see what I mean. Screen shots ain't doing it justice.
I will some more testing but it seem a lot of people aren't understanding the process or there is an few things that need to be worked out.
I dont know if the general crypto audience is going to be able to grasp. But maybe the institutions will be able to give better feedback. IMO Steep learning curve.
Very hard to de-risk and cash out once you start the cycle of borrowing and lending. Again it just might be me and my lack of understanding.
I'm just going to let it ride for a bit because I dont know how to get out. But I know that's what this is about testing and learning just there is a very step learning curve and you dont know if you did it right but a failure in a turret (error) kept you from it or you didnt get it right.
    On Wednesday, October 13, 2021, 05:52:25 PM CDT, mootz12 ***@***.***> wrote:  
 
 


Could you explain more what you were trying to do?

A repayment is repaying a liability. You were given the EURT in exchange for the liability at the start of your loan. I wouldn't expect any assets to be returned to you unless you are burning additional collateral to cover your liabilities.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by markuspluna** [comment]
This was mostly a UX issue with not being able to target different rates in repayments. Fixed now
