### ISSUE TITLE
[Documentation] Probably typo causing incosistent

### ISSUE THREAD

**Issue by starlog20** [script3/yieldblox-beta#277]
Other is written as 1,250 while only this one is writtern as 1,2500. probably it is typo to write more _zero's_ from other

![image](https://user-images.githubusercontent.com/92114001/136927146-407efff3-01d2-462a-8b44-ef2dd1d98f11.png)

link to docs : https://docs.ybx.script3.io/user-docs/ybx-tokens

**Comment by mootz12** [comment]
Oops. Thanks!
