### ISSUE TITLE
Able to load other contracts to the Script3 turrets

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#278]
I was able to load the following new txFunction contracts to one of the script3 turrets (T_GBE5M7ZQ5XRBFDNXS53UBQA3P4DAQWUCY2PJSGH5Z5O5VR6RBE43Z4FN): 

Contract that doesn't do anything as the parameters are missing
{
  "hash": "fa47ed7a7172a242b35d4a2af57659bc1df70fadffc07fb37f3ecc2a1d486539",
  "signer": "GC54DUIQQBL7JFVYMZF4TBTWVPNICOE6XPSJTBBNX6BBHFNABSL75NT5"
}

Basic payment contract with source and destination
{
  "hash": "ba0e4c861129fce86a204eb5cc6a04d57d04c675a07d25da6b763547d2175b96",
  "signer": "GCUMXBUQQBSO63EWS5JDJVYQAHWWEVM6XPHTCFD5B6Y52YGYH44BMRQB"
}
https://stellar-turrets-testnet-3.script3.workers.dev/tx-functions/ba0e4c861129fce86a204eb5cc6a04d57d04c675a07d25da6b763547d2175b96

I was also able to run the basic payment contract producing the following XDR:
AAAAAgAAAABo1zzgxhy3/KRpTcmjtNbNrYS27S0wJqmq9wA3bPm98AAAAGQABsUYAAAABQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAADYzVxYWaMGsJRaucriVVovClrohNR4H/EsOakZQkMY9gAAAAAAAAAAAJiWgAAAAAAAAAAB2D84FgAAAEDvVDHa0FxbFnKZT8rmMWGjGzzuKZ4BzdYrUVPVT82rp/ioEtSM0Xkx8tE2kgQhhZcpvWnsXn4Lm2+qmPW2Xh8A

Which I submitted to the network successfully once I had added GDYZ5WKDUWDI6LS67YPKZWBXAQJVHPXO4RQFCOBACZIA4KXNDBSIF4QB as a signer to the source account:

https://testnet.steexp.com/tx/18061881d2f4e05b624c7c06e0a2b18be336767dcfa0381e62e1797605aa34ec

Not sure if letting other contracts be loaded can be prevented but seems like a security risk. eg I could create a "liquidate" contract that instead does other operations

https://stellar-turrets-testnet-3.script3.workers.dev/tx-functions/ba0e4c861129fce86a204eb5cc6a04d57d04c675a07d25da6b763547d2175b96

**Comment by hanseartic** [comment]
It's not a problem, because the contract only runs when invoked. You can not replace existing contracts either. So it's just your code being available on the turret. Also uploading a contract returns a signer key. This key needs to be added to the account that you want to have managed by the turret as a signer.

**Comment by defj** [comment]
Confirmed that this is expected behaviour.
