### ISSUE TITLE
Potition Value Bugs ?

### ISSUE THREAD

**Issue by sundaymorking** [script3/yieldblox-beta#279]
**This problem occure yesterday, try to refresh the page, nothings.** 
_GC2JOHKGU6SIQZYQSXZDGBGIHWKFLN6R63VAAGMWV5N2YNSR25F7YRN3_

There's one position that shouldn't be here ,the value is **$0** (so im not borrowing anything) but this one is loaded in my position that i've borrow eth token (it shouldnt here coz the value is **$0**)

check this out ,try to repay it with "**MAX**" repay amount its show **1 ETH** ,lets try to repay with **ETH Collateral** (i have enough Collateral for sure) .. and here we go.

![morepicture](https://user-images.githubusercontent.com/90993539/136978364-990a982a-9981-49dd-b324-3cad07d042e4.png)

![mypotition](https://user-images.githubusercontent.com/90993539/136976980-7b19c2c6-7463-498c-bcf8-b32e5b0fefac.png)

![borrowvalue0](https://user-images.githubusercontent.com/90993539/136975496-87e2bf6b-b077-44a7-b0f6-46f4c9bc3aa0.png)

![trywithCollateral](https://user-images.githubusercontent.com/90993539/136975986-3a8f981b-3bc7-4ca2-a991-5dbdd826ca65.png)

![repay](https://user-images.githubusercontent.com/90993539/136975575-1c7f196d-41cc-4c41-91de-1a97197e8819.png)

![error](https://user-images.githubusercontent.com/90993539/136975600-86721b14-75a4-47c0-b2ab-ef9e9c409297.png)

**Comment by mootz12** [comment]
The repay modal went through a lot of updates recently. It appears that an underlying issue with repayment event is what caused this.

Please let me know if you are able to reproduce this. Closing for now.

**Comment by sundaymorking** [comment]
> The repay modal went through a lot of updates recently. It appears that an underlying issue with repayment event is what caused this.
> 
> Please let me know if you are able to reproduce this. Closing for now.

hello this is happens again with another pair "USDC", very annoying if the bug is not fixed when mainnet launches.
