### ISSUE TITLE
[UI/UX]  Restrict First Character Zero in Input Field in All Place that Allow to Input Data

### ISSUE THREAD

**Issue by yuminachan** [script3/yieldblox-beta#280]
I think allowing to input many zero number before real number is annoying and unsightly. here for example :

![image](https://user-images.githubusercontent.com/92166874/136986459-2b67a595-d075-4aab-9c98-6661cef1d335.png)

![image](https://user-images.githubusercontent.com/92166874/136988700-2d71a12d-f0e0-4940-9a7c-684330ba521f.png)

![image](https://user-images.githubusercontent.com/76908558/136997488-a7807ed7-7335-4d8e-9965-aecfb905d397.png)

So, imo better to make input data rules that can restrict first character zero in input field. it can make your data input more neat from unneeded number.

**Comment by mootz12** [comment]
We appreciate the feedback. Work is going in to add numeric filters. I'll tag this as a duplicate, and make a note of it.

https://github.com/script3/yieldblox-beta/issues/28
