### ISSUE TITLE
Can't update (reduce) collateral

### ISSUE THREAD

**Issue by asriqul** [script3/yieldblox-beta#282]
i try to withdraw my EURT lent but i need to change my collateral first. and when i confirm the transaction it always failed. is this happening because my Health Factor is at 1.1? but this only happened today, a few days ago, I was still able to change my lent collateral even my health factor was below 1.08
![ybx first](https://user-images.githubusercontent.com/46532231/137040738-35cdfccb-31be-42b2-91f9-5bbbf2af6d48.png)

even when I reduce it a few percent it still fails.

![ybx second](https://user-images.githubusercontent.com/46532231/137040822-b00547a8-04c1-4ec7-9ba4-6769c6732746.png)

**Comment by mootz12** [comment]
Yes, you can't put your health factor below 1.1

I am unsure if there was an issue a few days ago, there were some bugs with HF that have been resolved.
