### ISSUE TITLE
[UI/UX] Net APY Text Overlapping on Account Overview

### ISSUE THREAD

**Issue by starlog20** [script3/yieldblox-beta#284]
Still related with #56 but now after new patch, the overlapped happen to the Net APY. I use Google Chrome v94.0.4606.71

![image](https://user-images.githubusercontent.com/92114001/137069725-7b958dd0-2d31-41f2-978a-75cd79654191.png)

**Comment by starlog20** [comment]
But when i open it at Firefox it is normal

![image](https://user-images.githubusercontent.com/92114001/137069954-93d65b2c-641b-416c-b619-9fd116401d82.png)

**Comment by mootz12** [comment]
There does appear to still be a minor visual bug. Good catch!
