### ISSUE TITLE
Error calculation on sYBX amount

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#286]
I dont really sure its an error or not, but with a simple logic if 1.5x earn 1.5 sYBX, 1.0x would earn 1.0 sYBX and 0.8x would earn 0.8 sYBX.

![image](https://user-images.githubusercontent.com/91896561/137045752-736ce59c-5539-406a-845a-8557e08e8433.png)

**Comment by starlog20** [comment]
1 ybx * 1/4 years * 0,8 multipier = 0.2

**Comment by f0xie7** [comment]
It just clarrified that sYBX amount = YBX * APR * LOCK PERIOD.

**Comment by starlog20** [comment]
ok if we use your fomula then

1 YBX * 0.8x APR * 1/4 years lock period = 0.2 sYBX

**Comment by f0xie7** [comment]
Yes i know already

**Comment by mootz12** [comment]
It appears this calculation is correct.
