### ISSUE TITLE
Can't claim ybx reward

### ISSUE THREAD

**Issue by kotakhie** [script3/yieldblox-beta#287]
I can't claim ybx.
![Screenshot_2021-10-13-07-05-10-287_com kiwibrowser browser](https://user-images.githubusercontent.com/91866608/137046588-ce90fdf8-1853-45a8-80b1-a1096f08011f.jpg)

**Comment by reigister** [comment]
refresh and try again

**Comment by mootz12** [comment]
The token can be cached. If this is still occurring after refreshing, let me know.
