### ISSUE TITLE
Difference of Net APY & Token Yield

### ISSUE THREAD

**Issue by coolrobiul** [script3/yieldblox-beta#288]
**Net apy & token yield increased a little bit after YBX claim.
But after staking or after some time net apy nearly 50% down & token yield as like as before YBX claim.**

**Before YBX claim**
![Screenshot_2021-10-13-06-12-16-97_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/59414838/137050377-aac59fbb-ff2a-4667-a9b1-feb2be58ea83.jpg)

**After YBX claim**
![Screenshot_2021-10-13-06-16-59-87_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/59414838/137050453-2c071262-7f2a-4fdc-a893-e5c04d8796b5.jpg)

**After Staking YBX**
![Screenshot_2021-10-13-07-03-14-34_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/59414838/137050516-53bbaef4-13e3-4860-8c05-e45cddec9c2a.jpg)

**Comment by mootz12** [comment]
I believe this was an issue with our pricing bot. Please let me know if this issue continues to happen.

**Comment by coolrobiul** [comment]
Today token yield changed again a little bit

![IMG_20211016_082600](https://user-images.githubusercontent.com/59414838/137570066-d0558776-5649-495e-ab6b-5ec78ab7df59.jpg)

![IMG_20211016_082432](https://user-images.githubusercontent.com/59414838/137570080-594703d7-b7e0-423b-b865-214fb01852f6.jpg)
