### ISSUE TITLE
I cannot repay borrowed amount with collateral

### ISSUE THREAD

**Issue by cryptodmc771** [script3/yieldblox-beta#289]
XDR code:
AAAAAgAAAAAJZRTzeaar/k9ZHgTBQycFJxyDEAma7oITwh/5cEmFHAAACigAA6c3AAAAegAAAAEAAAAAAAAAAAAAAABhZkI8AAAAAQAAAAh5YnhSZXBheQAAAA0AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAABi+ez2vrcyyuVIoSzxLC9/7pTX0d/yGtVNwpUVSD/zVgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAAllFPN5pqv+T1keBMFDJwUnHIMQCZrughPCH/lwSYUcAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAB0P2g0AQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAAllFPN5pqv+T1keBMFDJwUnHIMQCZrughPCH/lwSYUcAAAAAnkwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAPS/E45HAAAAAAAAAA4AAAACeTAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAA9L8TjkcAAAACAAAAAAAAAAAJZRTzeaar/k9ZHgTBQycFJxyDEAma7oITwh/5cEmFHAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAABAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAAkkQtzuvzh8peCHd4wVm8CXvOTnDSdXHW+QBB472Ff8wAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMEVUSAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAIQuxdAAAAAwAAAAAAAAAACWUU83mmq/5PWR4EwUMnBSccgxAJmu6CE8If+XBJhRwAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAAAqu4nkAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABRVRIAAAAAAAm/Hr+did1Niqr/LIylIKKOluv+dfLo2q0RY7qILYT0gAAAAAAAMNPAAAAAAAAAAAAAAACAAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAAiiIW5QAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFFVEgAAAAAACb8ev52J3U2Kqv8sjKUgoo6W6/518ujarRFjuogthPSAAAAAAAJ3WQAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAABEAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAADvyddNDQ1o0j9OlfC/MH6bQyzjNh09UOtGhTUlJnGGiwAAAAJ1MDBVU0RDAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAEuf/tgAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAATAAAAAnUwMFVTREMAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAADvyddNDQ1o0j9OlfC/MH6bQyzjNh09UOtGhTUlJnGGiwAAAAAAAAABAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAjn+5K5nHwpNjsVWNFQaCWedeC3d5Whdgg6iZtNqrB8oAAAACdTAwRVRIAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAAQEIs0AAAAAAAAAA1fgHm0AAABAS/pAwfNf0gkFLCKoJKdkxU1ZYhTGP8AAvj3HNlLAzxqKqZg9CQ8GUOiEG4d6rg0aVV/uBq3eaE34SPVmGteeAptQdfMAAABAinky3ulBFBUFOIRlcuhpbJmbtBdhRB6a6NE8dnh86kUgv+9Xi/GBxpQlgJatIuCMZ5tUTFSxOuDCXOS3Jf+2AHBJhRwAAABA74MHHTXg6TKkz08quZhSPfheI3cYjysL3OsWVuSKjoD6uRuggN3lmYht+gTFMp8OehZRgJgKWaCGAR/3LTCqAg==

**Comment by mootz12** [comment]
The repay modal was updated recently. Please let me know if you are still having issues.
