### ISSUE TITLE
Failed to generate token when depositing BTC for lending

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#29]
Depositing 1 BTC to lend failed at last step with the following error:

![image](https://user-images.githubusercontent.com/11483548/136294679-2d4088a1-d0ac-432b-ad39-93409a4ae90e.png)

Transaction to create claimable balance was successful:
https://stellar.expert/explorer/testnet/tx/16331d5022e2c68d4ff4969b9afaaf5b0e72ea9a184ce839e1db9513d164cefc

**Comment by drew-boy** [comment]
duplicate clearing
