### ISSUE TITLE
Amount YBX move automatically when try claim and reject and try to lend or borrowing.

### ISSUE THREAD

**Issue by reigister** [script3/yieldblox-beta#290]
I try to claim my YBX total 193.44 but i change my mind, so i reject this.
like this picture 1
![try claim ybx](https://user-images.githubusercontent.com/78670969/137052363-5c275b44-6234-4517-9fbf-21e7d1b202c4.png)

when i click reject, it show error message (It is already right process) 
I borrow some EURT 
i forgot take SS
i refresh the page and 
the protocol still process the first step when i claim ybx.
but not full only 87.82 YBX

Like this picture 2
![try claim ybx2](https://user-images.githubusercontent.com/78670969/137052384-64dacb19-126a-436a-bd2d-3fdb44edef2a.png)

i try to reproduce the bug and it happen.
check this step by step
i try to claim again
the picture 3 show like this 
![try claim ybx3](https://user-images.githubusercontent.com/78670969/137052434-c9d49a5c-29f6-4753-aa15-5a4eecfd9e89.png)

and reject it (picture no 4)
![try claim ybx4](https://user-images.githubusercontent.com/78670969/137052459-dfcf51c6-33b5-4a3c-b591-1ee72e955e62.png)

after that my YBX status 
YBX already claim = 87.82, still can claim = 105.63 YBX

after that i lend some ETH around 4,36 ETH
picture no 5
![try claim ybx5](https://user-images.githubusercontent.com/78670969/137057271-be03bd5a-3fa2-475e-89a8-b664c59bf2d3.png)
i refresh the page and 
the protocol still process the second step when i claim ybx.
and YBX already claim change from 87.82 to 157.71, still can claim = 35.74
picture no 6
![try claim ybx 6](https://user-images.githubusercontent.com/78670969/137057456-a36d76ac-4205-4633-937e-f484798da1af.png)

I try to claim the remaining YBX (35.74) and all YBX already claimed
picture no 7
![try claim ybx 7](https://user-images.githubusercontent.com/78670969/137057857-f832dd41-f666-4d48-afd2-1ef09da79998.png)

**Comment by markuspluna** [comment]
Looks like a small refreshing issue on the front end. When you touch your balances (lend or borrow) it claims any pending YBX associated with those balances so the claims look normal

**Comment by mootz12** [comment]
This looks to be working as intended.

You were able to fully claim the amount that was quoted to you before, but you did it manually.
