### ISSUE TITLE
Using max "deposit additional collateral" and max "borrow" takes HF too low and doesn't allow transaction

### ISSUE THREAD

**Issue by trossw1818** [script3/yieldblox-beta#291]
Currently unable to use the max borrow and max "deposit additional collateral" together. It over-borrows, takes the HF too low and won't be able to submit. 

![YBX 14](https://user-images.githubusercontent.com/92266225/137058341-9a2dc04b-5b0c-46c7-9e10-a82ed1bf7ff0.JPG)

**Comment by mootz12** [comment]
Yes, the repay modal was recently refactored.

This should be fixed now. Let me know if you are still having issues.
