### ISSUE TITLE
The probelm of Repay

### ISSUE THREAD

**Issue by jakathei** [script3/yieldblox-beta#292]
When I making Repay instead of deducting from Borrowed and Lent.which in the end only deducted from the lent.Make to Health factor reduced.
Before I repay
![beforre repay](https://user-images.githubusercontent.com/92008056/137059392-4ea5b4f1-a59e-44cc-a321-c1ea25531106.png)

Repay with ethereum

![repay](https://user-images.githubusercontent.com/92008056/137059433-e3469e95-1c2e-47ba-a27e-d3fdb46d54b8.png)

After Repay
 
![after repay](https://user-images.githubusercontent.com/92008056/137059475-3ebc941b-c8b7-42d9-ae34-cf6090b1f374.png)

That is, I have paid the debt but the debt is not reduced

**Comment by mootz12** [comment]
Can you check if your specific borrow liability went down that you attempted to repay?

**Comment by jakathei** [comment]
My borrowed din't change , just my lent change.The Repay transfer to main banlance for deposit

**Comment by markuspluna** [comment]
I believe this was the repayWithSameAsset bug. It was reported elsewhere and is now fixed
