### ISSUE TITLE
Cannot repay ETH, clicking "max" returns no value and gives NaN error

### ISSUE THREAD

**Issue by trossw1818** [script3/yieldblox-beta#293]
I currently have Eth 85% collateralized so there should 6.38 ETH available to repay loan 

![YBX 15](https://user-images.githubusercontent.com/92266225/137059814-bf52372f-e5ed-444e-b0bc-d253cd0d0d30.JPG)

When trying to click max repay, expecting ~6.38 to populate it changes to " -- " but the "remaining borrow balance" goes from 37.2 ETH to displaying NaN

View before clicking max repay:

![YBX 17](https://user-images.githubusercontent.com/92266225/137060246-a25585fe-fbfb-4736-afc6-2ff618929a7e.JPG)

View after I click the max repay button:

![YBX 18](https://user-images.githubusercontent.com/92266225/137060337-3f097b36-c371-460d-a58c-4baae57840f5.JPG)

**Comment by mootz12** [comment]
You do not have any ETH in your wallet. See `Available to Repay`
