### ISSUE TITLE
Error while YBX claim

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#295]
I got this error message popup while claiming YBX for today : 
![image](https://user-images.githubusercontent.com/74468064/137061437-895a7ef3-091c-465a-9c8c-56a212dd283d.png)

It showed this error twice after refreshing, the claim was successful after the third time. 
Full screen-recording : https://drive.google.com/file/d/14NrPWcqKrReEMq7g9wr6gncrPq1vWZLO/view?usp=sharing

**Comment by mootz12** [comment]
Cloudflare is pretty weird with what they cache. We released a new contract around the time this bug was released, so I assume that played a role.

Sorry about that!
