### ISSUE TITLE
Problem with Repay EURT

### ISSUE THREAD

**Issue by vominhtri1611** [script3/yieldblox-beta#296]
I am doing to Repay EURT
My wallet have 196k EURT

Now I want to Repay 100k EURT (All my Remaining Borrow Balance ~342k EURT). And transaction completed.

The Remaining Borrow Balance should went down 100k EURT (342k -> 242k), but it just went down 1,7k EURT (342,73k -> 341,02k)

Here is the screenshot: My wallet, Repay -> transaction completed -> the result not like my expect
![image](https://user-images.githubusercontent.com/36155515/137095076-6685c0f3-4c24-47af-883e-1d4cb1cc396d.png)
![image](https://user-images.githubusercontent.com/36155515/137095257-209a1671-ebd9-43de-bd4c-893f4179a03f.png)
![image](https://user-images.githubusercontent.com/36155515/137095588-f29b374d-b958-4869-b546-c694209aadf5.png)
![image](https://user-images.githubusercontent.com/36155515/137096381-106dc369-a3d4-484a-a678-7f435027594c.png)

**Comment by mootz12** [comment]
This bug was my fault during the Repay Modal refactor. It has been fixed. Thanks for documenting it!

**Comment by vominhtri1611** [comment]
My identify: @mootz12 
Email linked to my Beta account: vominhtribl1611@gmail.com
YieldBlox Testnet Beta public address: GBBT4QKA3EQ3RYXV54BVWILK6XCDG3SXSR63HR3LYBZM4COGEW53GQKE
