### ISSUE TITLE
EURT repayment issue - Transactions not going through

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#297]
I tried repaying EURT with both held assets and collateral assests but none are going through. 

 
![image](https://user-images.githubusercontent.com/74468064/137104863-8471bf86-b3df-405c-95f9-ca6420af6d69.png)
![image](https://user-images.githubusercontent.com/74468064/137104868-1c6150d7-c038-42cb-8b09-b4bf9d88f629.png)
![image](https://user-images.githubusercontent.com/74468064/137104885-bf34b6ea-7676-4780-a645-a926d150e387.png)
![image](https://user-images.githubusercontent.com/74468064/137104904-c8e2f8b9-1653-4a24-8db2-1731567b2e00.png)
![image](https://user-images.githubusercontent.com/74468064/137104920-d27256dc-5484-44c0-91b6-7265ad16d222.png)
![image](https://user-images.githubusercontent.com/74468064/137104931-2c9e2332-b47c-445a-a7a6-df1ec891eb89.png)
![image](https://user-images.githubusercontent.com/74468064/137104969-5cbb13ad-a223-4390-ba3d-65ac162fa61d.png)

**Comment by arnob016** [comment]
Here's the screen recording for the process
Drive link: https://drive.google.com/file/d/14QsP1NDRt0HHEZPgYwx9dvMjdXTa-St7/view?usp=sharing

**Comment by arnob016** [comment]
Error XDR code : AAAAAgAAAADkzI7f6TOEPoHBB/g4v7Lt3Q40ItpYleDP7gDFNlS/ugAACigAA6dBAAABYgAAAAEAAAAAAAAAAAAAAABhZqxnAAAAAQAAAAh5YnhSZXBheQAAAA0AAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAC5Qs0Y342ZsZAURAo2pMy8NiG9KCg9K+ksxU9uV4U6/wAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAOTMjt/pM4Q+gcEH+Di/su3dDjQi2liV4M/uAMU2VL+6AAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAACFg7NQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAOTMjt/pM4Q+gcEH+Di/su3dDjQi2liV4M/uAMU2VL+6AAAAAnkwMEVUSAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAABpXUCaAAAAAAAAAA4AAAACeTAwRVRIAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAGldQJoAAAACAAAAAAAAAADkzI7f6TOEPoHBB/g4v7Lt3Q40ItpYleDP7gDFNlS/ugAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAABAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAACLb/9kCeQC3AoM4tBVE5PIlDcSjMBDucsAfjXa8jvC9wAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMEVVUlQAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAF7+aKBHAAAAAwAAAAAAAAAA5MyO3+kzhD6BwQf4OL+y7d0ONCLaWJXgz+4AxTZUv7oAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAFFVEgAAAAAACb8ev52J3U2Kqv8sjKUgoo6W6/518ujarRFjuogthPSAAAAAAAAABIAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABRVVSVAAAAAACc3hfwvVgaymTmvH7IbLeCysDfhivBhEq83fAn0BlNgAAAAAAAMNPAAAAAQAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAAAAAAAIAAAABRVRIAAAAAAAm/Hr+did1Niqr/LIylIKKOluv+dfLo2q0RY7qILYT0gAAAAAACqaqAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUVVUlQAAAAAAnN4X8L1YGspk5rx+yGy3gsrA34YrwYRKvN3wJ9AZTYAAAAAejJU3AAAAAEAAAABVVNEQwAAAAAIHZ5AtGqFkj6fWsv2oHzVx73aCBe/njojqIV33zJKRwAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAARAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAjn+5K5nHwpNjsVWNFQaCWedeC3d5Whdgg6iZtNqrB8oAAAACdTAwRVRIAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAARrJB0AAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAAD3yZrjxj6aKxNPNqM9QsRE9usR0zw/bFoP/vqhtNy3TwAAAAJ1MDBFVVJUAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAAG0JT9wAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAATAAAAAnUwMEVVUlQAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAD3yZrjxj6aKxNPNqM9QsRE9usR0zw/bFoP/vqhtNy3TwAAAAAAAAABAAAAAAAAAANX4B5tAAAAQMa064tqaRn/vreXsDJyvWB5cEDIBS24KGl0bRcPgKr/dThkPfSbA1GpXzzNt5RUwlH+3JMzXJr02r11CQ4oTAKbUHXzAAAAQKX/KxLo3xpNQRy+2sBZ1CoHfwwmiUCgybYW7Q55flg2BExCtntWVvS46OReUoKpA7ejXP8uduQZocmd2YLodgs2VL+6AAAAQFGecu8jPJft8WhKXGo42Z5Hpw0l/sapVeCm55kRLNeYtagCVVdovPQ007gG3DYLHLxFfALnU5dSgxKS/VSiLgw=

**Comment by mootz12** [comment]
I think this is related to a bug I introduced last night. See https://github.com/script3/yieldblox-beta/issues/296

If this is still an issue, please let me know.
