### ISSUE TITLE
ETH repayment issue - Transaction going through, but only 1.69 ETH gets paid. 

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#298]
This is a sequel to issue #297 .
I'm trying to repay ETH now. 

![image](https://user-images.githubusercontent.com/74468064/137107161-08f3655e-eea8-427b-b747-cf2584d10212.png)
![image](https://user-images.githubusercontent.com/74468064/137107231-04ede4ee-fa8b-46e5-b61a-f1f9cd9bd0e9.png)

 My HF is supposed to go from 1.11 to 1.15
But my full repayment isn't going through and health factor doesn't change as it said.

After 10 minutes:

![image](https://user-images.githubusercontent.com/74468064/137107543-937c2bd8-a08c-49e0-bf45-0e5815821ed7.png)
![image](https://user-images.githubusercontent.com/74468064/137107577-a91ac285-7cce-44d1-af7e-1a962b34dd5a.png)
![image](https://user-images.githubusercontent.com/74468064/137107598-a0753869-982e-42b9-908d-96ce978f8e15.png)

**_In a nutshell_**
I tried paying 12 ETH
Only 1.69 ETH was paid as repay, but 1.61 ETH was cut from my account (Where did that 0.8 ETH come from!)
Health factor didn't change as intended.

**Comment by arnob016** [comment]
Edit 1: 

I paid 1.69 ETH 4 times. Now the whole amount is back with the repayment.


Before : 
![image](https://user-images.githubusercontent.com/74468064/137112468-068bf91c-e8ee-4909-a7f3-020664ea7265.png)

Now:
![image](https://user-images.githubusercontent.com/74468064/137112128-b8672b3d-43c6-442d-a477-30910170de01.png)

**Comment by mootz12** [comment]
Likely the same issue as - https://github.com/script3/yieldblox-beta/issues/296

Please let me know if this is still an issue.
