### ISSUE TITLE
USDC loan display error

### ISSUE THREAD

**Issue by binhkieu** [script3/yieldblox-beta#300]
The Borrow section of My Profile shows a USDC loan of zero value. I repaid but the system gives an error
![2021-10-13_175104](https://user-images.githubusercontent.com/36544627/137120880-e83919e5-6e10-4a1a-a0c8-362c83de9bb2.jpg)
![lỗi hiển thị 2](https://user-images.githubusercontent.com/36544627/137120896-639da7fd-cf18-4102-ace3-23c8b9d0cd7e.JPG)
![lỗi hiể](https://user-images.githubusercontent.com/36544627/137120911-07cc780c-d8e4-468c-acba-a79345459d36.JPG)

.

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/32
