### ISSUE TITLE
Inputing an infinite value on manual repayment amount causes display error and crash

### ISSUE THREAD

**Issue by theboycoder** [script3/yieldblox-beta#301]
On the repayment loan with collateral screen if an infinite amount of value is added it causes frontend issue with the display, but when the number value key between 0-10 is added and held the display gets pushed off screen until the frontend cant display it anymore and the page crashes. 

![crash 1](https://user-images.githubusercontent.com/45983304/137174371-1dbce0aa-dba1-47ee-9903-c930def3a6c9.png)

![crash 2](https://user-images.githubusercontent.com/45983304/137174375-7ee5a1f5-5200-4de6-b81e-c1ddf3d95bdb.png)

**Comment by starlog20** [comment]
this issue is related with #175

**Comment by mootz12** [comment]
See comment above
