### ISSUE TITLE
Error Message after every transaction

### ISSUE THREAD

**Issue by Nathanofzion** [script3/yieldblox-beta#303]
For example when trying to claim YBX, it you get the error below:

"Something went wrong!
Unable to complete your request.

Majority of turrets failed to execute contract. Not authorized to run contract with hash acf7062f9389878e2001e184bf91b338ad30cb5a0dbf6df88c0ca1fac6bbc158"

It try's to build the transaction then fails. I also tried to Lending eth and btc but looks like the same issue error message (abit confusing). Checked StellarExpert both say successful tx's (btc={Transaction: e5aa336c1b7cad70f22bc71bb62ee9e12b23f6e5378405a3fae28c61a3c6fe65}, eth={Transaction: 9f3443be557775559e65d32794bc7007f3c8c1b67ded5131f59811681af9a523}. What confusing however is the memos say  srry - asset refund.

So not sure if the function was completed, as I expect to see a deposit in the current deposit Colum; and also would have thought my claimable YBX would show in the YBX value of the Staked YBX module. 

![Same error code on every tx](https://user-images.githubusercontent.com/38050940/137201598-0e330af0-ca4a-48a2-bd2b-0b61657b453f.PNG)

![Current despit no show- account balance no change](https://user-images.githubusercontent.com/38050940/137201350-40e4ee28-45f5-47e2-9c66-97716c66169b.PNG)
![See history payments sent](https://user-images.githubusercontent.com/38050940/137201354-2fd7b2bc-d7f3-4c57-a91b-8b5d3fe30739.PNG)

**Comment by mootz12** [comment]
Have you refreshed your browser recently?

That looks like an old contract hash. We will work on making the token refresh process a bit more seamless.

**Comment by Nathanofzion** [comment]
Yes after refresh, everything so far seems to be working. I'll be sure to advise if any other issues.
