### ISSUE TITLE
[Repayment] Failed to do repay with multi colleteral

### ISSUE THREAD

**Issue by starlog20** [script3/yieldblox-beta#305]
This error is  happen when i do repay with multiple colleteral.

Here step to get this error

1. open repayment and input repayment with multi collateral payment. example be like this

![image](https://user-images.githubusercontent.com/92114001/137215729-9e777590-ea31-4514-b106-6b27f77865b7.png)

2. then click repay and i will get this confirmation notif

![image](https://user-images.githubusercontent.com/92114001/137215884-9b654a9e-eb1e-4a9e-8fda-d0e6ddcecd89.png)

3. then let it loading for building transaction then you will found this error before approving transaction

![image](https://user-images.githubusercontent.com/92114001/137215978-bbf61914-af77-4ae3-896e-69248543ac47.png)

**Comment by starlog20** [comment]
probably related with this issue #209

**Comment by markuspluna** [comment]
This was actually probably the repaying with same asset bug, it was reported elsewhere and has been fixed
