### ISSUE TITLE
Fixed Interest Rate is not Fix rate

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#306]
I do borrow when the Fixed Rate is ~32%, but its keep reaching until ~40%. So, what the point of Fixed Rate?
![image](https://user-images.githubusercontent.com/91896561/137223007-21471a7d-8ce0-4eaf-9886-6d38663c4286.png)

**Comment by defj** [comment]
https://github.com/script3/yieldblox-beta/issues/213

**Comment by mootz12** [comment]
The display rate is incorrect
