### ISSUE TITLE
Swap betwen YBX

### ISSUE THREAD

**Issue by LorDDark6660** [script3/yieldblox-beta#312]
it is possible to swap between ybx and others asset now? or is it bug?

![Bez názvu](https://user-images.githubusercontent.com/92062140/137315475-3cb95c30-807f-4398-92aa-44a51920aa70.png)

 tx confirmed

6d1523b30c3c0c86a881055ec6949365a61e62953eb692488bfc475e9dee38b6

**Comment by arnob016** [comment]
I'll just go sleep 🐸 
![image](https://user-images.githubusercontent.com/74468064/137328116-dc723b54-e653-4b36-84b8-e34678d4f095.png)

**Comment by drew-boy** [comment]
As mentioned, Albedo is not our app.
We'll bring it up if needed with the Albedo team.
