### ISSUE TITLE
I can borrow up to 746$ with just 0.19$ worth of BTC left after withdraw all my lent asset?

### ISSUE THREAD

**Issue by vominhtri1611** [script3/yieldblox-beta#313]
First I just want to withdraw all my asset back to my wallet (include: BTC, ETH, USDC, EURT), 
Decrease all Collateral to 0% -> then Withdraw all my asset back to my wallet with Max button. 
But after all still have a little BTC balance in Lend value worth of 0.19$. 
So I try to borrow BTC with Max button and its worked, I borrow 746$ with 0.19$ left worth of BTC.

Here is my screenshot the result, with Healthfactor 1.11 and minus Net APY
![image](https://user-images.githubusercontent.com/36155515/137317093-8cd9e604-8298-435d-9c6e-f42dfa0f2f76.png)
![image](https://user-images.githubusercontent.com/36155515/137317303-2f8cdef5-29b9-4873-a81b-47a0c25fd78d.png)

**Comment by vominhtri1611** [comment]
I try to borrow BTC with Max botton again, and its worked.

![image](https://user-images.githubusercontent.com/36155515/137318449-aa3f54f8-0f0b-4034-affa-f3e7de48e5f8.png)

Now I can borrow more BTC up to 46 BTC

**Comment by vominhtri1611** [comment]
![image](https://user-images.githubusercontent.com/36155515/137319273-2036e3a6-0346-470a-8df9-6194d11628b3.png)

I borrowing 14 BTC more and the transaction still complete

**Comment by arnob016** [comment]
Did you get liquidated? @vominhtri1611

**Comment by vominhtri1611** [comment]
> Bạn có bị thanh lý không? @ vominhtri1611

No, actually then I borrowed 40 BTC more (If deposit and collateral, I can borrow more than that), but after that I just Repayed all my borrowed BTC. 
Now the Token Yield come normal but my Net APY and HF still bug, and after all I lost 2 BTC haha.
![image](https://user-images.githubusercontent.com/36155515/137405683-bf3d2f61-9e7a-441c-8fe4-1eb7afd4a14d.png)
