### ISSUE TITLE
Swap ratio YBX : assets

### ISSUE THREAD

**Issue by LorDDark6660** [script3/yieldblox-beta#315]
ratio of swaping :) 1YBX=0,47USDC  / 1YBX=47,3 XLM/ 1XLM=0,4 USD /   47,3 XLM*0,4USD = 18,92 USD 
         
 1YBX =18,92 USD  thats not same like 1YBX= 0,47 USDC

![1](https://user-images.githubusercontent.com/92062140/137317536-5601dbdc-c87f-41f0-a4ee-05f496e33d87.png)
![2](https://user-images.githubusercontent.com/92062140/137317543-1d0ff01c-bcdf-41c1-8cd3-2be10464ac1b.png)

**Comment by arnob016** [comment]
it's not listed fully yet ig, so it's bugged. We checked this a few days back.

**Comment by yuminachan** [comment]
how do you get auth to swap it? i tried to trade but it said "no auth" lol

**Comment by arnob016** [comment]
@Amishici  don't swap into ybx or xlm. Trust me you'll regret it.

**Comment by drew-boy** [comment]
Albedo isn't our app
