### ISSUE TITLE
Massive Health Factor increased

### ISSUE THREAD

**Issue by coolrobiul** [script3/yieldblox-beta#318]
Suddenly health factor increased a lot

![Screenshot_2021-10-14-19-23-13-93_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/59414838/137326579-e24d114a-a20b-4914-9269-08b9a499b459.jpg)

**Comment by coolrobiul** [comment]
![Screenshot_2021-10-14-19-31-30-52_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/59414838/137327683-a45f6ad7-c2a6-41a5-bff3-9dcf0b0c04b6.jpg)

**Comment by coolrobiul** [comment]
Previous bug was after ybx claim

But this isn't not same as before

This is suddenly

**Comment by mootz12** [comment]
This happens when someone commits a trade on the LP with YBX. They end up buying YBX for an outrageous price.
