### ISSUE TITLE
ETH assets disappeared but it still shows the loan (during the HF Spike)

### ISSUE THREAD

**Issue by theboycoder** [script3/yieldblox-beta#319]
I borrowed 1K ETH to test this bug again and see if it would allow me to borrow again with this spike which it did. But during the lending process I rejected the transactions and thought I would just pay it back instead of risking liquidation. After I cancelled the lending transaction the ETH assets I borrowed disappeared but the liabilities still showed I have borrowed it. I moved out of all positions to minimize the damage and even paid off all my previous ETH but the loan is  stuck at the amount I borrowed which disappeared but the balance remains. 

![37f84f5aee651ff18ddb469d9129b561](https://user-images.githubusercontent.com/45983304/137342258-0d92ef05-7193-4b07-bb39-0483a2a76ddc.png)

![050a44c30d4ab61c2ef5cb06261335af](https://user-images.githubusercontent.com/45983304/137342261-62454763-9bec-4db8-bad8-5775da4b59e7.png)

![76ca8948f3aec4a536a696b918a823f1](https://user-images.githubusercontent.com/45983304/137342262-382f7546-4360-4ac9-9752-7d35e133c3ee.png)

![aff50d0be78b6446c4ba33f0702d5d76](https://user-images.githubusercontent.com/45983304/137342266-2b99afc5-77f3-498e-865d-023f3457c728.png)

![1e704d93995c30eb4784763805f10b4b](https://user-images.githubusercontent.com/45983304/137342986-afd172d4-937f-476d-9ce3-6fd39a6f0144.png)

**Comment by mootz12** [comment]
The deposit step is being changed to be atomic. We have a bot running that pays back any claimable balances due to canceled deposits.
