### ISSUE TITLE
The website is sometimes offline 

### ISSUE THREAD

**Issue by gbosah** [script3/yieldblox-beta#322]
Anytime i exited my browser and stay longer before entering, my YBX site is always offline until i clear my browser data and exit the browser.
PS:
My other open page is always online only the YBX beta website. 
![Screenshot_2021-10-14-05-26-53-382_org flow browser](https://user-images.githubusercontent.com/28156856/137387312-b92d56d8-f834-4d68-9ec9-d88186cc65af.jpg)

**Comment by arnob016** [comment]
You've downloaded an offline version of the page / in data saver mode. So it is showing you a preloaded version of the site. Just reload.
