### ISSUE TITLE
Unable to claim YBX

### ISSUE THREAD

**Issue by hasToDev** [script3/yieldblox-beta#325]
Something went wrong when claiming YBX.

![unable-to-claim](https://user-images.githubusercontent.com/44645201/137406144-8ce40eb4-58ef-40e6-994f-5a52a01b16a2.jpg)

it gives following **XDR :**

AAAAAgAAAAAywYeo/72rPIgMTAJ6lJyi46299vo/ReRsFxCHByqsYAAAH0AAA6GxAAAAZAAAAAEAAAAAAAAAAAAAAABhaLWOAAAAAQAAAAh5YnhDbGFpbQAAACgAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAOzWsv80nDK/N2Le+dbgPhqwtwebs9KFUUvMDT/nKpJlAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACeTAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAdBkB94QAAAACAAAAAAAAAAAywYeo/72rPIgMTAJ6lJyi46299vo/ReRsFxCHByqsYAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAAefx7COPx+ObeLtn4HCrJ1xQyhnsoPqEnoM/8IlrIyrUAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADgAAAAJ5MDBCVEMAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAJFsTgAAAAIAAAAAAAAAADLBh6j/vas8iAxMAnqUnKLjrb32+j9F5GwXEIcHKqxgAAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAA+0LYMQuxEkNDLTJzQcXGemJkZiOQAMN9h9q1FqSUM5gAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAnkwMEVUSAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAIiJsmAAAAAgAAAAAAAAAAMsGHqP+9qzyIDEwCepScouOtvfb6P0XkbBcQhwcqrGAAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAACe1Cn/36iZv6pw9id4xFvhP82PNNgfP9k1HR09VVWUxAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACeTAwRVVSVAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAACvyW0YhEAAAACAAAAAAAAAAAywYeo/72rPIgMTAJ6lJyi46299vo/ReRsFxCHByqsYAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABRVRIAAAAAAAm/Hr+did1Niqr/LIylIKKOluv+dfLo2q0RY7qILYT0gAAAAAAAAABAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAA8ILtMESHOtQRq6tjrjGqrQUychVQtdpITF/GfVr+I5sAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADgAAAAJsMDBFVEgAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAA4gAAAAMAAAAAAAAAADLBh6j/vas8iAxMAnqUnKLjrb32+j9F5GwXEIcHKqxgAAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAABAAAAAAAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABQlRDAAAAAAA1Ek02bEhKY4k7M1uIniJN5hg0JdWoXuxpOkwCDDa1cQAAAAAAAAABAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA8AAAAAbIoJAWBcT9y/0NJDKqSWWdi1dVdMZwPLP+2DxUmquSgAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADgAAAAJsMDBCVEMAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAoowAAAAQAAAAAAAAAADLBh6j/vas8iAxMAnqUnKLjrb32+j9F5GwXEIcHKqxgAAAAAwAAAAEAAAAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAABAAAAAAAAAAZAAAAAAAAAAAmEBpzguHKqyy60NXLzOF08l2AyJXck6SXA+Bod2mEWAAAAAQAAAAAABRhuQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUVVUlQAAAAAAnN4X8L1YGspk5rx+yGy3gsrA34YrwYRKvN3wJ9AZTYAAAAAAAAAAQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAB8Oe6gpjLNvsN0M6Niyrme8lKyicTj/k7CLX2bXBuifAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwRVVSVAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAANxadVDJEAAAADAAAAAAAAAAAywYeo/72rPIgMTAJ6lJyi46299vo/ReRsFxCHByqsYAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAWlHFIBAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAVVTREMAAAAACB2eQLRqhZI+n1rL9qB81ce92ggXv546I6iFd98ySkcAAAAAAAAAAQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAACiEXcOS+/dhqOQdBwyniAsrDbz2XHIzrE8Yb9lwGq2AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAABOaZ58AAAADAAAAAAAAAAAywYeo/72rPIgMTAJ6lJyi46299vo/ReRsFxCHByqsYAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAABlXHQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUVUSAAAAAAAJvx6/nYndTYqq/yyMpSCijpbr/nXy6NqtEWO6iC2E9IAAAAAAAAAAQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAPCC7TBEhzrUEaurY64xqq0FMnIVULXaSExfxn1a/iObAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwRVRIAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAOIAAAADAAAAAAAAAAAywYeo/72rPIgMTAJ6lJyi46299vo/ReRsFxCHByqsYAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAAAAAQAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAGyKCQFgXE/cv9DSQyqkllnYtXVXTGcDyz/tg8VJqrkoAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwQlRDAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAKKMAAAAEAAAAAAAAAAAywYeo/72rPIgMTAJ6lJyi46299vo/ReRsFxCHByqsYAAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAGQAAAAAAAAAAJhAac4LhyqssutDVy8zhdPJdgMiV3JOklwPgaHdphFgAAAAEAAAAAAAUYbkAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFFVVJUAAAAAAJzeF/C9WBrKZOa8fshst4LKwN+GK8GESrzd8CfQGU2AAAAAAAAAAEAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAAfDnuoKYyzb7DdDOjYsq5nvJSsonE4/5Owi19m1wbonwAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMEVVUlQAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAADcWnlAjrAAAAAwAAAAAAAAAAMsGHqP+9qzyIDEwCepScouOtvfb6P0XkbBcQhwcqrGAAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAFpSQxjEAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAAAAAAAEAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAAAohF3Dkvv3YajkHQcMp4gLKw289lxyM6xPGG/ZcBqtgAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAATmmejAAAAAwAAAAAAAAAAMsGHqP+9qzyIDEwCepScouOtvfb6P0XkbBcQhwcqrGAAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAZVx8AAAABAAAAACYQGnOC4cqrLLrQ1cvM4XTyXYDIldyTpJcD4Gh3aYRYAAAAAQAAAAAywYeo/72rPIgMTAJ6lJyi46299vo/ReRsFxCHByqsYAAAAAFZQlgAAAAAAJFmQO+U/rh+vFnAXVH+zIYixxh/0M4EICyDllZx2EPHAAAAAKEzstYAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAEQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAI5/uSuZx8KTY7FVjRUGglnnXgt3eVoXYIOombTaqwfKAAAAAnUwMEVUSAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAABpN/alAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAAihxoC2Rc3Rzv52OlD93qOot5BbzNcUIMIrreZ9+mOJ4AAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAALb7kVMAAAABAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAQAAAAD3yZrjxj6aKxNPNqM9QsRE9usR0zw/bFoP/vqhtNy3TwAAAAJ1MDBFVVJUAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAACvsIPgAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAATAAAAAnUwMEVVUlQAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAD3yZrjxj6aKxNPNqM9QsRE9usR0zw/bFoP/vqhtNy3TwAAAAAAAAABAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAEAAAAA78nXTQ0NaNI/TpXwvzB+m0Ms4zYdPVDrRoU1JSZxhosAAAACdTAwVVNEQwAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAABPeNqMAAAAAAAAAA5Q50UEAAABAooFsu3iljfUHkPWgAkFphvlYQTRIH0Z1oAIjjKlgPHduHC79J4vyXZV2JMJ9ZieB4PLxyRDWpjLkn5wNWErND2RG3GMAAABAnBsnpBjlF32ZOwVnLP09ZIs4GWIW8brCTH+r9fSPDsM61Ytmz8iBfCvp+zSufR3RfEQUqkjslLkj1tCB16w7BwcqrGAAAABAt1Xrqlf6MH7YcLP5PNLbOlDhNYOCN9tI0JxbO+M7o4Z7fszvixTb5BHhIqIgLjK+1g63e/yi6huYSClX78HyBg==

**Comment by hasToDev** [comment]
today i can't claim YBX again, no XDR data available.

![cannotclaim](https://user-images.githubusercontent.com/44645201/138080568-9e9b6679-984c-4c85-99f6-aba90129ed26.jpg)

**Comment by mootz12** [comment]
Relates to https://github.com/script3/yieldblox-beta/issues/354

The above bug clearly defined the issue, so not marking as duplicate. However, I will still qualify this bug for a for a bounty.

**Comment by hasToDev** [comment]
indoRaptor#0844
GAZMDB5I7662WPEIBRGAE6UUTSROHLN5635D6RPENQLRBBYHFKWGB3MD

**Comment by markuspluna** [comment]
Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public
