### ISSUE TITLE
Able to withdraw all funds with active loan position.

### ISSUE THREAD

**Issue by kingrasha** [script3/yieldblox-beta#326]
I repaid a loan in EURT but forgot to pay a small ETH loan and was still able to remove all collateral and withdraw all coins from the platform
![Untitled-1](https://user-images.githubusercontent.com/80496286/137425757-9c7f1270-2bb8-4b02-bb03-62e92efedf7f.jpg)
![Untitled-2](https://user-images.githubusercontent.com/80496286/137425837-affc2442-34fe-433e-9dd5-dc1f942e3399.jpg)
.

**Comment by mootz12** [comment]
This is correct. Your staking YBX is acting as collateral for the small loan.
