### ISSUE TITLE
Cannot increase Collateral from 0% to any%

### ISSUE THREAD

**Issue by ElliotFriend** [script3/yieldblox-beta#33]
I think I figured out the pattern to make this work. I'm using Brave (all popups allowed), Freighter, and have successfully navigated through most parts of the UI. Here's what happened, and how I managed to solve it:

1. I deposited 50,000USDC with 0% collateralized.
2. Went to the "profile" page and tried to increase the collateral to anything. No matter if I was trying to increase to 100% or 50%, or whatever, the transaction would always fail, but only for assets that had 0% collateralized to begin with.
3. I deposited an additional 1,000USDc, with 10% collateralized. Transaction worked fine.
4. After this deposit, I was able to change the collateralized level for the rest of that deposited asset.

I guess if there's no collateral setup at the beginning and it's 0%, you can't increase it without making a deposit first.

**Comment by mootz12** [comment]
This was a frontend oops. We don't need the turrets to collateralize a loan, this is something the user can do on their own. It has been resolved.

**Comment by ElliotFriend** [comment]
@mootz12 Here's my Discord username for the beta bug bounty: ElliotFriend:5362

**Comment by markuspluna** [comment]
Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public
