### ISSUE TITLE
0 value loans showing in Profile

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#337]
Finally managed to repay my small EURT and ETH loans with collateral but they are determined to hang around. 

1. Repayment transactions for small EURT fixed and variable and variable ETH:
https://stellar.expert/explorer/testnet/tx/3fddc7d36374fd4cc7aeba5017891a53b688391777ce6f2b093e4bdd7a3133b9
https://stellar.expert/explorer/testnet/tx/ce196a76169a918a48d43c0d423ba8e44b4e0aa9063ff51a0426a325d68afd8e
https://stellar.expert/explorer/testnet/tx/abdb00b8dd8e5adad9b59804a2d1cb96f0714656c2e2e9e994467a784ba19ba7

2. 0 value loans showing on my profile:

![image](https://user-images.githubusercontent.com/11483548/137604904-8a35d1dd-6c19-4691-ac04-0b2bfbef25aa.png)

Actually 0 value not a very small display issue 0
![image](https://user-images.githubusercontent.com/11483548/137604924-f10168fe-47a8-452c-9807-9e414e4f1e5e.png)

![image](https://user-images.githubusercontent.com/11483548/137604930-4c8d6791-d727-4ddf-9f82-2d0043c2a2d9.png)

**Comment by arnob016** [comment]
There's 1 lumen stuck there. This was reported more than any other bugs.=

**Comment by mootz12** [comment]
Yup, this was a lingering rounding issue. Marking as duplicate. https://github.com/script3/yieldblox-beta/issues/32
