### ISSUE TITLE
Some YBX are claimed automatically

### ISSUE THREAD

**Issue by husnulh4kim** [script3/yieldblox-beta#340]
![Screenshot_142](https://user-images.githubusercontent.com/58093903/137607032-3f7d70a3-d3e0-4e3d-b61a-bb952b58cc48.png)
![Screenshot_143](https://user-images.githubusercontent.com/58093903/137607036-18bcd6fb-0a82-4d5c-a029-8f7affba1995.png)
![Screenshot_144](https://user-images.githubusercontent.com/58093903/137607038-943a9ecb-bade-4820-b8bc-733f92504467.png)
![Screenshot_145](https://user-images.githubusercontent.com/58093903/137607040-51d2943a-c14d-4c1e-b303-2e93d268925b.png)
The problem is like this, I have an unclaimed YBX, when I made a loan with EURT suddenly some of my YBX was automatically claimed.
 I've seen this problem in the last few days

**Comment by husnulh4kim** [comment]
![Screenshot_146](https://user-images.githubusercontent.com/58093903/137607679-0dcae8f0-4661-40e1-ab5d-66ecee295947.png)
This happens every time I do any transaction activity

**Comment by starlog20** [comment]
it is work as intended. If there you make transaction with claimable balance in the transaction, the ybx reward will also claimed together the transaction that you have made.
