### ISSUE TITLE
Health in the Milli

### ISSUE THREAD

**Issue by BrightLigth** [script3/yieldblox-beta#341]
![Health in the milli](https://user-images.githubusercontent.com/92237131/137608285-eb38a04e-01f9-4c8e-b16b-2de69cee315a.PNG)

**Comment by arnob016** [comment]
It's not a bug, it's a feature.

**Comment by mootz12** [comment]
Yup, HF can be between infinity (collateral and no loans) and 0 (no collateral and loans).
