### ISSUE TITLE
 Majority of turrets failed to execute contract. Cannot read property 'avg' of undefined

### ISSUE THREAD

**Issue by Firdausfarul** [script3/yieldblox-beta#344]
This happened when i try to borrow.

![image](https://user-images.githubusercontent.com/29442958/137609885-b157927f-e761-4bf3-904f-6b92db4c4121.png)

Something went wrong!
Failed to generate your token! Please try again by performing another action.

Majority of turrets failed to execute contract. Cannot read property 'avg' of undefined

**Comment by mootz12** [comment]
Our market making bots weren't the most consistent during the beta. This occurs when the market making bot gets stuck and we can't properly get the TWAP
