### ISSUE TITLE
Borrow amount not showing up its on USDC showing in profile tab; refreshed several times

### ISSUE THREAD

**Issue by BrightLigth** [script3/yieldblox-beta#345]
![Borrow not showing up](https://user-images.githubusercontent.com/92237131/137613554-f96e1e69-65be-4ab5-8cc3-1f04065fa4c1.PNG)
![Borrow on profile tab](https://user-images.githubusercontent.com/92237131/137613611-d92a8fa1-653d-4e4f-a802-b88f175e6c06.PNG)

**Comment by mootz12** [comment]
There was an issue where we could only grab one borrow when displaying `Current Borrow`

It has been fixed.

**Comment by drew-boy** [comment]
Hello @BrightLigth!

Could you comment one of these on your issue:

Discord username
Keybase username
Email linked to your beta account
Your YieldBlox Testnet Beta public address
Your personal public Stellar address (not recommended; post at your own risk)

It's so we can contact you and reward you a Beta Bug Bounty! :-)

**Comment by BrightLigth** [comment]
Hey thanks. Discord— BrightLight#8046


Sent from Yahoo Mail for iPhone


On Wednesday, November 10, 2021, 8:36 PM, drew-boy ***@***.***> wrote:




Hello @BrightLigth!

Could you comment one of these on your issue:

Discord username
Keybase username
Email linked to your beta account
Your YieldBlox Testnet Beta public address
Your personal public Stellar address (not recommended; post at your own risk)

It's so we can contact you and reward you a Beta Bug Bounty! :-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by markuspluna** [comment]
Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public

**Comment by BrightLigth** [comment]
Thanks
    On Tuesday, November 30, 2021, 08:28:12 PM CST, markuspluna ***@***.***> wrote:  
 
 


Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
