### ISSUE TITLE
HF Calculation Issue with Repay activity, Probably Trigger Full Liquidation

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#346]
I dont try if this transaction can be done or will prevented by sistem, but if the liquidation bot try to repay loan with overload collateral, this one probably happen. HF would extremely become keeps decreased instead of increasing by repay activity.

![repay bug](https://user-images.githubusercontent.com/91896561/137614104-18237401-a382-4201-8ac3-10617e2203c3.gif)

**Comment by f0xie7** [comment]
Its probably because its enabled me to withdraww the collateral by accident of repaying it. The collateral that overpaid would go to my wallet and my position on platfrom would be on the risk since the hf go dropped since my lending withdrawed.

**Comment by mootz12** [comment]
Liquidations aren't allowed to remove your collateral, they can only apply it towards a loan.

When you repay through the Repayment modal, we allow you to remove collateral in the same step if desired (and given your HF can support it)
