### ISSUE TITLE
Health factor at 6+ billion?

### ISSUE THREAD

**Issue by cryptodmc771** [script3/yieldblox-beta#347]
<img width="1440" alt="Screen Shot 2021-10-17 at 1 58 54 PM" src="https://user-images.githubusercontent.com/92388247/137639300-f2b24313-3f69-4c64-9526-ef6b6437d8fc.png">

**Comment by arnob016** [comment]
_**It's not a bug, it's a feature**_
It's normal to have millions of HF.

**Comment by mootz12** [comment]
^
HF can be between infinity (collateral and no loans) or 0 (no collateral and loans)
