### ISSUE TITLE
Repayment Dialog Does Not Show Small Amounts

### ISSUE THREAD

**Issue by notwheel** [script3/yieldblox-beta#350]
It might have been by design, but the repayment dialog does not show the balances of loans with very small amounts - i.e., I paid off what I thought my total balance of USDC was, but the the token still appears in Borrow:

![image](https://user-images.githubusercontent.com/543510/137779884-a20ed74c-4af2-46b9-805a-23641149c739.png)

Upon opening the loan, it shows that the liabilities are zero: 

![image](https://user-images.githubusercontent.com/543510/137779977-ff9c996e-8ab2-49ee-ac3e-9fc41b0b7606.png)

It's not until choosing the max amount to repay is it made clear that a very tiny amount of USDC is still owed:

![image](https://user-images.githubusercontent.com/543510/137779849-05b6511b-3e31-43f8-b6d1-c3ef32f948f9.png)

This might prove confusing to users - and possibly interpreted as a bug in normal use cases. Also, it creates an added step of having to go back and try to figure out what's causing it to appear and then repay the amount.

Maybe adding a few decimal places conditionally when there is a tiny amount of loan repayment due. (though it's not standard in US $ format, it might be helpful here)

**Comment by mootz12** [comment]
We have a story on the backlog to show smaller amounts instead of `0.00`. It caused a good amount of confusion during the beta.

Marking this as duplicate to others and closing. Thanks for the suggestion!
