### ISSUE TITLE
Negative interest rate (-4396.49%) shown in Profile

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#351]
My fixed interest rate position is shown with a negative interest rate:

![image](https://user-images.githubusercontent.com/11483548/137815720-e4d270cb-5c7a-4fa9-9bae-c04f465904c0.png)

**Comment by mootz12** [comment]
This likely was a introduced bug due to https://github.com/script3/yieldblox-beta/issues/213

Thanks for calling it out - marking this bug as duplicate to 213.

**Comment by defj** [comment]
@mootz12 If this was introduced as part of another fix then shouldn't it be it's own issue? Anyway I also raised #213 so I guess I don't miss out too much :)
