### ISSUE TITLE
Repayment and Deposit issue (updated)

### ISSUE THREAD

**Issue by theboycoder** [script3/yieldblox-beta#352]
I was trying to repay my borrowed funds but there was a bug with the max repay button with displaying faulty numbers and it allowed me to submit the transaction for a different amount than displayed.

more info on what the chain displayed:
https://stellar.expert/explorer/testnet/tx/199ebc9e89a189038cbe8e2b88eab44d034e4d7f4e1bcfb80177cafcbca2f599

Edit: This also allows me to deposit 1e-7 from USDC/ETH and it confirms the screen and transcations between this. 

Edit 2:  Allowed me to deposit into the wallet
![e1](https://user-images.githubusercontent.com/45983304/138184755-21bf978c-e2d0-4dc8-9a2f-0e9df329f5d7.png)

Edit: 1 USDC 
![r2](https://user-images.githubusercontent.com/45983304/138005217-66b97bbf-618d-4a0b-af11-b28a9298a3f5.png)

Edit: 1 USDC
![r1](https://user-images.githubusercontent.com/45983304/138005229-1c5c9e60-ee26-4ecc-9032-cdd8c6ea1a52.png)

https://user-images.githubusercontent.com/45983304/137825700-ac1a028c-bd92-440e-81cb-5a95061a2002.mp4

![repay f](https://user-images.githubusercontent.com/45983304/137825825-ddb24c9e-00f1-4eb3-a8ca-f7c2e2c80464.png)

![repay f 2](https://user-images.githubusercontent.com/45983304/137825705-d96a98fe-15be-4bd0-8872-48f7daf11063.png)

**Comment by mootz12** [comment]
It appears you only have 1 stroop (1e-7) of BTC in your wallet, so this is working as intended.
