### ISSUE TITLE
The number of YBX claims is reduced when Repay EURT with Collateral (ETH)

### ISSUE THREAD

**Issue by ygusmada** [script3/yieldblox-beta#353]
today I deliberately did not claim ybx and tried to repay EURT with collateral (ETH). before i repayed, YBX amount that should i got is 36, when repayed with collateral it decrease to 12.

**Comment by ygusmada** [comment]
i try to borrow again and it decrease to 6

**Comment by mootz12** [comment]
This is working as intended. Every time a position is touched, we claim YBX for it if there is some available.
