### ISSUE TITLE
Having a large amount of borrows on EURT for a long period of time suddenly stopped all operations from executing by triggering this error message "Invalid hyper string: NaN"

### ISSUE THREAD

**Issue by austinero77** [script3/yieldblox-beta#354]
Yesterday I tried claiming my portion of ybx only for an error message "Invalid hyper string: NaN" to pop in the course of claiming, I did several refreshing and still the same, I observed the whole thing and thought it was my HF at 1.09 and tried other operations to repay the loan even with my collateral but the same error message occurred, I kept trying all to no avail and after several hours from yesterday till now I tried again with my HF at 1.11 this time the same error kept occurring, This appears to be a new bug triggered because I had a Large borrow on a single asset (EURT) for a long period of time, in the case of beta testing, from the beginning. I have had other borrows in other asset and was able to pay back previously but never did on EURT due to my strategy. In total I have 1.85M EURT on borrows.
![IMG_20211020_004325_643](https://user-images.githubusercontent.com/91912591/138005225-1b7fff41-3216-4508-a7b8-37d34c6c84bd.jpg)

**Comment by austinero77** [comment]
![IMG_20211020_004539_453](https://user-images.githubusercontent.com/91912591/138005390-a1a72364-6a55-4926-8543-c2a66b7008d6.jpg)

**Comment by austinero77** [comment]
![IMG_20211020_004232_001](https://user-images.githubusercontent.com/91912591/138005767-83fea8c7-c1db-4013-8be8-3b13d802cb2a.jpg)

**Comment by mootz12** [comment]
This has been resolved. I believe it was the first log of this bug, so I am assigning it as such. If there was an earlier bug, please let me know.

**Comment by austinero77** [comment]
Discord: Austinero77#6716
