### ISSUE TITLE
Amount of claimable YBX decreased , Some YBX gone! After Repay, Borrow and Lend! ( UPDATED!)

### ISSUE THREAD

**Issue by zigone2021** [script3/yieldblox-beta#356]
I've been to test this several days and lost some claimable YBX for some days. 
Firstly, I think the automatic claim for YBX rewards must be fixed or turned off , because I found it decrease our available rewards by automatically claim it after some transaction.
I did test this several days before reporting it here, maybe people already report this or about automatically claim before this thread, but I tried to catch details after several days testing to make sure it's not just a glitch.. So here we are...
Take a look into the screenshot bellow:

![screenshot_17](https://user-images.githubusercontent.com/92061986/138035678-4cdfcc61-30ec-4acb-a22b-8872c9429c1d.png)

**Explanation:**
Claimable YBX : 54.38 YBX
Wallet YBX : 0.35 
If I claim the YBX i should get 54.73 YBX in my wallet.

But after I did some transactions for example : Repay => some the unclaimable YBX is automatically claimed and amount decreased:

![screenshot_19](https://user-images.githubusercontent.com/92061986/138036389-6a2c93c5-69d3-4e16-b43e-3f97b09594ab.png)

the result is bellow :
![screenshot_20](https://user-images.githubusercontent.com/92061986/138036678-55842c0c-00fe-448b-bd30-376cc72c9570.png)

**Explanation :**
Claimable YBX : 37.85 YBX
Wallet YBX : 4.94 YBX
Total : 42.79 YBX which is means 11.94 YBX is gone. (54.73 - 42.79= 11.94)

So another test i made and repay :
![screenshot_25](https://user-images.githubusercontent.com/92061986/138037291-4a248580-ee5f-47e3-a06c-3b9a5c89540e.png)

And here is the result :

![screenshot_26](https://user-images.githubusercontent.com/92061986/138037377-dcce8aa0-4786-4bfd-90d3-c6aefe42b80c.png)

**Explanation :**
Claimable YBX : 2.57 YBX
Wallet YBX : 39.66 YBX
Total : 42.23 YBX which is also decreased a bit from 42.79 YBX ( 0.56 YBX lost...)

- [ ] UPDATE! : ( Today test for only Lend and Borrow)

![screenshot_32](https://user-images.githubusercontent.com/92061986/138393419-166530fd-37e9-4174-a82a-0dfcfa932e09.png)

**Explanation :**
Claimable YBX : 23.62 YBX
Wallet YBX : 0 YBX
Total : 23.62 YBX if I claim it directly ( start balance for this test)

I tried to make a borrow transaction:
![screenshot_33](https://user-images.githubusercontent.com/92061986/138393603-eab24710-d8f1-431b-bb8d-ab4f3bb6a0c0.png)

Here is the result :
![screenshot_34](https://user-images.githubusercontent.com/92061986/138393640-d36f9685-fd94-46db-b518-457eb4122851.png)

**Explanation :**
Claimable YBX : 23.54 YBX
Wallet YBX : 0.09 YBX
Total : 23.63 YBX  (+0.01 YBX) Surprisingly it gave me more YBX

Lend it:

![screenshot_35](https://user-images.githubusercontent.com/92061986/138393827-5d68af8d-3429-44b9-979a-63f0e310e568.png)

The result :
![screenshot_36](https://user-images.githubusercontent.com/92061986/138393880-b70eb462-a1cd-47b5-8356-4921279faa23.png)

**Explanation :**
Claimable YBX : 22.37 YBX
Wallet YBX : 1.25 YBX
Total : 23.62 YBX  (-0.01 YBX) - Decreased

More Borrow, now with BTC :

![screenshot_37](https://user-images.githubusercontent.com/92061986/138394080-22e09463-9ad1-42cb-8177-6adc8d579191.png)

The result is :
![screenshot_38](https://user-images.githubusercontent.com/92061986/138394110-65eced92-7f2c-4339-b344-6e5b0fcbf891.png)

**Explanation :**
Claimable YBX : 13.53 YBX
Wallet YBX : 10.09 YBX
Total : 23.62 YBX (same)

Lend it: 
![screenshot_39](https://user-images.githubusercontent.com/92061986/138394247-5d2c69bc-716f-4094-8ca1-3b30bd1d16ee.png)

The result is:
![screenshot_40](https://user-images.githubusercontent.com/92061986/138394287-eee3589d-15b1-4321-b739-00783876ef20.png)

**Explanation :**
Claimable YBX : 1.09 YBX
Wallet YBX : 22.54 YBX
Total : 23.63 YBX (+0.01 YBX)

Borrow USDC :
![screenshot_41](https://user-images.githubusercontent.com/92061986/138394471-d2c3d7a4-8526-41ff-aab3-c138ca7aacb5.png)

Result :

![screenshot_42](https://user-images.githubusercontent.com/92061986/138394516-9063aca6-700c-4c2b-898f-243017483e90.png)

**Explanation :**
Claimable YBX : 1.00 YBX
Wallet YBX : 22.62 YBX
Total : 23.62 YBX (+0.01 YBX)

Make a deposit borrowwed USDC:
![screenshot_43](https://user-images.githubusercontent.com/92061986/138394632-7ff9abd7-667d-4a0c-b624-344c00c43215.png)

Result :
![screenshot_44](https://user-images.githubusercontent.com/92061986/138394652-5213b401-faf7-451d-aae1-dea080f77826.png)

**Explanation :**
Claimable YBX : 0.58 YBX
Wallet YBX : 23.04 YBX
Total : 23.62 YBX (-0.01 YBX from the last )

**Conclusion:**
1. The biggest lost is on repay the borrow from my experiences. Its also happen to Lend and borrow, but only a bit, amount decreased and raised but remains same or lost a bit or increased a bit. 
2. And after some minimum YBX its stop to automatically claim even after I did more transaction.

This is not a real YBX because of this is a beta YBX. But if this is a real YBX , must be a big problem when people lose the YBX rewards. I hope it'll fixed and team take some solution for this kind of report before the mainnet.

**Comment by starlog20** [comment]
just want to connected other case #276

probably my repayment transaction shouldn't  be ignore there because i did it between 1st claim and 2nd claim. 
about reducing ybx issue probably bcuz of this. but about why i must do claim for twice is still questionable!

Anyway good analyst my friends!

**Comment by zigone2021** [comment]
> just want to connected other case #276
> 
> probably my repayment transaction shouldn't be ignore there because i did it between 1st claim and 2nd claim. about reducing ybx issue probably bcuz of this. but about why i must do claim for twice is still questionable!
> 
> Anyway good analyst my friends!

Nice, It seems we are reporting the same issue or maybe others too. This great  found since will impact Yield farming , i did already found before and others too, but we just dont pay much attention into this. This is why i try to analyze this issue 3 days before reporting and took a necessary screenshot for reporting.

**The biggest lost is on repay from my experiences, its also happen to Lend , not yet try on borrow, but will do on the next day. And after some minimum YBX its stop to automatically claim.**

**Comment by mootz12** [comment]
Closing as duplicate to #276. Thanks for the added detail on the issue.

**Comment by zigone2021** [comment]
Sadly this is closed and marked as duplicate. I knew it's connected to the issues #276 when i read it, different methods, different ways on testing. And reporter at #276 is also said it's different in some way. Test it in several ways for days to make sure the issues is still exist before reporting , and need to catch the details that makes me late on reporting. But surely this will help much for YBX development.  Thanks anyway @mootz12 , hope YBX can be more powerful after fixing the bugs 😉
