### ISSUE TITLE
FIXED Rate Changed

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#363]
I believe i borrow it when the rate was around 30%, but after the patch that make fixed rate is not floating anymore, my fixed rate goes down to 10%, is it true or a bug?
![image](https://user-images.githubusercontent.com/91896561/138301364-c96493ae-7fb0-48aa-ab72-8371336dc0df.png)

**Comment by markuspluna** [comment]
Old bug I believe. The fix meant fixed rates were refreshed

**Comment by markuspluna** [comment]
I'll look into it just to be sure. When did you open this position?

**Comment by f0xie7** [comment]
> 
> 
> I'll look into it just to be sure. When did you open this position?

Its not that far until the rate is as low as 10%, i believe i open that position when the fixed rate was around 30%.

**Comment by mootz12** [comment]
Linking this back to #213 . It appears there still is a bug in calculating this.
