### ISSUE TITLE
Can't borrow anything

### ISSUE THREAD

**Issue by coolrobiul** [script3/yieldblox-beta#365]
This is happening when I'm going to borrow any asset
Tried every asset to borrow.. but same result everytime

![Screenshot_2021-10-24-20-24-13-79_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/59414838/138598590-dbf4f46c-eaf8-483d-bae4-295e5beee4cf.jpg)

**Comment by markuspluna** [comment]
This was just the price bot breaking
