### ISSUE TITLE
Different Amount Fixed Interest Rate in Borrowing Market with my Borrow Profile

### ISSUE THREAD

**Issue by reigister** [script3/yieldblox-beta#367]
So, i try to look the change Fixed Interest Rate in Borrowing Market 

Before i try my experiment, i take a SS like this picture below, you can see the Fixed Interest Rate is 45.49%
![Fixed interest rate](https://user-images.githubusercontent.com/78670969/139170768-4be9b25d-7ebc-4122-9ad0-3f795c55f475.png)

I do borrow 2M EURT and successful
![Fixed interest rate 2](https://user-images.githubusercontent.com/78670969/139170776-f38d0f89-4926-4ae0-a307-6cff2ab91146.png)
![Fixed interest rate 3](https://user-images.githubusercontent.com/78670969/139170778-4fc33523-7d04-4d4a-a4b7-23acd086210d.png)
![Fixed interest rate 4](https://user-images.githubusercontent.com/78670969/139170782-93fed90c-8d3c-4996-a948-19cf021ede18.png)

but look the Fixed Interest Rate Change. is it right? if fixed interest rate change so it not fixed rate again right? CMIIW
![Fixed interest rate 5](https://user-images.githubusercontent.com/78670969/139170785-511e5fc5-cf1b-408c-a1bd-6c24997e3610.png)

I try to look in my profile and then it not show rate before i borrow (45.49%) it show rate after i borrow (47.91%)
![Fixed interest rate 6](https://user-images.githubusercontent.com/78670969/139170787-cc7c8c1e-6f49-41e9-bde1-5a13c430e5cb.png)

I do deposit back 2M EURT
![Fixed interest rate 7](https://user-images.githubusercontent.com/78670969/139170789-ff254152-9857-4a88-87cb-add7dbc4efb9.png)

The Fixed Interest Rate Change again (45.79%)
![Fixed interest rate 8](https://user-images.githubusercontent.com/78670969/139170793-30578c43-41b6-4908-bedf-75299de1f6d6.png)

I do Borrow now 1,5M EURT
![Fixed interest rate 9](https://user-images.githubusercontent.com/78670969/139170795-2bfcf339-9a97-4e17-9e75-a117d94f2f81.png)

The Fixed Interest Rate change again (47.58%)
![Fixed interest rate 10](https://user-images.githubusercontent.com/78670969/139170797-73e1210e-80f5-43fc-be18-39caa8a60483.png)

I try to look in my profile and then why the fixed interest rate change to be 10.41% ???
![Fixed interest rate 11](https://user-images.githubusercontent.com/78670969/139170799-d384b318-a332-41fb-9bbc-89c02351622d.png)

**Comment by reigister** [comment]
I hope i get explanation about this. it is important for user who want to do borrow in platform to know how exactly rate interest if borrow in platform @markuspluna @mootz12 @drew-boy 

Thank you for attention

**Comment by markuspluna** [comment]
Interesting, almost definitely a front end bug. We'll have to look at it once we get around to working through the rest of these bugs

**Comment by mootz12** [comment]
Marking this as duplicate to #213 , this was the original file of the bug.
