### ISSUE TITLE
Different amount collateral in profile with box update collateral. and i get additional USDC with that.

### ISSUE THREAD

**Issue by reigister** [script3/yieldblox-beta#369]
I try some experiment with collateral

First, i take my SS before i do experiment, you can see my USDC in my wallet is 333.4337987
![withdraw collateral](https://user-images.githubusercontent.com/78670969/139280408-169c700a-c435-4cbe-99d7-189d58c88352.png)

I make deposit 300 USDC and collateralized. Transactions was successfully
![withdraw collateral 2](https://user-images.githubusercontent.com/78670969/139280445-fb4d8b56-4b34-468d-901a-1d8a078a8a11.png)
![withdraw collateral 3](https://user-images.githubusercontent.com/78670969/139280450-a8f3a568-d56b-4331-822d-b6be0e9fab6c.png)
![withdraw collateral 4](https://user-images.githubusercontent.com/78670969/139280453-a37f96ab-7980-4212-86fe-34b4bd34ea0d.png)

I see in my profile there are 300 USDC lent
![withdraw collateral 5](https://user-images.githubusercontent.com/78670969/139280455-906aae1b-4b3d-4301-9adc-1970dc5a6ec8.png)

And when i want to update my collateralized to 50% i see my collateral not  300 USDC but 299.9999999669832 USDC. why not same. i think it must 300 USDC 
![withdraw collateral 6](https://user-images.githubusercontent.com/78670969/139280458-2252423c-84d5-4552-a243-9a25aa451e2d.png)

In my wallet its correct. my remain USDC is 333.4337987 - 300 = 33.4337987 USDC
![withdraw collateral 7](https://user-images.githubusercontent.com/78670969/139281913-4f7dd994-7d43-4ee3-8444-0bd485d211a4.png)

I try to update my collateral to 50% and transactions successfully
![withdraw collateral 8](https://user-images.githubusercontent.com/78670969/139283112-09ce2506-9b25-4665-a8f5-ddf3ed0c62f7.png)
![withdraw collateral 9](https://user-images.githubusercontent.com/78670969/139283325-61c27aca-2575-4247-a143-260af502573e.png)

![withdraw collateral 10](https://user-images.githubusercontent.com/78670969/139283336-cb9ba589-da91-440a-bab5-7ca57b3ec99b.png)

when i see in update collateral it show like this picture below. why not 150 USDC??
![withdraw collateral 11](https://user-images.githubusercontent.com/78670969/139283339-c94993dc-5fd4-4481-8927-4f440df668b9.png)

I try to withdraw that collateral (50% from 300 USDC) and it show more than 150USDC. and transaction was succesfull
![withdraw collateral 12](https://user-images.githubusercontent.com/78670969/139284504-bc90c1e4-9bff-4b12-baab-ec4e1b45d42c.png)

![withdraw collateral 13](https://user-images.githubusercontent.com/78670969/139284609-329e9f36-ac62-4409-b0e6-81ae42e56cae.png)

my USDC in my wallet must 33.4337987 USDC + 150.00043663739208 USDC = 183.434235337392 USDC
![withdraw collateral 14](https://user-images.githubusercontent.com/78670969/139285763-9a0a5b9b-2409-4ae6-8ca1-182f8d50d296.png)

i try to withdraw the remain 50% collateral to know if my balance USDC get increased then before (look picture 1) it must 333.4337987 USDC and then you can see this picture below my USDC get increased to be 333.4346719 USDC
![withdraw collateral 15](https://user-images.githubusercontent.com/78670969/139287025-426e6a26-9fef-45a7-b999-93e3ed9a75d8.png)

**Comment by reigister** [comment]
i found interesting bug @markuspluna, maybe this bug who make me get additional balance.
at above it show a tiny USDC because i do with 300USDC but what happen when i do with 3M USDC. i will do reproduce this bug with big USDC to see how many USDC i get for doing that. i am waiting your explanation about this bug. thank you for your attention.

**Comment by reigister** [comment]
or is it my interest?

**Comment by mootz12** [comment]
Deposits are represented as a yToken. This token exists to show how much of a share of the total USDC in the pool do you own. Thus, if people move USDC around your proportional share can differ slightly, and small rounding errors can appear.

The reason your balance increased was some1 likely paid USDC interest in the time you deposited vs withdrew, so your share of the USDC pool become more valuable.
