### ISSUE TITLE
No positions in Profile

### ISSUE THREAD

**Issue by lmorgan824** [script3/yieldblox-beta#37]
There are no positions in profile after completing three lending transactions
Create claimable balance 85,500 EURTGABH…MPNN for claimants GDGH…ZM37 (unconditional), GDNS…TZW7 (unconditional)
 Transaction 3c223d15…ef0dbdfa
5m ago
Create claimable balance 35 ETHGATP…FLMC for claimants GDGH…ZM37 (unconditional), GDNS…TZW7 (unconditional)
 Transaction 8c0cfb8f…c4c44845
7m ago
Create claimable balance 2.4 BTCGA2R…CXHA for claimants GDGH…ZM37 (unconditional), GDNS…TZW7 (unconditional)
 Transaction 6b6c9c46…a71fc27d
8m ago
Create claimable balance 100,000 USDCGAEB…O437 for claimants GDGH…ZM37 (unconditional), GDNS…TZW7 (unconditional)

**Comment by drew-boy** [comment]
Can you provide screen shots?

**Comment by mootz12** [comment]
Sounds like there was a failure while trying to deposit, which was covered in earlier bugs.
