### ISSUE TITLE
Negative APY?

### ISSUE THREAD

**Issue by cryptodmc771** [script3/yieldblox-beta#370]
<img width="1440" alt="Screen Shot 2021-10-30 at 9 33 38 PM" src="https://user-images.githubusercontent.com/92388247/139563106-2d2b2a69-b950-4a7f-b857-39601d80b1cc.png">

**Comment by silence48** [comment]
This is being caused due to there being no ybx on the testnet to work with i believe.

**Comment by mootz12** [comment]
yep

Our issuance was scheduled for ~ 3 weeks, so the amount being issued at the time of this bug was pretty minimal.

Negative APR means you are paying interest into the pool
