### ISSUE TITLE
Try to repay multiple collateral but only show 1 input in the confirmation tab

### ISSUE THREAD

**Issue by yuminachan** [script3/yieldblox-beta#372]
my input

![image](https://user-images.githubusercontent.com/76908558/140404434-8b35921d-1d9f-412d-aa83-6c79f7a9f524.png)

confirmation tab
![image](https://user-images.githubusercontent.com/76908558/140404709-53ef106e-9a4d-4a81-8703-22f294f2fde1.png)

building transaction and got this

![image](https://user-images.githubusercontent.com/76908558/140404846-935c9aac-2000-4059-b5ca-458bbbdb48b2.png)

**Comment by mootz12** [comment]
The price bot has been struggling the past few days.

My guess is the price on the DEX is outdated, which causes excess slippage to be incurred (since crypto price has been moving up only).

**Comment by yuminachan** [comment]
> 
> 
> The price bot has been struggling the past few days.
> 
> My guess is the price on the DEX is outdated, which causes excess slippage to be incurred (since crypto price has been moving up only).

My point is before confirm transaction it has 3 input data, but in confirmation tab the input is only one
![image](https://user-images.githubusercontent.com/76908558/141019636-e502f366-281e-4c72-b1a4-57b991d25296.png)

so, the point is not on price issue imo. @mootz12

**Comment by drew-boy** [comment]
Hello @yuminachan!

Could you comment one of these on your issue:

Discord username
Keybase username
Email linked to your beta account
Your YieldBlox Testnet Beta public address
Your personal public Stellar address (not recommended; post at your own risk)

It's so we can contact you and reward you a Beta Bug Bounty! :-)

**Comment by yuminachan** [comment]
@drew-boy I though send in one thread is enough 

YieldBlox Testnet Beta public address: GAPFCZXOX3KSWADVJCOZWH2I5BJXVK4P4WQAUNXS7UCU3RDW4PV2FKCM

**Comment by markuspluna** [comment]
Paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public
