### ISSUE TITLE
unable to find asset price. Cannot do anything. Bot is dead occasionally?

### ISSUE THREAD

**Issue by yuminachan** [script3/yieldblox-beta#374]
Try to repay with ETH

![image](https://user-images.githubusercontent.com/76908558/140407261-dc30100a-bd33-44ae-9968-bfa86a8cabb9.png)

but got this failed error. "unable to find asset price" 

![image](https://user-images.githubusercontent.com/76908558/140407537-31f73a3f-104e-4cea-99a5-b54b4cb8220a.png)

**Comment by mootz12** [comment]
Yep, our price bot started really having issues towards the end when we announced the beta is coming to a close.

Apologies for the trouble.
