### ISSUE TITLE
My EURT is LOSS because I reject 2nd transaction during depositing proses

### ISSUE THREAD

**Issue by yuminachan** [script3/yieldblox-beta#376]
![image](https://user-images.githubusercontent.com/76908558/140416293-cffedf30-e5c1-423b-ac7e-dafd0803e783.png)
![image](https://user-images.githubusercontent.com/76908558/140416338-39da504d-27a9-4d44-a745-96b53d46479b.png)

then success,

then 2nd tx, i cancel it
![image](https://user-images.githubusercontent.com/76908558/140416609-d8b554de-bb8b-4b48-9dc7-18a12a5a53be.png)

then error happens. i forgot to take the XDR but I believe you should be know

then I try to see to stellar explore and I see claimable for my depositing EURT here
![image](https://user-images.githubusercontent.com/76908558/140417433-aa3b4bf6-46e1-4d5b-a9f4-33726c0269a2.png)

well, I know i can claim my balance again using claimable balance, but the problem is if the new user and he/she don't know about how stellar networks work, it can make panicking. so I suggest mixing or submitting both transactions in a single transaction to avoid panicking by the user. 

IMO this problem can happen because 3 cases. 
1. Connection Lost
2. Intention to cancel depositing transaction. (can be change mind to cancel depositing or change mind to change depositing amount of balance. 
3. Transaction failed because other issue

**Comment by mootz12** [comment]
Yup, we have a story on the backlog to make this process atomic. Good catch! Marking as duplicate
