### ISSUE TITLE
Buffer Data Value Display Error 

### ISSUE THREAD

**Issue by theboycoder** [script3/yieldblox-beta#39]
I deposited the BTC for collateral but during the wallet confirmation there was a display error for the amount on the first sign in transaction 

The display errors occur for borrowing, setting up Collateral, deposits, and unauthorized ybx staking 

![display value error - Copy](https://user-images.githubusercontent.com/45983304/136296021-f1613a3e-b049-49b3-934d-4eed478747c6.png)

**Comment by theboycoder** [comment]
> 
> 
> Describe in more detail?

I tested this for borrowing, lending the different tokens.
While having 1 BTC lent, I try to deposit the BTC for collateral to borrow an increased margin, The confirmation loading screen goes through and when the wallet connects the first sign in this display error shows up on to confirm the first transaction sign in with for the operations listed above. 

![dispo2-x - Copy](https://user-images.githubusercontent.com/45983304/136299982-49880a6b-f644-40af-b452-e14d6966260e.png)

![dispo3-x - Copy](https://user-images.githubusercontent.com/45983304/136300002-a405b327-c113-4704-b6be-a627590d546d.png)

![dispo1-C - Copy](https://user-images.githubusercontent.com/45983304/136300008-5c7bf90e-3167-441e-ae95-347118aef981.png)

**Comment by mootz12** [comment]
This is only generating an access token. There was a bug with the deposit flow that likely was effecting you, and has already been resolved.
