### ISSUE TITLE
Lending workaround 

### ISSUE THREAD

**Issue by haroldmd** [script3/yieldblox-beta#42]
This is what I found:

If you tried to lend an asset you have nothing lent and use the max option, you get an error, and funds are gone. 

How it did work for me:
Lent a small amount first (feels like initializing some parameter), the transaction goes well; after that, I lent the rest using the max option and all worked.

Did it with all assets (EURT, USDC, BTC, ETH)

**Comment by mootz12** [comment]
Likely had to do with the poor auth token flow during a deposit, which has since been resolved.
