### ISSUE TITLE
Manage Collateral closes unexpectedly when dragging the slider out of the modal

### ISSUE THREAD

**Issue by fpbrault** [script3/yieldblox-beta#43]
The Manage Collateral closes unexpectedly when dragging the slider out of the modal, which is likely to happen since the edge is close
![issue](https://user-images.githubusercontent.com/1728218/136296931-4b063911-0685-412a-af59-dc8e6e638e75.gif)

**Comment by mootz12** [comment]
Slider was removed in favor of an input box.

**Comment by fpbrault** [comment]
Email linked to my beta account (for bug bounty): fpbrault@gmail.com
