### ISSUE TITLE
Can´t repay borow

### ISSUE THREAD

**Issue by LorDDark6660** [script3/yieldblox-beta#46]
repay borrow error

AAAAAgAAAAA0Uu+v4runt9Yl4Wi7Ae813aOWNAYAJUdZ6LFfDtJNvgADDUAAA6jXAAAAFAAAAAEAAAAAAAAAAAAAAABhXjLmAAAAAQAAAAh5YnhSZXBheQAAAAoAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAPAAAAAO1xDcFCJry45gbRiOTVbpORsoT8uDcZL4XUAM5wmuEmAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAA4AAAACbDAwVVNEQwAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAABKgdVugAAAAEAAAAAAAAAAA0Uu+v4runt9Yl4Wi7Ae813aOWNAYAJUdZ6LFfDtJNvgAAAAMAAAABAAAAAAAAAAAAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAQAAAAAAAAAAAAAAAAAAAAAJhAac4LhyqssutDVy8zhdPJdgMiV3JOklwPgaHdphFgAAAAEAAAAAAAYfxwAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAADwAAAAD6JEqA+daV+WfShrJSzf2wKQJpWnjNRu4E+kkkjemE4wAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMFVTREMAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAASoG6gGAAAAAwAAAAAAAAAANFLvr+K7p7fWJeFouwHvNd2jljQGACVHWeixXw7STb4AAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAAAAADVKcAAAAAAAAAAQAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAFVU0RDAAAAAAgdnkC0aoWSPp9ay/agfNXHvdoIF7+eOiOohXffMkpHAAAACVAzc7EAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAEQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAnUwMFVTREMAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAFll6YAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwVVNEQwAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAO/J100NDWjSP06V8L8wfptDLOM2HT1Q60aFNSUmcYaLAAAAAAAAAAEAAAAAAAAAAxyXJzMAAABAZ+HyfBYzeqWBMPi/+LpEs2tQ/0ZxXaa6zUs2VkiMMC/tCY43/Agr/7N7liovHROtOfUw/9QvShtSkPtkZjRrB6ICYd8AAABA9l3w+HYzb9gZPzCKxYDeOMde8iWapAruqhVIRlSXQFwepZOBjzygrvmMYbU8eprqMfXoOCkb16Dr7bT+HD76Dw7STb4AAABArftbxM7BkF7/j7i+bD4bgvGltNY/vv+78uNf8QyybnKyXAvamnMUfvWQgn6uXvh7o9+w0parHn2BLz+JxjXtCA==

**Comment by drew-boy** [comment]
duplicate clearing
