### ISSUE TITLE
UI: Amount fields too small to display max decimal places (eg Repay with Collateral)

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#51]
Issue: Size of the amount fields doesn't allow you view the max decimal places.

eg 
![image](https://user-images.githubusercontent.com/11483548/136298868-1e002d97-2a7d-4e32-ab80-462451016499.png)

Probably need to increase size and also limit max decimal places.

**Comment by drew-boy** [comment]
This isn't a bug, but we can try to make the user display easier going forward -- thanks!
