### ISSUE TITLE
Suggestion: Directly enter values rather than use sliders

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#52]
General suggestion, can their be an alternative to the sliders to directly enter the amounts?

I can be a pain to try and get to exact values. eg:

I want to change to 2 ETH directly.

![image](https://user-images.githubusercontent.com/11483548/136299162-29fce6ad-33d7-43da-8d31-feae648d0d55.png)

**Comment by mootz12** [comment]
closing in favor of https://github.com/script3/yieldblox-beta/issues/43
