### ISSUE TITLE
Bug and UI Suggestion on Account Overview

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#56]
The "k" and the words "Total value borrowed" overlapped, 
Lowering font size or create right allignment on "Total value borrowed" words is suggested.

![image](https://user-images.githubusercontent.com/91896561/136302052-94ccbaa4-c5e0-46ba-a397-8eb655f40f89.png)

**Comment by f0xie7** [comment]
Its only happen on https://ybx-beta.script3.io/#/market, on https://ybx-beta.script3.io/#/profile its better since the "Total value borrowed" is placed below the borrowed amount.

**Comment by mootz12** [comment]
This was a known issue pre beta, and has since been resolved. Thank you for the report!

**Comment by f0xie7** [comment]
f0xie#8785
