### ISSUE TITLE
Suggestion UI on Menu Balance YBX Available to Claim

### ISSUE THREAD

**Issue by davidsa05** [script3/yieldblox-beta#61]
I want to suggestion about user interface on Menu Balance YBX Available to Claim, if nominal/number of Balance YBX Available to Claim set parameter is 0 (zero), set this button to disable/unclickable first. Then if the balance > 0 the button can be active/clickable.

![Capture 1](https://user-images.githubusercontent.com/91865890/136303199-aed16551-cb7f-4fb3-ad5a-78279d726776.JPG)

**Comment by mootz12** [comment]
Thanks for the feedback! Closing to keep the bug tracker more organized to easily find what bugs have been filed
