### ISSUE TITLE
EURT gone

### ISSUE THREAD

**Issue by haroldmd** [script3/yieldblox-beta#7]
Trying to lend EURT, got an error, now there's no EURT on my wallet, Rabet.

Wallet: GCGVILQGOC7XHPLA2Z2MSSCFUCOH4IZ5PY7WPO3KL76XNGOGSYT4EN7R

![lend_eurt](https://user-images.githubusercontent.com/12978509/136290170-56503d25-3cdf-4c77-b169-62fa6dcd4afb.jpg)

![lend_eurt2](https://user-images.githubusercontent.com/12978509/136290196-d9d816ab-4eb4-4a42-8920-7fe67c4db664.jpg)

**Comment by kingrasha** [comment]
Same. Both USDC & EURT using Rabet wallet. 
Was able to deposit EURT I borrowed.

**Comment by haroldmd** [comment]
It works with small amounts, but if you try max amount, that's where I got the error.
