### ISSUE TITLE
Suggestion. Show warning when someone try to borrow more than max borrow

### ISSUE THREAD

**Issue by reigister** [script3/yieldblox-beta#71]
Please show warning when someone try to borrow more than max borrow
![borrow 1](https://user-images.githubusercontent.com/78670969/136305847-ee672eeb-6b6f-45cd-add9-6e086ae32b8f.png)
![borrow 2](https://user-images.githubusercontent.com/78670969/136305870-1aef8d6b-f09d-47f1-b3cf-bb42116359f6.png)

**Comment by mootz12** [comment]
Closing as duplicate - using https://github.com/script3/yieldblox-beta/issues/28 for input validation
