### ISSUE TITLE
Don't support values greater than max and less than 0

### ISSUE THREAD

**Issue by Garvit-k** [script3/yieldblox-beta#75]
When entering values for borrow,lending and repay dont support negative values and values greater than max also the health shouldn't go into negative

![Screenshot (650)](https://user-images.githubusercontent.com/31393258/136307352-4470dde6-3e2f-491e-9eeb-0f391f10eb02.png)
![Screenshot (651)](https://user-images.githubusercontent.com/31393258/136307356-2cbd4d84-c1eb-430f-b350-e6a5ffdb4431.png)

**Comment by drew-boy** [comment]
this isn't a bug
