### ISSUE TITLE
Typo in Confirm Borrow modal

### ISSUE THREAD

**Issue by fpbrault** [script3/yieldblox-beta#76]
There is a typo in the Confirm Borrow modal. It says "Interst Type" instead of "Interest Type"

![image](https://user-images.githubusercontent.com/1728218/136307802-136057a7-e3de-4f44-8fcc-eeac8302298f.png)

**Comment by mootz12** [comment]
Spelling is hard 😓 

Thanks for catching this!

**Comment by fpbrault** [comment]
Email linked to my beta account (for bug bounty): fpbrault@gmail.com
