### ISSUE TITLE
When using Max option for repaying, it gives me an incorrect amount and will cause the transaction to fail

### ISSUE THREAD

**Issue by Okiedokierl** [script3/yieldblox-beta#78]
![Yieldblox Max amount incorrect](https://user-images.githubusercontent.com/92068136/136307921-098e4f82-f26e-4b1f-8415-92210453c7aa.PNG)

I have .5 bitcoin borrowed, and when I hit "Max", it gives me an incorrect amount with a bunch of values off at the end of the cell.

**Comment by drew-boy** [comment]
this is just rounding from interest
