### ISSUE TITLE
Unable to borrow ETH/BTC with "Majority of turrets failed to execute contract. Service Unavailable" error message

### ISSUE THREAD

**Issue by fpbrault** [script3/yieldblox-beta#81]
I'm unable to borrow any ETH/BTC , as this error message appears:

![image](https://user-images.githubusercontent.com/1728218/136308183-600141d1-785f-48b6-9a50-83ee6891d519.png)

The amount I'm trying to borrow is within the maximum amount and my health factor is well above 1
![image](https://user-images.githubusercontent.com/1728218/136308120-92b5806d-728d-4b9a-88a6-80fadf687952.png)
![image](https://user-images.githubusercontent.com/1728218/136308134-b87f102c-198f-46f6-bb9b-d17643ac838f.png)

Here's the XDR:
`AAAAAgAAAABcPFIV+9erc/yYEhkqqbhZHWMqv1mB5BATJEKOGOP87AAAAMgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAABhX5x6AAAAAAAAAAIAAAAAAAAACgAAAANhdWQAAAAAAQAAAA5hcGkuc2NyaXB0My5pbwAAAAAAAAAAAAoAAAAOdHhGdW5jdGlvbkhhc2gAAAAAAAEAAABAZDY2OTliYTgwOTBhMjgwZTZhYjc1ZGRkODQ1M2VlOTRhMGFmNjRhN2VhOTQ4NjBmYWZmMGYyMWM3MDIxZTI2OAAAAAAAAAABGOP87AAAAEBGAzOPAehHPI6f9s8x6xSokCihYJdcg5D3uPnyVni4POJ/YiyVZHCFowM+UhgQkPtsr/aWs3djjPnzYl7Fjy8E`

**Comment by mootz12** [comment]
This was a configuration issue on our YieldBlox API that helps us make all the Stellar Turrets requests. It has been resolved.

**Comment by fpbrault** [comment]
Email linked to my beta account (for bug bounty): fpbrault@gmail.com

**Comment by markuspluna** [comment]
Bug Bounty paid in transaction:

https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjJkNzVjZTM1YTdiYTdhOTViYzczMjk1MTE2M2RlODQ0MWQ0NzY5Y2Q3OGY3NTY1ODg3MmFmZWZkZjdhNTVlMzAifQ%3D%3D&network=public
