### ISSUE TITLE
[Specification Question]Is the app available in English only?

### ISSUE THREAD

**Issue by obamaburiburi** [script3/yieldblox-beta#87]
Is YieldBlox only available in English?

Although it will incur localization costs, I believe that multi-language support will make it easier for non-English speaking users to use the service.
I would appreciate your consideration.

*Some Apps seem to offer multi-language support
- SUSHI : Support for 15 languages including English, Japanese, Simplified Chinese, and Traditional Chinese.
- UNI : Supports English and Japanese.

**Comment by drew-boy** [comment]
We want to integrate this in the future! :-)
