### ISSUE TITLE
I can stake with 0 Ybx, it was very possible to spam attack on Ybx stake contract.

### ISSUE THREAD

**Issue by backschool99** [script3/yieldblox-beta#90]
I can stake with 0 Ybx, it was very possible to spam attack on Ybx stake contract.

It is very possible to attack Ybx stake contract in the future mainnet, this is my proof transaction.
https://stellar.expert/explorer/testnet/tx/ea838e7fc6a93456eb57f0fbe16d08d5253371bce50f48ae1b12aedf967f21ee

It should be set a trigger value, like 0 is not allowed and message warning will show up/anything not happen.

![Screenshot (132)](https://user-images.githubusercontent.com/88925777/136314273-6b15473a-b13a-4ab5-a52d-49df1074d031.png)
![Screenshot (131)](https://user-images.githubusercontent.com/88925777/136314278-3f22fea6-b429-4fff-95cc-9d4287c17c2c.png)

**Comment by mootz12** [comment]
See https://github.com/script3/yieldblox-beta/issues/26
