### ISSUE TITLE
There is an error when I borrow third token

### ISSUE THREAD

**Issue by minhtung1595** [script3/yieldblox-beta#94]
![image](https://user-images.githubusercontent.com/33053228/136318862-41414e34-0f3d-4625-a0ef-1ddadd1e5226.png)

I borrow BTC, it;s success.
I borrow ETH, it's success
When I borrow third time with USDC token, it show an error as image i sent

**Comment by mootz12** [comment]
This was an old error that has since been resolved, due to a timeout limitation on the Stellar Turret.
