### ISSUE TITLE
[Suggestions][UI] YBX Claim Modal and Staked YBX Grid

### ISSUE THREAD

**Issue by vv181** [script3/yieldblox-beta#96]
![img](https://i.imgur.com/R0006P2.png) ![img](https://i.imgur.com/ZebDzgB.png)

Personally, when I look at that, I feel like somethings is off. One thing for sure is, the button position could/should be positioned better. Or maybe the whole UI can be overhauled to maximize the white space. I'm sure the UI would look much better.

**Comment by mootz12** [comment]
Thanks for the feedback! We will keep this in mind as we continue to make improvements. Closing this issue to clean up the issue tracker to bugs.
