### ISSUE TITLE
Problems in setting the clock on the device may cause the deposit to fail

### ISSUE THREAD

**Issue by hendra677** [script3/yieldblox-beta#97]
I made a deposit in my account with the wrong clock setting on my device. This results in a failed deposit.
And the error message that appears does not lead us to a solution that must be completed.
The error message should appear and direct the user to immediately set the clock settings on the device.
![unknown](https://user-images.githubusercontent.com/55767936/136319452-fa00f7ac-cf28-41da-823b-334c44e651e1.png)

**Comment by mootz12** [comment]
Your system doesn't specify many timestamps on our app. The only error I could imagine is an invalid token, but that doesn't seem to be the case.

Closing for now, if you provide further detail I am happy to take a closer look.

**Comment by hendra677** [comment]
screenshots of other details, I don't have any more. because maybe this bug is fixed.
My suggestion for errors caused by timings, the error message that appears should indicate that this is caused by incorrect timings.

**Comment by hendra677** [comment]
- Discord username                                  : hendra677#2202
- Email linked to beta account                : Hendratroy79@gmail.com
- YieldBlox Testnet Beta public address  : GBXN6AXTYGEXLZKXEUVDWRA6D6MU4KXXEL2ZIF6XUZI6VW666BJ4HQKI
- Personal public Stellar address             : GA5WF2XSLU22542I6XIN6HG6JXQP4XZYXQTSHKA6SG4YPZGFMSXM6GHU
